#!/usr/bin/env python

from typing import TYPE_CHECKING

from SCons.Script.SConscript import SConsEnvironment

import editor.template_builders as build_template_gd

if TYPE_CHECKING:
    env = SConsEnvironment()
    Import = SConsEnvironment.Import

Import("env")

env["BUILDERS"]["MakeGDTemplateBuilder"] = env.Builder(
    action=env.Run(build_template_gd.make_templates),
    suffix=".h",
    src_suffix=".gd",
)

# Template files
templates_sources = env.Glob("*/*.gd")

env.Alias("editor_template_gd", [env.MakeGDTemplateBuilder("templates.gen.h", templates_sources)])
