#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

import editor.template_builders as build_template_gd

env.CommandNoCache("templates.gen.h", Glob("*/*.gd"), env.Run(build_template_gd.make_templates))
