#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

if "sndio" in env and env["sndio"]:
    if env["use_sowrap"]:
        env.add_source_files(env.drivers_sources, "sndio-so_wrap.c")

env.add_source_files(env.drivers_sources, "*.cpp")
