// This file is generated. Do not edit!
// see https://github.com/hpvb/dynload-wrapper for details
// generated by generate-wrapper.py 0.7 on 2026-03-22 15:53:05
// flags: generate-wrapper.py --include ./thirdparty/linuxbsd_headers/sndio/sndio.h --sys-include thirdparty/linuxbsd_headers/sndio/sndio.h --soname libsndio.so.7 --soname __OpenBSD__,libsndio.so --init-name sndio --output-header ./drivers/sndio/sndio-so_wrap.h --output-implementation ./drivers/sndio/sndio-so_wrap.c --omit-prefix mio_ --omit-prefix sio_sun_ --omit-prefix sioctl_sun_
//
#include <stdint.h>

#define sio_initpar sio_initpar_dylibloader_orig_sndio
#define sio_open sio_open_dylibloader_orig_sndio
#define sio_close sio_close_dylibloader_orig_sndio
#define sio_setpar sio_setpar_dylibloader_orig_sndio
#define sio_getpar sio_getpar_dylibloader_orig_sndio
#define sio_getcap sio_getcap_dylibloader_orig_sndio
#define sio_onmove sio_onmove_dylibloader_orig_sndio
#define sio_write sio_write_dylibloader_orig_sndio
#define sio_read sio_read_dylibloader_orig_sndio
#define sio_start sio_start_dylibloader_orig_sndio
#define sio_stop sio_stop_dylibloader_orig_sndio
#define sio_flush sio_flush_dylibloader_orig_sndio
#define sio_nfds sio_nfds_dylibloader_orig_sndio
#define sio_pollfd sio_pollfd_dylibloader_orig_sndio
#define sio_revents sio_revents_dylibloader_orig_sndio
#define sio_eof sio_eof_dylibloader_orig_sndio
#define sio_setvol sio_setvol_dylibloader_orig_sndio
#define sio_onvol sio_onvol_dylibloader_orig_sndio
#define sioctl_open sioctl_open_dylibloader_orig_sndio
#define sioctl_close sioctl_close_dylibloader_orig_sndio
#define sioctl_ondesc sioctl_ondesc_dylibloader_orig_sndio
#define sioctl_onval sioctl_onval_dylibloader_orig_sndio
#define sioctl_setval sioctl_setval_dylibloader_orig_sndio
#define sioctl_nfds sioctl_nfds_dylibloader_orig_sndio
#define sioctl_pollfd sioctl_pollfd_dylibloader_orig_sndio
#define sioctl_revents sioctl_revents_dylibloader_orig_sndio
#define sioctl_eof sioctl_eof_dylibloader_orig_sndio
#include "thirdparty/linuxbsd_headers/sndio/sndio.h" // IWYU pragma: export.
#undef sio_initpar
#undef sio_open
#undef sio_close
#undef sio_setpar
#undef sio_getpar
#undef sio_getcap
#undef sio_onmove
#undef sio_write
#undef sio_read
#undef sio_start
#undef sio_stop
#undef sio_flush
#undef sio_nfds
#undef sio_pollfd
#undef sio_revents
#undef sio_eof
#undef sio_setvol
#undef sio_onvol
#undef sioctl_open
#undef sioctl_close
#undef sioctl_ondesc
#undef sioctl_onval
#undef sioctl_setval
#undef sioctl_nfds
#undef sioctl_pollfd
#undef sioctl_revents
#undef sioctl_eof
#include <dlfcn.h>
#include <stdio.h>
void (*sio_initpar_dylibloader_wrapper_sndio)(struct sio_par *);
struct sio_hdl *(*sio_open_dylibloader_wrapper_sndio)(const char *, unsigned int, int);
void (*sio_close_dylibloader_wrapper_sndio)(struct sio_hdl *);
int (*sio_setpar_dylibloader_wrapper_sndio)(struct sio_hdl *, struct sio_par *);
int (*sio_getpar_dylibloader_wrapper_sndio)(struct sio_hdl *, struct sio_par *);
int (*sio_getcap_dylibloader_wrapper_sndio)(struct sio_hdl *, struct sio_cap *);
void (*sio_onmove_dylibloader_wrapper_sndio)(struct sio_hdl *, void (*)(void *, int), void *);
size_t (*sio_write_dylibloader_wrapper_sndio)(struct sio_hdl *, const void *, size_t);
size_t (*sio_read_dylibloader_wrapper_sndio)(struct sio_hdl *, void *, size_t);
int (*sio_start_dylibloader_wrapper_sndio)(struct sio_hdl *);
int (*sio_stop_dylibloader_wrapper_sndio)(struct sio_hdl *);
int (*sio_flush_dylibloader_wrapper_sndio)(struct sio_hdl *);
int (*sio_nfds_dylibloader_wrapper_sndio)(struct sio_hdl *);
int (*sio_pollfd_dylibloader_wrapper_sndio)(struct sio_hdl *, struct pollfd *, int);
int (*sio_revents_dylibloader_wrapper_sndio)(struct sio_hdl *, struct pollfd *);
int (*sio_eof_dylibloader_wrapper_sndio)(struct sio_hdl *);
int (*sio_setvol_dylibloader_wrapper_sndio)(struct sio_hdl *, unsigned int);
int (*sio_onvol_dylibloader_wrapper_sndio)(struct sio_hdl *, void (*)(void *, unsigned int), void *);
struct sioctl_hdl *(*sioctl_open_dylibloader_wrapper_sndio)(const char *, unsigned int, int);
void (*sioctl_close_dylibloader_wrapper_sndio)(struct sioctl_hdl *);
int (*sioctl_ondesc_dylibloader_wrapper_sndio)(struct sioctl_hdl *, void (*)(void *, struct sioctl_desc *, int), void *);
int (*sioctl_onval_dylibloader_wrapper_sndio)(struct sioctl_hdl *, void (*)(void *, unsigned int, unsigned int), void *);
int (*sioctl_setval_dylibloader_wrapper_sndio)(struct sioctl_hdl *, unsigned int, unsigned int);
int (*sioctl_nfds_dylibloader_wrapper_sndio)(struct sioctl_hdl *);
int (*sioctl_pollfd_dylibloader_wrapper_sndio)(struct sioctl_hdl *, struct pollfd *, int);
int (*sioctl_revents_dylibloader_wrapper_sndio)(struct sioctl_hdl *, struct pollfd *);
int (*sioctl_eof_dylibloader_wrapper_sndio)(struct sioctl_hdl *);
#ifdef __OpenBSD__
#define SONAME "libsndio.so"
#else
#define SONAME "libsndio.so.7"
#endif
int initialize_sndio(int verbose) {
  void *handle;
  char *error;
  handle = dlopen(SONAME, RTLD_LAZY);
  if (!handle) {
    if (verbose) {
      fprintf(stderr, "%s\n", dlerror());
    }
    return(1);
  }
  dlerror();
// sio_initpar
  *(void **) (&sio_initpar_dylibloader_wrapper_sndio) = dlsym(handle, "sio_initpar");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// sio_open
  *(void **) (&sio_open_dylibloader_wrapper_sndio) = dlsym(handle, "sio_open");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// sio_close
  *(void **) (&sio_close_dylibloader_wrapper_sndio) = dlsym(handle, "sio_close");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// sio_setpar
  *(void **) (&sio_setpar_dylibloader_wrapper_sndio) = dlsym(handle, "sio_setpar");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// sio_getpar
  *(void **) (&sio_getpar_dylibloader_wrapper_sndio) = dlsym(handle, "sio_getpar");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// sio_getcap
  *(void **) (&sio_getcap_dylibloader_wrapper_sndio) = dlsym(handle, "sio_getcap");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// sio_onmove
  *(void **) (&sio_onmove_dylibloader_wrapper_sndio) = dlsym(handle, "sio_onmove");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// sio_write
  *(void **) (&sio_write_dylibloader_wrapper_sndio) = dlsym(handle, "sio_write");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// sio_read
  *(void **) (&sio_read_dylibloader_wrapper_sndio) = dlsym(handle, "sio_read");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// sio_start
  *(void **) (&sio_start_dylibloader_wrapper_sndio) = dlsym(handle, "sio_start");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// sio_stop
  *(void **) (&sio_stop_dylibloader_wrapper_sndio) = dlsym(handle, "sio_stop");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// sio_flush
  *(void **) (&sio_flush_dylibloader_wrapper_sndio) = dlsym(handle, "sio_flush");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// sio_nfds
  *(void **) (&sio_nfds_dylibloader_wrapper_sndio) = dlsym(handle, "sio_nfds");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// sio_pollfd
  *(void **) (&sio_pollfd_dylibloader_wrapper_sndio) = dlsym(handle, "sio_pollfd");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// sio_revents
  *(void **) (&sio_revents_dylibloader_wrapper_sndio) = dlsym(handle, "sio_revents");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// sio_eof
  *(void **) (&sio_eof_dylibloader_wrapper_sndio) = dlsym(handle, "sio_eof");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// sio_setvol
  *(void **) (&sio_setvol_dylibloader_wrapper_sndio) = dlsym(handle, "sio_setvol");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// sio_onvol
  *(void **) (&sio_onvol_dylibloader_wrapper_sndio) = dlsym(handle, "sio_onvol");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// sioctl_open
  *(void **) (&sioctl_open_dylibloader_wrapper_sndio) = dlsym(handle, "sioctl_open");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// sioctl_close
  *(void **) (&sioctl_close_dylibloader_wrapper_sndio) = dlsym(handle, "sioctl_close");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// sioctl_ondesc
  *(void **) (&sioctl_ondesc_dylibloader_wrapper_sndio) = dlsym(handle, "sioctl_ondesc");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// sioctl_onval
  *(void **) (&sioctl_onval_dylibloader_wrapper_sndio) = dlsym(handle, "sioctl_onval");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// sioctl_setval
  *(void **) (&sioctl_setval_dylibloader_wrapper_sndio) = dlsym(handle, "sioctl_setval");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// sioctl_nfds
  *(void **) (&sioctl_nfds_dylibloader_wrapper_sndio) = dlsym(handle, "sioctl_nfds");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// sioctl_pollfd
  *(void **) (&sioctl_pollfd_dylibloader_wrapper_sndio) = dlsym(handle, "sioctl_pollfd");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// sioctl_revents
  *(void **) (&sioctl_revents_dylibloader_wrapper_sndio) = dlsym(handle, "sioctl_revents");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// sioctl_eof
  *(void **) (&sioctl_eof_dylibloader_wrapper_sndio) = dlsym(handle, "sioctl_eof");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
return 0;
}
