#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_gridmap = env_modules.Clone()

# Godot source files
env_gridmap.add_source_files(env["MODULES_SOURCES"], "*.cpp")
if env["EDITOR_BUILD"]:
    env_gridmap.add_source_files(env["MODULES_SOURCES"], "editor/*.cpp")
