#!/usr/bin/env python

Import('env')

thirdparty_dir = "#thirdparty/bullet/"
thirdparty_lib = thirdparty_dir + "Win64/lib/"

bullet_libs = [
        "Bullet2FileLoader",
        "Bullet3Collision",
        "Bullet3Common",
        "Bullet3Dynamics",
        "Bullet3Geometry",
        "Bullet3OpenCL_clew",
        "BulletCollision",
        "BulletDynamics",
        "BulletInverseDynamics",
        "BulletSoftBody",
        "LinearMath"
    ]

thirdparty_src = thirdparty_dir + "src/"
# include headers
env.Append(CPPPATH=[thirdparty_src])

# lib
env.Append(LIBPATH=[thirdparty_dir + "/Win64/lib/"])

bullet_libs = [file+'.lib' for file in bullet_libs]
# LIBS doesn't work in windows
env.Append(LINKFLAGS=bullet_libs)

env.add_source_files(env.modules_sources, "*.cpp")
