#!/usr/bin/env python

Import("env")
Import("env_gdnative")

env_gdnative.add_source_files(env.modules_sources, "*.cpp")

if "selected_platform" in env and env["selected_platform"] in ["linuxbsd", "iphone"]:
    env.Append(LINKFLAGS=["-rdynamic"])
