#!/usr/bin/env python

Import("env")
Import("env_gdnative")

env_gdnative.add_source_files(env.modules_sources, "*.cpp")

if "platform" in env and env["platform"] in ["x11", "iphone"]:
    env.Append(LINKFLAGS=["-rdynamic"])
