#!/usr/bin/env python

Import("env")

local_sources = env.glob_files('*.cpp') + env.glob_files('*.h')
env.add_project_sources(local_sources)
env.add_objects_from_sources(env.core_objects, local_sources)