#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.add_source_files(env.editor_sources, "*.cpp")

SConscript("2d/SCsub")
SConscript("animation/SCsub")
SConscript("gizmos/SCsub")
SConscript("shader/SCsub")
SConscript("tiles/SCsub")
