#!/usr/bin/env python

# SCsub

Import('env')

env_tts = env

env_tts.add_source_files(env.modules_sources,"*.cpp") # Add all cpp files to the build

env_tts.Append(CPPPATH=['speech_tools/include', 'festival/src/include'])
# http://www.cstr.ed.ac.uk/projects/festival/manual/festival_28.html#SEC132 <-- Festival library documentation
env_tts.Append(LIBPATH=['libpath'])
env_tts.Append(LIBS=['Festival', 'estools', 'estbase', 'eststring'])
