#!/usr/bin/env python

Import('env')

if (env["platform"] in ["haiku", "osx", "windows", "x11"]):
    # FIXME: Dead code, now using GLAD
    """
    # Thirdparty source files
    if (env['builtin_glew'] != 'no'):  # builtin

        thirdparty_dir = "#thirdparty/glew/"
        thirdparty_sources = [
            "glew.c",
        ]
        thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

        env.add_source_files(env.drivers_sources, thirdparty_sources)
        env.Append(CPPFLAGS=['-DGLEW_STATIC'])
        env.Append(CPPPATH=[thirdparty_dir])

    env.Append(CPPFLAGS=['-DGLEW_ENABLED'])
    """

    env.add_source_files(env.drivers_sources,"glad.c")
    env.Append(CPPFLAGS = ['-DGLAD_ENABLED'])
    env.Append(CPPFLAGS = ['-DGLES_OVER_GL'])
    env.Append(CPPPATH = ['.'])

# Godot source files
env.add_source_files(env.drivers_sources, "*.cpp")

Export('env')
