#!/usr/bin/env python

Import('env')

import os
from platform_methods import run_in_subprocess
import platform_unix_builders

common_unix = [
    "crash_handler_unix.cpp",
    "detect_prime.cpp",
    "joypad_linux.cpp",
    "os_genericunix.cpp",
    "power_unix.cpp",
    "x11/context_gl_x11.cpp",
    "x11/key_mapping_x11.cpp",
    "x11/os_x11.cpp",
    "wayland/context_egl_wayland.cpp",
    "wayland/key_mapping_xkb.cpp",
    "wayland/os_wayland.cpp",
]

prog = env.add_program('#bin/godot', ['godot_unix.cpp'] + common_unix)

env.Append(LIBS=["wayland-client", "wayland-egl", "wayland-server", "libEGL"])

if (env["debug_symbols"] == "full" or env["debug_symbols"] == "yes") and env["separate_debug_symbols"]:
    env.AddPostAction(prog, run_in_subprocess(
        platform_unix_builders.make_debug_unix))
