#!/usr/bin/env python

Import("env")
Import("env_modules")

env_flac = env_modules.Clone()
env_flac.disable_warnings()
env_flac.Append(CPPPATH=["#thirdparty"])

env_flac.add_source_files(env.modules_sources, "*.cpp")
