#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.add_source_files(env["SCENE_SOURCES"], "*.cpp")

# Chain load SCsubs
if not env["disable_physics_2d"]:
    SConscript("physics/SCsub")
if not env["disable_navigation_2d"]:
    SConscript("navigation/SCsub")
