#!/usr/bin/env python

Import("env")

if "GLES2_GLSL" in env["BUILDERS"]:
    env.GLES2_GLSL("copy.glsl")
    # env.GLES2_GLSL('resolve.glsl');
    env.GLES2_GLSL("canvas.glsl")
    env.GLES2_GLSL("canvas_shadow.glsl")
    env.GLES2_GLSL("scene.glsl")
    env.GLES2_GLSL("cubemap_filter.glsl")
    env.GLES2_GLSL("cube_to_dp.glsl")
    # env.GLES2_GLSL('blend_shape.glsl');
    # env.GLES2_GLSL('screen_space_reflection.glsl');
    env.GLES2_GLSL("effect_blur.glsl")
    # env.GLES2_GLSL('subsurf_scattering.glsl');
    # env.GLES2_GLSL('ssao.glsl');
    # env.GLES2_GLSL('ssao_minify.glsl');
    # env.GLES2_GLSL('ssao_blur.glsl');
    # env.GLES2_GLSL('exposure.glsl');
    env.GLES2_GLSL("tonemap.glsl")
    # env.GLES2_GLSL('particles.glsl');
    env.GLES2_GLSL("lens_distorted.glsl")
