#!/usr/bin/env python

Import('env')

if 'GLSL120GLES' in env['BUILDERS']:
    env.GLSL120GLES('material.glsl')
    env.GLSL120GLES('canvas.glsl')
    env.GLSL120GLES('canvas_shadow.glsl')
    env.GLSL120GLES('blur.glsl')
    env.GLSL120GLES('copy.glsl')

Export('env')
