#!/usr/bin/env python

Import("env")
Import("env_modules")

env_blazium_sdk = env_modules.Clone()
env_blazium_sdk.add_source_files(env.modules_sources, "lobby/*.cpp")
env_blazium_sdk.add_source_files(env.modules_sources, "*.cpp")
