#!/usr/bin/env python
from misc.utility.scons_hints import *

import os
import sys

Import("env", "py_builder_env")

# Editor's own icons
icon_sources = Glob("*.svg")

# Module icons
for path in env.module_icons_paths:
    if not os.path.isabs(path):
        icon_sources += Glob(f"#{path}/*.svg")  # Built-in.
    else:
        icon_sources += Glob(f"{path}/*.svg")  # Custom.

py_builder_env.Command(
    "#editor/themes/editor_icons.gen.h",
    icon_sources,
    Action(
        f"{sys.executable} editor/icons/editor_icons_builders.py --method make_editor_icons_action --target $TARGET --source $SOURCES",
        "$GENCOMSTR",
    ),
)
