#!/usr/bin/env python

from typing import TYPE_CHECKING

from SCons.Script.SConscript import SConsEnvironment

import editor.template_builders as build_template_cs

if TYPE_CHECKING:
    env = SConsEnvironment()
    Import = SConsEnvironment.Import

Import("env")

env["BUILDERS"]["MakeCSharpTemplateBuilder"] = env.Builder(
    action=env.Run(build_template_cs.make_templates),
    suffix=".h",
    src_suffix=".cs",
)

# Template files
templates_sources = env.Glob("*/*.cs")

env.Alias("editor_template_cs", [env.MakeCSharpTemplateBuilder("templates.gen.h", templates_sources)])
