#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

import editor.template_builders as build_template_cs

env.CommandNoCache("templates.gen.h", Glob("*/*.cs"), env.Run(build_template_cs.make_templates))
