#!/usr/bin/env python
from misc.utility.scons_hints import *

import sys

Import("py_builder_env")

py_builder_env.Command(
    "templates.gen.h",
    Glob("*/*.cs"),
    Action(
        f"{sys.executable} editor/template_builders.py --method make_templates --target $TARGET --source $SOURCES",
        "Generating $TARGET",
    ),
)
