short_name = "redot"
name = "Redot Engine"
major = 4
minor = 3
patch = 1
status = "rc"
module_config = ""
website = "https://redotengine.org"
docs = "4.3"
godot_major = 4
godot_minor = 3
godot_patch = 1
godot_status = "dev"
