#!/usr/bin/env python
from misc.utility.scons_hints import *

import sys

Import("env", "py_builder_env")

env.main_sources = []

env_main = env.Clone()

env_main.add_source_files(env.main_sources, "*.cpp")

if env["steamapi"] and env.editor_build:
    env_main.Append(CPPDEFINES=["STEAMAPI_ENABLED"])

if env["tests"]:
    env_main.Append(CPPDEFINES=["TESTS_ENABLED"])

py_builder_env.Command(
    "#main/splash.gen.h",
    "#main/splash.png",
    Action(
        "$PYTHON_BIN main/main_builders.py --method make_splash --target $TARGET --source $SOURCE",
        "$GENCOMSTR",
    ),
)

if env_main.editor_build and not env_main["no_editor_splash"]:
    py_builder_env.Command(
        "#main/splash_editor.gen.h",
        "#main/splash_editor.png",
        Action(
            "$PYTHON_BIN main/main_builders.py --method make_splash_editor --target $TARGET --source $SOURCE",
            "$GENCOMSTR",
        ),
    )

py_builder_env.Command(
    "#main/app_icon.gen.h",
    "#main/app_icon.png",
    Action(
        "$PYTHON_BIN main/main_builders.py --method make_app_icon --target $TARGET --source $SOURCE",
        "$GENCOMSTR",
    ),
)

lib = env_main.add_library("main", env.main_sources)
env.Prepend(LIBS=[lib])
