#!/usr/bin/env python

Import("env")

env.editordeps_sources = []

# Godot source files
env.add_source_files(env.editordeps_sources, "*.cpp")

# Build it all as a library
lib = env.add_library("editordeps", env.editordeps_sources)
env.Prepend(LIBS=[lib])
