#!/usr/bin/env python

Import("env")

# Thirdparty code

thirdparty_obj = []

env_thirdparty = env.Clone()
env_thirdparty.disable_warnings()
env.scene_sources += thirdparty_obj

# Godot source files

scene_obj = []

env.add_source_files(scene_obj, "*.cpp")
env.scene_sources += scene_obj

# Needed to force rebuilding the scene files when the thirdparty code is updated.
env.Depends(scene_obj, thirdparty_obj)
