#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_vertex_mobile = env_modules.Clone()
env_vertex_mobile.add_source_files(env.modules_sources, "*.cpp")

if env.editor_build:
    env_vertex_mobile.add_source_files(env.modules_sources, "editor/*.cpp")
