#!/usr/bin/env python
from misc.utility.scons_hints import *

import platform_ios_builders

Import("env")

ios_lib = [
    "godot_ios.mm",
    "os_ios.mm",
    "main.m",
    "app_delegate.mm",
    "view_controller.mm",
    "ios.mm",
    "rendering_context_driver_vulkan_ios.mm",
    "display_server_ios.mm",
    "godot_view.mm",
    "tts_ios.mm",
    "display_layer.mm",
    "godot_app_delegate.m",
    "godot_view_renderer.mm",
    "device_metrics.m",
    "keyboard_input_view.mm",
    "key_mapping_ios.mm",
    "ios_terminal_logger.mm",
]

env_ios = env.Clone()
ios_lib = env_ios.add_library("ios", ios_lib)

# (iOS) Enable module support
env_ios.Append(CCFLAGS=["-fmodules", "-fcxx-modules"])


combine_command = env_ios.CommandNoCache(
    "#bin/libgodot" + env_ios["LIBSUFFIX"], [ios_lib] + env_ios["LIBS"], env.Run(platform_ios_builders.combine_libs)
)

if env["generate_bundle"]:
    env.AlwaysBuild(
        env.CommandNoCache("generate_bundle", combine_command, env.Run(platform_ios_builders.generate_bundle))
    )
