#!/usr/bin/env python

Import("env")
Import("env_modules")

env_inappstore = env_modules.Clone()

# (iOS) Enable module support
env_inappstore.Append(CCFLAGS=["-fmodules", "-fcxx-modules"])

# (iOS) Build as separate static library
modules_sources = []
env_inappstore.add_source_files(modules_sources, "*.cpp")
env_inappstore.add_source_files(modules_sources, "*.mm")
mod_lib = env_modules.add_library("#bin/libgodot_inappstore_module" + env["LIBSUFFIX"], modules_sources)
