#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_modules.Append(CPPDEFINES=["GODOT_MODULE"])

env_visual_shader = env_modules.Clone()

env_visual_shader.add_source_files(env["MODULES_SOURCES"], "*.cpp")
env_visual_shader.add_source_files(env["MODULES_SOURCES"], "vs_nodes/*.cpp")

if env["EDITOR_BUILD"]:
    env_visual_shader.add_source_files(env["MODULES_SOURCES"], "editor/*.cpp")
