#!/usr/bin/env python
from misc.utility.scons_hints import *

# This file is for building as a Godot engine module.

Import("env")
Import("env_modules")

env_modules.Append(CPPDEFINES=["GODOT_MODULE"])

env_visual_shader = env_modules.Clone()

env_visual_shader.add_source_files(env.modules_sources, "*.cpp")
env_visual_shader.add_source_files(env.modules_sources, "vs_nodes/*.cpp")

if env.editor_build:
    env_visual_shader.add_source_files(env.modules_sources, "editor/*.cpp")
