#!/usr/bin/env python

from typing import TYPE_CHECKING

from SCons.Script.SConscript import SConsEnvironment

if TYPE_CHECKING:
    env = SConsEnvironment()
    env_modules = SConsEnvironment()
    Import = SConsEnvironment.Import

Import("env")
Import("env_modules")

env_mp = env_modules.Clone()

module_obj = []
env_mp.add_source_files(module_obj, "*.cpp")

if env.editor_build:
    env_mp.add_source_files(module_obj, "editor/*.cpp")

env.modules_sources += module_obj
