#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

if env.msvc:
    env.Append(
        LINKFLAGS=["mfplat.lib", "mf.lib", "wmcodecdspuuid.lib", "mfuuid.lib", "mfreadwrite.lib", "strmiids.lib"]
    )
else:
    env.Append(LIBS=["mfplat", "mf", "wmcodecdspuuid", "mfuuid", "mfreadwrite", "strmiids"])

Import("env_modules")

env_wmf = env_modules.Clone()

env_wmf.add_source_files(env.modules_sources, "*.cpp")
Export("env")
