#!/usr/bin/env python

Import('env')
Import('env_modules')

env_cvtt = env_modules.Clone()

# Thirdparty source files
if env['builtin_squish']:
    thirdparty_dir = "#thirdparty/cvtt/"
    thirdparty_sources = [
        "ConvectionKernels.cpp"
    ]

    thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

    env_cvtt.add_source_files(env.modules_sources, thirdparty_sources)
    env_cvtt.Append(CPPPATH=[thirdparty_dir])

# Godot source files
env_cvtt.add_source_files(env.modules_sources, "*.cpp")
