using System;

namespace Godot.SourceGenerators
{
    internal enum VariantType
    {
        Nil = 0,
        Bool = 1,
        Int = 2,
        Float = 3,
        String = 4,
        Vector2 = 5,
        Vector2i = 6,
        Rect2 = 7,
        Rect2i = 8,
        Vector3 = 9,
        Vector3i = 10,
        Transform2d = 11,
        Plane = 12,
        Quaternion = 13,
        Aabb = 14,
        Basis = 15,
        Transform3d = 16,
        Color = 17,
        StringName = 18,
        NodePath = 19,
        Rid = 20,
        Object = 21,
        Callable = 22,
        Signal = 23,
        Dictionary = 24,
        Array = 25,
        PackedByteArray = 26,
        PackedInt32Array = 27,
        PackedInt64Array = 28,
        PackedFloat32Array = 29,
        PackedFloat64Array = 30,
        PackedStringArray = 31,
        PackedVector2Array = 32,
        PackedVector3Array = 33,
        PackedColorArray = 34,
        Max = 35
    }

    internal enum PropertyHint
    {
        None = 0,
        Range = 1,
        Enum = 2,
        EnumSuggestion = 3,
        ExpEasing = 4,
        Length = 5,
        KeyAccel = 6,
        Flags = 7,
        Layers2dRender = 8,
        Layers2dPhysics = 9,
        Layers2dNavigation = 10,
        Layers3dRender = 11,
        Layers3dPhysics = 12,
        Layers3dNavigation = 13,
        File = 14,
        Dir = 15,
        GlobalFile = 16,
        GlobalDir = 17,
        ResourceType = 18,
        MultilineText = 19,
        PlaceholderText = 20,
        ColorNoAlpha = 21,
        ImageCompressLossy = 22,
        ImageCompressLossless = 23,
        ObjectId = 24,
        TypeString = 25,
        NodePathToEditedNode = 26,
        MethodOfVariantType = 27,
        MethodOfBaseType = 28,
        MethodOfInstance = 29,
        MethodOfScript = 30,
        PropertyOfVariantType = 31,
        PropertyOfBaseType = 32,
        PropertyOfInstance = 33,
        PropertyOfScript = 34,
        ObjectTooBig = 35,
        NodePathValidTypes = 36,
        SaveFile = 37,
        IntIsObjectId = 38,
        IntIsPointer = 40,
        ArrayType = 39,
        LocaleId = 41,
        Max = 42
    }

    [Flags]
    internal enum PropertyUsageFlags
    {
        None = 0,
        Storage = 1,
        Editor = 2,
        Network = 4,
        EditorHelper = 8,
        Checkable = 16,
        Checked = 32,
        Internationalized = 64,
        Group = 128,
        Category = 256,
        Subgroup = 512,
        NoInstanceState = 2048,
        RestartIfChanged = 4096,
        ScriptVariable = 8192,
        StoreIfNull = 16384,
        AnimateAsTrigger = 32768,
        UpdateAllIfModified = 65536,
        ScriptDefaultValue = 131072,
        ClassIsEnum = 262144,
        NilIsVariant = 524288,
        Internal = 1048576,
        DoNotShareOnDuplicate = 2097152,
        HighEndGfx = 4194304,
        NodePathFromSceneRoot = 8388608,
        ResourceNotPersistent = 16777216,
        KeyingIncrements = 33554432,
        DeferredSetResource = 67108864,
        EditorInstantiateObject = 134217728,
        EditorBasicSetting = 268435456,
        Array = 1073741824,
        Default = 7,
        DefaultIntl = 71,
        NoEditor = 5
    }
}
