#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_qbo = env_modules.Clone()

# Thirdparty source files

thirdparty_obj = []

env_thirdparty = env_qbo.Clone()
env_thirdparty.disable_warnings()

thirdparty_sources = []

env_thirdparty.add_source_files(thirdparty_obj, thirdparty_sources)
env.modules_sources += thirdparty_obj

# Godot source files

module_obj = []

env_qbo.add_source_files(module_obj, "*.cpp")

env.modules_sources += module_obj

# Needed to force rebuilding the module files when the thirdparty library is updated.
env.Depends(module_obj, thirdparty_obj)

if env.editor_build:
    env_qbo.add_source_files(env.modules_sources, "editor/*.cpp")
