#!/usr/bin/env python

from typing import TYPE_CHECKING

from SCons.Script.SConscript import SConsEnvironment

if TYPE_CHECKING:
    env = SConsEnvironment()
    Import = SConsEnvironment.Import

Import("env")

# Thirdparty code

thirdparty_obj = []

thirdparty_sources = "#thirdparty/misc/mikktspace.c"

env_thirdparty = env.Clone()
env_thirdparty.disable_warnings()
env_thirdparty.add_source_files(thirdparty_obj, thirdparty_sources)
env.scene_sources += thirdparty_obj

# Godot source files

scene_obj = []

env.add_source_files(scene_obj, "*.cpp")
env.scene_sources += scene_obj

# Needed to force rebuilding the scene files when the thirdparty code is updated.
env.Depends(scene_obj, thirdparty_obj)

env.SConscript("2d/SCsub")
if not env["disable_3d"]:
    env.SConscript("3d/SCsub")
