/**************************************************************************/
/*  physics_server_3d_enums.h                                             */
/**************************************************************************/
/*                         This file is part of:                          */
/*                             GODOT ENGINE                               */
/*                        https://godotengine.org                         */
/**************************************************************************/
/* Copyright (c) 2014-present Godot Engine contributors (see AUTHORS.md). */
/* Copyright (c) 2007-2014 Juan Linietsky, Ariel Manzur.                  */
/*                                                                        */
/* Permission is hereby granted, free of charge, to any person obtaining  */
/* a copy of this software and associated documentation files (the        */
/* "Software"), to deal in the Software without restriction, including    */
/* without limitation the rights to use, copy, modify, merge, publish,    */
/* distribute, sublicense, and/or sell copies of the Software, and to     */
/* permit persons to whom the Software is furnished to do so, subject to  */
/* the following conditions:                                              */
/*                                                                        */
/* The above copyright notice and this permission notice shall be         */
/* included in all copies or substantial portions of the Software.        */
/*                                                                        */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,        */
/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF     */
/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. */
/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY   */
/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,   */
/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      */
/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
/**************************************************************************/

#pragma once

namespace PhysicsServer3DEnums {

/* SHAPE API */

enum ShapeType {
	SHAPE_WORLD_BOUNDARY, ///< plane:"plane"
	SHAPE_SEPARATION_RAY, ///< float:"length"
	SHAPE_SPHERE, ///< float:"radius"
	SHAPE_BOX, ///< vec3:"extents"
	SHAPE_CAPSULE, ///< dict( float:"radius", float:"height"):capsule
	SHAPE_CYLINDER, ///< dict( float:"radius", float:"height"):cylinder
	SHAPE_CONVEX_POLYGON, ///< array of planes:"planes"
	SHAPE_CONCAVE_POLYGON, ///< vector3 array:"triangles" , or Dictionary with "indices" (int array) and "triangles" (Vector3 array)
	SHAPE_HEIGHTMAP, ///< dict( int:"width", int:"depth",float:"cell_size", float_array:"heights"
	SHAPE_SOFT_BODY, ///< Used internally, can't be created from the physics server.
	SHAPE_CUSTOM, ///< Server-Implementation based custom shape, calling shape_create() with this value will result in an error
};

/* SPACE API */

enum SpaceParameter {
	SPACE_PARAM_CONTACT_RECYCLE_RADIUS,
	SPACE_PARAM_CONTACT_MAX_SEPARATION,
	SPACE_PARAM_CONTACT_MAX_ALLOWED_PENETRATION,
	SPACE_PARAM_CONTACT_DEFAULT_BIAS,
	SPACE_PARAM_BODY_LINEAR_VELOCITY_SLEEP_THRESHOLD,
	SPACE_PARAM_BODY_ANGULAR_VELOCITY_SLEEP_THRESHOLD,
	SPACE_PARAM_BODY_TIME_TO_SLEEP,
	SPACE_PARAM_SOLVER_ITERATIONS,
};

/* AREA API */

enum AreaParameter {
	AREA_PARAM_GRAVITY_OVERRIDE_MODE,
	AREA_PARAM_GRAVITY,
	AREA_PARAM_GRAVITY_VECTOR,
	AREA_PARAM_GRAVITY_IS_POINT,
	AREA_PARAM_GRAVITY_POINT_UNIT_DISTANCE,
	AREA_PARAM_LINEAR_DAMP_OVERRIDE_MODE,
	AREA_PARAM_LINEAR_DAMP,
	AREA_PARAM_ANGULAR_DAMP_OVERRIDE_MODE,
	AREA_PARAM_ANGULAR_DAMP,
	AREA_PARAM_PRIORITY,
	AREA_PARAM_WIND_FORCE_MAGNITUDE,
	AREA_PARAM_WIND_SOURCE,
	AREA_PARAM_WIND_DIRECTION,
	AREA_PARAM_WIND_ATTENUATION_FACTOR,
};

enum AreaSpaceOverrideMode {
	AREA_SPACE_OVERRIDE_DISABLED,
	AREA_SPACE_OVERRIDE_COMBINE,
	AREA_SPACE_OVERRIDE_COMBINE_REPLACE,
	AREA_SPACE_OVERRIDE_REPLACE,
	AREA_SPACE_OVERRIDE_REPLACE_COMBINE
};

/* BODY API */

enum BodyMode {
	BODY_MODE_STATIC,
	BODY_MODE_KINEMATIC,
	BODY_MODE_RIGID,
	BODY_MODE_RIGID_LINEAR,
};

enum BodyDampMode {
	BODY_DAMP_MODE_COMBINE,
	BODY_DAMP_MODE_REPLACE,
};

enum BodyParameter {
	BODY_PARAM_BOUNCE,
	BODY_PARAM_FRICTION,
	BODY_PARAM_MASS, ///< unused for static, always infinite
	BODY_PARAM_INERTIA,
	BODY_PARAM_CENTER_OF_MASS,
	BODY_PARAM_GRAVITY_SCALE,
	BODY_PARAM_LINEAR_DAMP_MODE,
	BODY_PARAM_ANGULAR_DAMP_MODE,
	BODY_PARAM_LINEAR_DAMP,
	BODY_PARAM_ANGULAR_DAMP,
	BODY_PARAM_MAX,
};

enum BodyState {
	BODY_STATE_TRANSFORM,
	BODY_STATE_LINEAR_VELOCITY,
	BODY_STATE_ANGULAR_VELOCITY,
	BODY_STATE_SLEEPING,
	BODY_STATE_CAN_SLEEP
};

enum BodyAxis {
	BODY_AXIS_LINEAR_X = 1 << 0,
	BODY_AXIS_LINEAR_Y = 1 << 1,
	BODY_AXIS_LINEAR_Z = 1 << 2,
	BODY_AXIS_ANGULAR_X = 1 << 3,
	BODY_AXIS_ANGULAR_Y = 1 << 4,
	BODY_AXIS_ANGULAR_Z = 1 << 5
};

/* JOINT API */

enum JointType {
	JOINT_TYPE_PIN,
	JOINT_TYPE_HINGE,
	JOINT_TYPE_SLIDER,
	JOINT_TYPE_CONE_TWIST,
	JOINT_TYPE_6DOF,
	JOINT_TYPE_MAX,

};

enum PinJointParam {
	PIN_JOINT_BIAS,
	PIN_JOINT_DAMPING,
	PIN_JOINT_IMPULSE_CLAMP
};

enum HingeJointParam {
	HINGE_JOINT_BIAS,
	HINGE_JOINT_LIMIT_UPPER,
	HINGE_JOINT_LIMIT_LOWER,
	HINGE_JOINT_LIMIT_BIAS,
	HINGE_JOINT_LIMIT_SOFTNESS,
	HINGE_JOINT_LIMIT_RELAXATION,
	HINGE_JOINT_MOTOR_TARGET_VELOCITY,
	HINGE_JOINT_MOTOR_MAX_IMPULSE,
	HINGE_JOINT_MAX
};

enum HingeJointFlag {
	HINGE_JOINT_FLAG_USE_LIMIT,
	HINGE_JOINT_FLAG_ENABLE_MOTOR,
	HINGE_JOINT_FLAG_MAX
};

enum SliderJointParam {
	SLIDER_JOINT_LINEAR_LIMIT_UPPER,
	SLIDER_JOINT_LINEAR_LIMIT_LOWER,
	SLIDER_JOINT_LINEAR_LIMIT_SOFTNESS,
	SLIDER_JOINT_LINEAR_LIMIT_RESTITUTION,
	SLIDER_JOINT_LINEAR_LIMIT_DAMPING,
	SLIDER_JOINT_LINEAR_MOTION_SOFTNESS,
	SLIDER_JOINT_LINEAR_MOTION_RESTITUTION,
	SLIDER_JOINT_LINEAR_MOTION_DAMPING,
	SLIDER_JOINT_LINEAR_ORTHOGONAL_SOFTNESS,
	SLIDER_JOINT_LINEAR_ORTHOGONAL_RESTITUTION,
	SLIDER_JOINT_LINEAR_ORTHOGONAL_DAMPING,

	SLIDER_JOINT_ANGULAR_LIMIT_UPPER,
	SLIDER_JOINT_ANGULAR_LIMIT_LOWER,
	SLIDER_JOINT_ANGULAR_LIMIT_SOFTNESS,
	SLIDER_JOINT_ANGULAR_LIMIT_RESTITUTION,
	SLIDER_JOINT_ANGULAR_LIMIT_DAMPING,
	SLIDER_JOINT_ANGULAR_MOTION_SOFTNESS,
	SLIDER_JOINT_ANGULAR_MOTION_RESTITUTION,
	SLIDER_JOINT_ANGULAR_MOTION_DAMPING,
	SLIDER_JOINT_ANGULAR_ORTHOGONAL_SOFTNESS,
	SLIDER_JOINT_ANGULAR_ORTHOGONAL_RESTITUTION,
	SLIDER_JOINT_ANGULAR_ORTHOGONAL_DAMPING,
	SLIDER_JOINT_MAX
};

enum ConeTwistJointParam {
	CONE_TWIST_JOINT_SWING_SPAN,
	CONE_TWIST_JOINT_TWIST_SPAN,
	CONE_TWIST_JOINT_BIAS,
	CONE_TWIST_JOINT_SOFTNESS,
	CONE_TWIST_JOINT_RELAXATION,
	CONE_TWIST_MAX
};

enum G6DOFJointAxisParam {
	G6DOF_JOINT_LINEAR_LOWER_LIMIT,
	G6DOF_JOINT_LINEAR_UPPER_LIMIT,
	G6DOF_JOINT_LINEAR_LIMIT_SOFTNESS,
	G6DOF_JOINT_LINEAR_RESTITUTION,
	G6DOF_JOINT_LINEAR_DAMPING,
	G6DOF_JOINT_LINEAR_MOTOR_TARGET_VELOCITY,
	G6DOF_JOINT_LINEAR_MOTOR_FORCE_LIMIT,
	G6DOF_JOINT_LINEAR_SPRING_STIFFNESS,
	G6DOF_JOINT_LINEAR_SPRING_DAMPING,
	G6DOF_JOINT_LINEAR_SPRING_EQUILIBRIUM_POINT,
	G6DOF_JOINT_ANGULAR_LOWER_LIMIT,
	G6DOF_JOINT_ANGULAR_UPPER_LIMIT,
	G6DOF_JOINT_ANGULAR_LIMIT_SOFTNESS,
	G6DOF_JOINT_ANGULAR_DAMPING,
	G6DOF_JOINT_ANGULAR_RESTITUTION,
	G6DOF_JOINT_ANGULAR_FORCE_LIMIT,
	G6DOF_JOINT_ANGULAR_ERP,
	G6DOF_JOINT_ANGULAR_MOTOR_TARGET_VELOCITY,
	G6DOF_JOINT_ANGULAR_MOTOR_FORCE_LIMIT,
	G6DOF_JOINT_ANGULAR_SPRING_STIFFNESS,
	G6DOF_JOINT_ANGULAR_SPRING_DAMPING,
	G6DOF_JOINT_ANGULAR_SPRING_EQUILIBRIUM_POINT,
	G6DOF_JOINT_LINEAR_DRIVE_FORCE_LIMIT,
	G6DOF_JOINT_ANGULAR_DRIVE_TORQUE_LIMIT,
	G6DOF_JOINT_MAX
};

enum G6DOFJointAxisFlag {
	G6DOF_JOINT_FLAG_ENABLE_LINEAR_LIMIT,
	G6DOF_JOINT_FLAG_ENABLE_ANGULAR_LIMIT,
	G6DOF_JOINT_FLAG_ENABLE_ANGULAR_SPRING,
	G6DOF_JOINT_FLAG_ENABLE_LINEAR_SPRING,
	G6DOF_JOINT_FLAG_ENABLE_ANGULAR_MOTOR,
#ifndef DISABLE_DEPRECATED
	G6DOF_JOINT_FLAG_ENABLE_MOTOR = G6DOF_JOINT_FLAG_ENABLE_ANGULAR_MOTOR,
#endif // DISABLE_DEPRECATED
	G6DOF_JOINT_FLAG_ENABLE_LINEAR_MOTOR,
	G6DOF_JOINT_FLAG_MAX
};

/* QUERY API */

enum AreaBodyStatus {
	AREA_BODY_ADDED,
	AREA_BODY_REMOVED
};

enum ProcessInfo {
	INFO_ACTIVE_OBJECTS,
	INFO_COLLISION_PAIRS,
	INFO_ISLAND_COUNT
};

#ifndef DISABLE_DEPRECATED
// Graveyard.
#endif

} // namespace PhysicsServer3DEnums

// Alias to make it easier to use.
#define PS3DE PhysicsServer3DEnums
