/**************************************************************************/
/*  accessibility_server_enums.h                                          */
/**************************************************************************/
/*                         This file is part of:                          */
/*                             GODOT ENGINE                               */
/*                        https://godotengine.org                         */
/**************************************************************************/
/* Copyright (c) 2014-present Godot Engine contributors (see AUTHORS.md). */
/* Copyright (c) 2007-2014 Juan Linietsky, Ariel Manzur.                  */
/*                                                                        */
/* Permission is hereby granted, free of charge, to any person obtaining  */
/* a copy of this software and associated documentation files (the        */
/* "Software"), to deal in the Software without restriction, including    */
/* without limitation the rights to use, copy, modify, merge, publish,    */
/* distribute, sublicense, and/or sell copies of the Software, and to     */
/* permit persons to whom the Software is furnished to do so, subject to  */
/* the following conditions:                                              */
/*                                                                        */
/* The above copyright notice and this permission notice shall be         */
/* included in all copies or substantial portions of the Software.        */
/*                                                                        */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,        */
/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF     */
/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. */
/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY   */
/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,   */
/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      */
/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
/**************************************************************************/

#pragma once

namespace AccessibilityServerEnums {

enum AccessibilityMode {
	ACCESSIBILITY_AUTO,
	ACCESSIBILITY_ALWAYS,
	ACCESSIBILITY_DISABLED,
};

enum AccessibilityRole {
	ROLE_UNKNOWN,
	ROLE_DEFAULT_BUTTON,
	ROLE_AUDIO,
	ROLE_VIDEO,
	ROLE_STATIC_TEXT,
	ROLE_CONTAINER,
	ROLE_PANEL,
	ROLE_BUTTON,
	ROLE_LINK,
	ROLE_CHECK_BOX,
	ROLE_RADIO_BUTTON,
	ROLE_CHECK_BUTTON,
	ROLE_SCROLL_BAR,
	ROLE_SCROLL_VIEW,
	ROLE_SPLITTER,
	ROLE_SLIDER,
	ROLE_SPIN_BUTTON,
	ROLE_PROGRESS_INDICATOR,
	ROLE_TEXT_FIELD,
	ROLE_MULTILINE_TEXT_FIELD,
	ROLE_COLOR_PICKER,
	ROLE_TABLE,
	ROLE_CELL,
	ROLE_ROW,
	ROLE_ROW_GROUP,
	ROLE_GROUP,
	ROLE_ROW_HEADER,
	ROLE_COLUMN_HEADER,
	ROLE_TREE,
	ROLE_TREE_ITEM,
	ROLE_LIST,
	ROLE_LIST_ITEM,
	ROLE_LIST_BOX,
	ROLE_LIST_BOX_OPTION,
	ROLE_TAB_BAR,
	ROLE_TAB,
	ROLE_TAB_PANEL,
	ROLE_MENU_BAR,
	ROLE_MENU,
	ROLE_MENU_ITEM,
	ROLE_MENU_ITEM_CHECK_BOX,
	ROLE_MENU_ITEM_RADIO,
	ROLE_IMAGE,
	ROLE_WINDOW,
	ROLE_TITLE_BAR,
	ROLE_DIALOG,
	ROLE_TOOLTIP,
	ROLE_REGION,
	ROLE_TEXT_RUN,
	ROLE_COMBO_BOX,
	ROLE_EDITABLE_COMBO_BOX,
	ROLE_MENU_LIST_OPTION,
	ROLE_MENU_LIST_POPUP,
	ROLE_SEARCH_INPUT,
	ROLE_DATE_INPUT,
	ROLE_DATE_TIME_INPUT,
	ROLE_WEEK_INPUT,
	ROLE_MONTH_INPUT,
	ROLE_TIME_INPUT,
	ROLE_EMAIL_INPUT,
	ROLE_NUMBER_INPUT,
	ROLE_PASSWORD_INPUT,
	ROLE_PHONE_NUMBER_INPUT,
	ROLE_URL_INPUT,
	ROLE_SWITCH,
	ROLE_PARAGRAPH,
	ROLE_LABEL,
	ROLE_ABBR,
	ROLE_ALERT,
	ROLE_ALERT_DIALOG,
	ROLE_APPLICATION,
	ROLE_ARTICLE,
	ROLE_BANNER,
	ROLE_BLOCKQUOTE,
	ROLE_CANVAS,
	ROLE_CAPTION,
	ROLE_CARET,
	ROLE_CODE,
	ROLE_COMPLEMENTARY,
	ROLE_COMMENT,
	ROLE_CONTENT_DELETION,
	ROLE_CONTENT_INSERTION,
	ROLE_CONTENT_INFO,
	ROLE_DEFINITION,
	ROLE_DESCRIPTION_LIST,
	ROLE_DETAILS,
	ROLE_DISCLOSURE_TRIANGLE,
	ROLE_DOCUMENT,
	ROLE_EMBEDDED_OBJECT,
	ROLE_EMPHASIS,
	ROLE_FEED,
	ROLE_FIGURE,
	ROLE_FIGURE_CAPTION,
	ROLE_FOOTER,
	ROLE_FORM,
	ROLE_GRID,
	ROLE_GRID_CELL,
	ROLE_HEADER,
	ROLE_HEADING,
	ROLE_IFRAME,
	ROLE_IFRAME_PRESENTATIONAL,
	ROLE_IME_CANDIDATE,
	ROLE_KEYBOARD,
	ROLE_LEGEND,
	ROLE_LINE_BREAK,
	ROLE_LIST_MARKER,
	ROLE_LOG,
	ROLE_MAIN,
	ROLE_MARK,
	ROLE_MARQUEE,
	ROLE_MATH,
	ROLE_METER,
	ROLE_NAVIGATION,
	ROLE_NOTE,
	ROLE_PLUGIN_OBJECT,
	ROLE_RADIO_GROUP,
	ROLE_ROOT_WEB_AREA,
	ROLE_RUBY,
	ROLE_RUBY_ANNOTATION,
	ROLE_SEARCH,
	ROLE_SECTION,
	ROLE_SECTION_HEADER,
	ROLE_SECTION_FOOTER,
	ROLE_STATUS,
	ROLE_STRONG,
	ROLE_SUGGESTION,
	ROLE_SVG_ROOT,
	ROLE_TERM,
	ROLE_TIMER,
	ROLE_TOOLBAR,
	ROLE_TREE_GRID,
	ROLE_WEB_VIEW,
	ROLE_LIST_GRID,
	ROLE_TERMINAL,
	ROLE_GRAPHICS_DOCUMENT,
	ROLE_GRAPHICS_OBJECT,
	ROLE_GRAPHICS_SYMBOL,
	ROLE_PDF_ROOT,
	ROLE_PDF_ACTIONABLE_HIGHLIGHT,
	ROLE_DOC_ABSTRACT,
	ROLE_DOC_ACKNOWLEDGEMENTS,
	ROLE_DOC_AFTERWORD,
	ROLE_DOC_APPENDIX,
	ROLE_DOC_BACK_LINK,
	ROLE_DOC_BIBLIO_ENTRY,
	ROLE_DOC_BIBLIOGRAPHY,
	ROLE_DOC_BIBLIO_REF,
	ROLE_DOC_CHAPTER,
	ROLE_DOC_COLOPHON,
	ROLE_DOC_CONCLUSION,
	ROLE_DOC_COVER,
	ROLE_DOC_CREDIT,
	ROLE_DOC_CREDITS,
	ROLE_DOC_DEDICATION,
	ROLE_DOC_ENDNOTE,
	ROLE_DOC_ENDNOTES,
	ROLE_DOC_EPIGRAPH,
	ROLE_DOC_EPILOGUE,
	ROLE_DOC_ERRATA,
	ROLE_DOC_EXAMPLE,
	ROLE_DOC_FOOTNOTE,
	ROLE_DOC_FOREWORD,
	ROLE_DOC_GLOSSARY,
	ROLE_DOC_GLOSS_REF,
	ROLE_DOC_INDEX,
	ROLE_DOC_INTRODUCTION,
	ROLE_DOC_NOTE_REF,
	ROLE_DOC_NOTICE,
	ROLE_DOC_PAGE_BREAK,
	ROLE_DOC_PAGE_FOOTER,
	ROLE_DOC_PAGE_HEADER,
	ROLE_DOC_PAGE_LIST,
	ROLE_DOC_PART,
	ROLE_DOC_PREFACE,
	ROLE_DOC_PROLOGUE,
	ROLE_DOC_PULLQUOTE,
	ROLE_DOC_QNA,
	ROLE_DOC_SUBTITLE,
	ROLE_DOC_TIP,
	ROLE_DOC_TOC,
};

enum AccessibilityPopupType {
	POPUP_MENU,
	POPUP_LIST,
	POPUP_TREE,
	POPUP_DIALOG,
};

enum AccessibilityFlags {
	FLAG_HIDDEN,
	FLAG_MULTISELECTABLE,
	FLAG_REQUIRED,
	FLAG_VISITED,
	FLAG_BUSY,
	FLAG_MODAL,
	FLAG_TOUCH_PASSTHROUGH,
	FLAG_READONLY,
	FLAG_DISABLED,
	FLAG_CLIPS_CHILDREN,
};

enum AccessibilityAction {
	ACTION_CLICK,
	ACTION_FOCUS,
	ACTION_BLUR,
	ACTION_COLLAPSE,
	ACTION_EXPAND,
	ACTION_DECREMENT,
	ACTION_INCREMENT,
	ACTION_HIDE_TOOLTIP,
	ACTION_SHOW_TOOLTIP,
	ACTION_SET_TEXT_SELECTION,
	ACTION_REPLACE_SELECTED_TEXT,
	ACTION_SCROLL_BACKWARD,
	ACTION_SCROLL_DOWN,
	ACTION_SCROLL_FORWARD,
	ACTION_SCROLL_LEFT,
	ACTION_SCROLL_RIGHT,
	ACTION_SCROLL_UP,
	ACTION_SCROLL_INTO_VIEW,
	ACTION_SCROLL_TO_POINT,
	ACTION_SET_SCROLL_OFFSET,
	ACTION_SET_VALUE,
	ACTION_SHOW_CONTEXT_MENU,
	ACTION_CUSTOM,
};

enum AccessibilityLiveMode {
	LIVE_OFF,
	LIVE_POLITE,
	LIVE_ASSERTIVE,
};

enum AccessibilityScrollUnit {
	SCROLL_UNIT_ITEM,
	SCROLL_UNIT_PAGE,
};

enum AccessibilityScrollHint {
	SCROLL_HINT_TOP_LEFT,
	SCROLL_HINT_BOTTOM_RIGHT,
	SCROLL_HINT_TOP_EDGE,
	SCROLL_HINT_BOTTOM_EDGE,
	SCROLL_HINT_LEFT_EDGE,
	SCROLL_HINT_RIGHT_EDGE,
};

}; // namespace AccessibilityServerEnums
