#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.add_source_files(env["SCENE_SOURCES"], "tile_set.cpp")

if not env["disable_physics_2d"]:
    env.add_source_files(env["SCENE_SOURCES"], "capsule_shape_2d.cpp")
    env.add_source_files(env["SCENE_SOURCES"], "circle_shape_2d.cpp")
    env.add_source_files(env["SCENE_SOURCES"], "concave_polygon_shape_2d.cpp")
    env.add_source_files(env["SCENE_SOURCES"], "convex_polygon_shape_2d.cpp")
    env.add_source_files(env["SCENE_SOURCES"], "rectangle_shape_2d.cpp")
    env.add_source_files(env["SCENE_SOURCES"], "segment_shape_2d.cpp")
    env.add_source_files(env["SCENE_SOURCES"], "separation_ray_shape_2d.cpp")
    env.add_source_files(env["SCENE_SOURCES"], "shape_2d.cpp")
    env.add_source_files(env["SCENE_SOURCES"], "world_boundary_shape_2d.cpp")
if not env["disable_navigation_2d"]:
    env.add_source_files(env["SCENE_SOURCES"], "navigation_mesh_source_geometry_data_2d.cpp")
    env.add_source_files(env["SCENE_SOURCES"], "navigation_polygon.cpp")
    env.add_source_files(env["SCENE_SOURCES"], "polygon_path_finder.cpp")

SConscript("skeleton/SCsub")
