#!/usr/bin/env python

import sys

Import('env')

common_server = [\
    "os_server.cpp",\
]

if sys.platform == "darwin":
	common_server.append("#platform/osx/crash_handler_osx.mm")
	common_server.append("#platform/osx/power_osx.cpp")
	common_server.append("#platform/osx/semaphore_osx.cpp")
else:
	common_server.append("#platform/linuxbsd/crash_handler_linuxbsd.cpp")
	common_server.append("#platform/linuxbsd/power_linuxbsd.cpp")

prog = env.add_program('#bin/godot_server', ['godot_server.cpp'] + common_server)
