#!/usr/bin/env python

Import('env')

common_server = [\
    "os_server.cpp",\
    "#platform/freedesktop/crash_handler_x11.cpp",
    "#platform/freedesktop/power_x11.cpp",
]
prog = env.add_program('#bin/godot_server', ['godot_server.cpp'] + common_server)
