#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

if not env["disable_navigation_3d"]:
    env.add_source_files(env["SERVERS_SOURCES"], "*.cpp")
else:
    if env["DEBUG_FEATURES"]:
        env.add_source_files(env["SERVERS_SOURCES"], "navigation_server_3d.cpp")
