#!/usr/bin/env python

Import('env')

iphone_lib = [

    'os_iphone.cpp',
    #'rasterizer_iphone.cpp',
    'audio_driver_iphone.cpp',
    'sem_iphone.cpp',
    'gl_view.mm',
    'main.m',
    'app_delegate.mm',
    'view_controller.mm',
    'game_center.mm',
    'in_app_store.mm',
    'icloud.mm',
    'ios.mm',
]

# env.Depends('#core/math/vector3.h', 'vector3_psp.h')

#iphone_lib = env.Library('iphone', iphone_lib)

env_ios = env.Clone()


if env['ios_gles22_override'] == "yes":
    env_ios.Append(CPPFLAGS=['-DGLES2_OVERRIDE'])


obj = env_ios.Object('godot_iphone.cpp')

prog = None
prog = env_ios.Program('#bin/godot', [obj] + iphone_lib)
action = "$IPHONEPATH/usr/bin/dsymutil " + File(prog)[0].path + " -o " + File(prog)[0].path + ".dSYM"
env.AddPostAction(prog, action)
