// bootstrapped.cpp
// Hand-written exports for engine-level singletons that are not present in
// extension_api.json and therefore cannot be generated by cpp_generators.py.
//
// These two functions are the bootstrap entry points for the entire bridge:
// Engine_get_SceneTree_singleton() is called first to anchor the scene graph,
// and Engine_get_object_singleton() resolves every other named singleton
// (CrossRuntimeEventSignal, ClassDB, etc.) by name thereafter.
//
// Both return a raw uintptr_t (Object* cast to integer) rather than Variant*
// because they are called before any Variant infrastructure is needed and
// their signatures are hardcoded in HARDCODED_FIRST in js_generator.py.
#include "../header/need.h"
#include "scene/main/scene_tree.h"
#include "core/config/engine.h"

extern "C" {

EMSCRIPTEN_KEEPALIVE
uintptr_t Engine_get_object_singleton(const char* name_utf8) {
    Engine *engine = Engine::get_singleton();
    if (!engine) return 0;
    Object *singleton = engine->get_singleton_object(StringName(String::utf8(name_utf8)));
    return singleton ? (uintptr_t)singleton : 0;
}

EMSCRIPTEN_KEEPALIVE
uintptr_t Engine_get_SceneTree_singleton() {
    SceneTree *tree = SceneTree::get_singleton();
    return tree ? (uintptr_t)tree : 0;
}

} // extern "C"
