/**************************************************************************/
/*  BootStrapped.cpp                                                      */
/**************************************************************************/
/*                         This file is part of:                          */
/*                             GODOT ENGINE                               */
/*                        https://godotengine.org                         */
/**************************************************************************/
/* Copyright (c) 2014-present Godot Engine contributors (see AUTHORS.md). */
/* Copyright (c) 2007-2014 Juan Linietsky, Ariel Manzur.                  */
/*                                                                        */
/* Permission is hereby granted, free of charge, to any person obtaining  */
/* a copy of this software and associated documentation files (the        */
/* "Software"), to deal in the Software without restriction, including    */
/* without limitation the rights to use, copy, modify, merge, publish,    */
/* distribute, sublicense, and/or sell copies of the Software, and to     */
/* permit persons to whom the Software is furnished to do so, subject to  */
/* the following conditions:                                              */
/*                                                                        */
/* The above copyright notice and this permission notice shall be         */
/* included in all copies or substantial portions of the Software.        */
/*                                                                        */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,        */
/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF     */
/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. */
/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY   */
/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,   */
/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      */
/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
/**************************************************************************/

// bootstrapped.cpp
// Hand-written exports for engine-level singletons that are not present in
// extension_api.json and therefore cannot be generated by cpp_generators.py.
//
// These two functions are the bootstrap entry points for the entire bridge:
// Engine_get_SceneTree_singleton() is called first to anchor the scene graph,
// and Engine_get_object_singleton() resolves every other named singleton
// (CrossRuntimeEventSignal, ClassDB, etc.) by name thereafter.
//
// Both return a raw uintptr_t (Object* cast to integer) rather than Variant*
// because they are called before any Variant infrastructure is needed and
// their signatures are hardcoded in HARDCODED_FIRST in js_generator.py.
#include "../header/need.h"

#include "core/config/engine.h"
#include "scene/main/scene_tree.h"

extern "C" {

EMSCRIPTEN_KEEPALIVE
uintptr_t Engine_get_object_singleton(const char *name_utf8) {
	Engine *engine = Engine::get_singleton();
	if (!engine) {
		return 0;
	}
	Object *singleton = engine->get_singleton_object(StringName(String::utf8(name_utf8)));
	return singleton ? (uintptr_t)singleton : 0;
}

EMSCRIPTEN_KEEPALIVE
uintptr_t Engine_get_SceneTree_singleton() {
	SceneTree *tree = SceneTree::get_singleton();
	return tree ? (uintptr_t)tree : 0;
}

} // extern "C"
