#!/usr/bin/python

Import('env')

env.tests_sources = []
env.add_source_files(env.tests_sources, "*.cpp")

Export('env')

# SConscript('math/SCsub');

lib = env.add_library("tests", env.tests_sources)
env.Prepend(LIBS=[lib])
