#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_materialx = env_modules.Clone()

if env.msvc:
    env_materialx.Append(CCFLAGS="/EHsc")
else:
    env_materialx.Append(CCFLAGS="-fexceptions")

env_materialx.Prepend(
    CPPPATH=["#modules/mtlx", "/nix/store/7bwfgs2nh289ynlljfm3dl0ybb1byp7k-python3.12-materialx-1.38.10/include"]
)
env.Append(LIBPATH=["/nix/store/7bwfgs2nh289ynlljfm3dl0ybb1byp7k-python3.12-materialx-1.38.10/lib"])
env.Append(
    LIBS=[
        "MaterialXCore",
        "MaterialXFormat",
        "MaterialXGenGlsl",
        "MaterialXGenMdl",
        "MaterialXGenMsl",
        "MaterialXGenOsl",
        "MaterialXGenShader",
        "MaterialXRender",
        "MaterialXRenderGlsl",
        "MaterialXRenderHw",
        "MaterialXRenderOsl",
    ]
)

if env["platform"] == "macos" or env["platform"] == "ios":
    env_materialx.Append(CPPDEFINES=["DMATERIALXVIEW_METAL_BACKEND=1"])
elif env["platform"] == "linux":
    env_materialx.Append(CPPDEFINES=["__linux__"])

env_materialx.Append(CPPDEFINES=["GL_SILENCE_DEPRECATION"])

module_objs = []

env_materialx.add_source_files(module_objs, "*.cpp")
env.modules_sources += module_objs
