#!/usr/bin/env python

from typing import TYPE_CHECKING

from SCons.Script.SConscript import SConsEnvironment

if TYPE_CHECKING:
    env = SConsEnvironment()
    env_openxr = SConsEnvironment()
    Import = SConsEnvironment.Import

Import("env")
Import("env_openxr")

module_obj = []

env_openxr.add_source_files(module_obj, "*.cpp")

env.modules_sources += module_obj
