#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_openxr")

module_obj = []

env_openxr.add_source_files(module_obj, "*.cpp")

env["MODULES_SOURCES"] += module_obj
