#!/usr/bin/env python

Import("env")
Import("env_modules")

env_fbx = env_modules.Clone()

# Make includes relative to the folder path specified here so our includes are clean
env_fbx.Prepend(CPPPATH=["#modules/fbx/"])

if env["builtin_zlib"]:
    env_fbx.Prepend(CPPPATH=["#thirdparty/zlib/"])

# Either add all the folders in one go if a SCU build...
if env_fbx.add_source_files_scu(env.modules_sources, "*.cpp") == False:
    # or if not a scu build, the above line only adds the main folder,
    # and the subfolders are added separately:
    env_fbx.add_source_files(env.modules_sources, "tools/*.cpp")
    env_fbx.add_source_files(env.modules_sources, "data/*.cpp")
    env_fbx.add_source_files(env.modules_sources, "fbx_parser/*.cpp")
