#!/usr/bin/env python

Import("env")
Import("env_modules")

env_fbx = env_modules.Clone()

# Make includes relative to the folder path specified here so our includes are clean
env_fbx.Prepend(CPPPATH=["#modules/fbx/"])

if env["builtin_zlib"]:
    env_fbx.Prepend(CPPPATH=["#thirdparty/zlib/"])

# Godot's own source files
env_fbx.add_source_files(env.modules_sources, "tools/*.cpp")
env_fbx.add_source_files(env.modules_sources, "data/*.cpp")
env_fbx.add_source_files(env.modules_sources, "fbx_parser/*.cpp")
env_fbx.add_source_files(env.modules_sources, "*.cpp")
