#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env", "py_builder_env")

py_builder_env.Command(
    "ext_wrappers.gen.h",
    "make_wrappers.py",
    Action(
        "$PYTHON_BIN $SOURCE --target $TARGET",
        "$GENCOMSTR",
    ),
)
py_builder_env.Command(
    "gdextension_interface_dump.gen.h",
    ["gdextension_interface.json", "make_interface_dumper.py"],
    Action(
        "$PYTHON_BIN ${SOURCES[1]} --target $TARGET --source ${SOURCES[0]}",
        "$GENCOMSTR",
    ),
)
py_builder_env.Command(
    "gdextension_interface.gen.h",
    ["gdextension_interface.json", "make_interface_header.py"],
    Action(
        "$PYTHON_BIN ${SOURCES[1]} --target $TARGET --source ${SOURCES[0]}",
        "$GENCOMSTR",
    ),
)

env.add_source_files(env.core_sources, "*.cpp")
