#!/usr/bin/env python

Import("env")

import make_wrappers
from platform_methods import run_in_subprocess

env.CommandNoCache(["ext_wrappers.gen.inc"], "make_wrappers.py", run_in_subprocess(make_wrappers.run))


env_extension = env.Clone()

env_extension.add_source_files(env.core_sources, "*.cpp")
