#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.servers_sources = []

env.add_source_files(env.servers_sources, "audio_server.cpp")
env.add_source_files(env.servers_sources, "camera_server.cpp")
env.add_source_files(env.servers_sources, "display_server.cpp")
env.add_source_files(env.servers_sources, "navigation_server_2d.cpp")
env.add_source_files(env.servers_sources, "navigation_server_3d.cpp")
env.add_source_files(env.servers_sources, "register_server_types.cpp")
env.add_source_files(env.servers_sources, "rendering_server.cpp")
env.add_source_files(env.servers_sources, "text_server.cpp")

SConscript("audio/SCsub")
SConscript("camera/SCsub")
SConscript("debugger/SCsub")
SConscript("display/SCsub")
SConscript("extensions/SCsub")
SConscript("movie_writer/SCsub")
SConscript("navigation/SCsub")
SConscript("rendering/SCsub")
SConscript("text/SCsub")

if not env["disable_physics_2d"]:
    env.add_source_files(env.servers_sources, "physics_server_2d.cpp")
    env.add_source_files(env.servers_sources, "physics_server_2d_wrap_mt.cpp")

if not env["disable_physics_3d"]:
    env.add_source_files(env.servers_sources, "physics_server_3d.cpp")
    env.add_source_files(env.servers_sources, "physics_server_3d_wrap_mt.cpp")

if not env["disable_xr"]:
    env.add_source_files(env.servers_sources, "xr_server.cpp")
    SConscript("xr/SCsub")

lib = env.add_library("servers", env.servers_sources)

env.Prepend(LIBS=[lib])
