#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.servers_sources = []

env.add_source_files(env.servers_sources, "register_server_types.cpp")

SConscript("audio/SCsub")
SConscript("camera/SCsub")
SConscript("debugger/SCsub")
SConscript("display/SCsub")
SConscript("movie_writer/SCsub")
SConscript("rendering/SCsub")
SConscript("text/SCsub")

if not env["disable_navigation_2d"]:
    SConscript("navigation_2d/SCsub")
if not env["disable_physics_2d"]:
    SConscript("physics_2d/SCsub")

if not env["disable_navigation_3d"]:
    SConscript("navigation_3d/SCsub")
if not env["disable_physics_3d"]:
    SConscript("physics_3d/SCsub")
if not env["disable_xr"]:
    SConscript("xr/SCsub")

lib = env.add_library("servers", env.servers_sources)

env.Prepend(LIBS=[lib])
