#!/usr/bin/env python

Import("env")

env.servers_sources = []
env.add_source_files(env.servers_sources, "*.cpp")

SConscript("xr/SCsub")
SConscript("camera/SCsub")
SConscript("physics_3d/SCsub")
SConscript("physics_2d/SCsub")
SConscript("rendering/SCsub")
SConscript("audio/SCsub")
SConscript("text/SCsub")
SConscript("debugger/SCsub")
SConscript("extensions/SCsub")
SConscript("movie_writer/SCsub")
SConscript("navigation/SCsub")

lib = env.add_library("servers", env.servers_sources)

env.Prepend(LIBS=[lib])
