#!/usr/bin/env python

Import("env")
Import("env_modules")

env_camera = env_modules.Clone()

if env["platform"] in ["windows", "macos", "linuxbsd"]:
    env_camera.add_source_files(env.modules_sources, "register_types.cpp")

if env["platform"] == "windows":
    env_camera.add_source_files(env.modules_sources, "camera_win.cpp")

elif env["platform"] == "macos":
    env_camera.add_source_files(env.modules_sources, "camera_macos.mm")

elif env["platform"] == "linuxbsd":
    env_camera.add_source_files(env.modules_sources, "camera_linux.cpp")
    env_camera.add_source_files(env.modules_sources, "camera_feed_linux.cpp")
    env_camera.add_source_files(env.modules_sources, "buffer_decoder.cpp")
