#!/usr/bin/env python

Import("env")

# Using importlib package and relative path to prevent conflicts with other external
# python packages named "editor" while trying to import template_builders.
import importlib.util

spec = importlib.util.spec_from_file_location("editor.template_builders", "../../../editor/template_builders.py")
build_template_cs = importlib.util.module_from_spec(spec)
spec.loader.exec_module(build_template_cs)

env["BUILDERS"]["MakeCSharpTemplateBuilder"] = Builder(
    action=env.Run(build_template_cs.make_templates, "Generating C# templates header."),
    suffix=".h",
    src_suffix=".cs",
)

# Template files
templates_sources = Glob("*/*.cs")

env.Alias("editor_template_cs", [env.MakeCSharpTemplateBuilder("templates.gen.h", templates_sources)])
