#!/usr/bin/env python

Import('env')
Import('env_modules')

env_arkit = env_modules.Clone()

# (iOS) Build as separate static library
modules_sources = []
modules_headers = []
env_arkit.add_source_files(modules_sources, "*.cpp")
env_arkit.add_source_files(modules_sources, "*.mm")
env_arkit.add_header_files(modules_headers, "*.h")
mod_lib = env_modules.add_library('#bin/libgodot_arkit_module' + env['LIBSUFFIX'], modules_sources)