#!/usr/bin/env python

Import('env')
Import('env_modules')

env_arkit = env_modules.Clone()

# Add source files
env_arkit.add_source_files(env.modules_sources, "*.cpp")
env_arkit.add_source_files(env.modules_sources, "*.mm")
