#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_minimp3 = env_modules.Clone()

thirdparty_dir = "#thirdparty/minimp3/"

env_minimp3.Prepend(CPPEXTPATH=[thirdparty_dir])

if not env["minimp3_extra_formats"]:
    env_minimp3.Append(CPPDEFINES=["MINIMP3_ONLY_MP3"])

# Godot source files
env_minimp3.add_source_files(env.modules_sources, "*.cpp")
