#!/usr/bin/env python

Import('env')
from compat import isbasestring

# Thirdparty source files
thirdparty_dir = "#thirdparty/nanoflann/"

env.Append(CPPPATH=[thirdparty_dir])


# Godot source files
env.add_source_files(env.modules_sources, "*.cpp")

Export('env')
