#!/usr/bin/env python

Import("env")
Import("env_gdnative")

env_net = env_gdnative.Clone()

has_webrtc = env_net["module_webrtc_enabled"]
if has_webrtc:
    env_net.Append(CPPDEFINES=["WEBRTC_GDNATIVE_ENABLED"])

env_net.add_source_files(env.modules_sources, "*.cpp")
