#!/usr/bin/env python

Import('env')

# Not cloning the env, the includes need to be accessible for core/

# Thirdparty source files
# No check here as already done in drivers/SCsub
thirdparty_dir = "#thirdparty/zlib/"
thirdparty_sources = [
	"adler32.c",
	"compress.c",
	"crc32.c",
	"deflate.c",
	"infback.c",
	"inffast.c",
	"inflate.c",
	"inftrees.c",
	"trees.c",
	"uncompr.c",
	"zutil.c",
]
thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

env.add_source_files(env.drivers_sources, thirdparty_sources)
env.Append(CPPPATH = [thirdparty_dir])
