/*************************************************************************/
/*  gl_error_handler.h                                                   */
/*************************************************************************/
/*                       This file is part of:                           */
/*                           GODOT ENGINE                                */
/*                    http://www.godotengine.org                         */
/*************************************************************************/
/* Copyright (c) 2007-2017 Juan Linietsky, Ariel Manzur.                 */
/* Copyright (c) 2014-2017 Godot Engine contributors (cf. AUTHORS.md)    */
/*                                                                       */
/* Permission is hereby granted, free of charge, to any person obtaining */
/* a copy of this software and associated documentation files (the       */
/* "Software"), to deal in the Software without restriction, including   */
/* without limitation the rights to use, copy, modify, merge, publish,   */
/* distribute, sublicense, and/or sell copies of the Software, and to    */
/* permit persons to whom the Software is furnished to do so, subject to */
/* the following conditions:                                             */
/*                                                                       */
/* The above copyright notice and this permission notice shall be        */
/* included in all copies or substantial portions of the Software.       */
/*                                                                       */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,       */
/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF    */
/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.*/
/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY  */
/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,  */
/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE     */
/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                */
/*************************************************************************/

#ifndef GL_ERROR_HANDLER_H
#define GL_ERROR_HANDLER_H

#include "core/error_macros.h"

extern "C" {
bool _err_print_gl_errors(const char *p_function, const char *p_file, int p_line, const char *p_command);
void _err_print_gl_fb_error(const char *p_function, const char *p_file, int p_line, GLenum p_status, const char *p_framebuffer_desc);
}

/** Capture errors generated by gl commands
 * clears error first, once an error is generated further errors are ignored
 */

#define GL_ERR_WITH_CLEAR(m_gl_command)                                                               \
  {                                                                                      \
    glGetError(); \
    m_gl_command;                                                                      \
    if (!_err_print_gl_errors(FUNCTION_STR, __FILE__, __LINE__, _STR(m_gl_command))) { \
      _err_error_exists = false;                                                     \
    };                                                                                 \
  }

/** Capture errors generated by gl commands
 * use this if error was checked in previous gl call
 */

#define GL_ERR(m_gl_command)                                                               \
	{                                                                                      \
		m_gl_command;                                                                      \
		if (!_err_print_gl_errors(FUNCTION_STR, __FILE__, __LINE__, _STR(m_gl_command))) { \
			_err_error_exists = false;                                                     \
		};                                                                                 \
	}

/** Check if our framebuffer had an issue
 */

#define GL_ERR_FRAMEBUFFER(m_status, m_framebuffer_desc)                                            \
	{                                                                                               \
		if (m_status != GL_FRAMEBUFFER_COMPLETE) {                                                  \
			_err_print_gl_fb_error(FUNCTION_STR, __FILE__, __LINE__, m_status, m_framebuffer_desc); \
		} else                                                                                      \
			_err_error_exists = false;                                                              \
	}

#endif
