#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.add_source_files(env.drivers_sources, "*.cpp")

env.add_subdirectory("shaders/SCsub")
env.add_subdirectory("storage/SCsub")
env.add_subdirectory("effects/SCsub")
env.add_subdirectory("environment/SCsub")
