#!/usr/bin/env python

from typing import TYPE_CHECKING

import default_theme_builders
from SCons.Script.SConscript import SConsEnvironment

if TYPE_CHECKING:
    env = SConsEnvironment()
    Import = SConsEnvironment.Import

Import("env")

env.add_source_files(env.scene_sources, "*.cpp")

env.SConscript("icons/SCsub")

env.Depends("#scene/theme/default_font.gen.h", "#thirdparty/fonts/OpenSans_SemiBold.woff2")
env.CommandNoCache(
    "#scene/theme/default_font.gen.h",
    "#thirdparty/fonts/OpenSans_SemiBold.woff2",
    env.Run(default_theme_builders.make_fonts_header),
)
