#!/usr/bin/env python

Import("env")

from platform_methods import run_in_subprocess
import default_theme_builders


env.add_source_files(env.scene_sources, "*.cpp")

SConscript("icons/SCsub")

env.Depends("#scene/theme/default_font.gen.h", "#thirdparty/fonts/OpenSans_SemiBold.woff2")
env.CommandNoCache(
    "#scene/theme/default_font.gen.h",
    "#thirdparty/fonts/OpenSans_SemiBold.woff2",
    run_in_subprocess(default_theme_builders.make_fonts_header),
)
