#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env", "py_builder_env")

env.add_source_files(env.servers_sources, "*.cpp")

py_builder_env.CommandNoCache(
    "ltc_lut.gen.h",
    ["make_ltc_lut.py", "#servers/rendering/storage/ltc/ltc_lut1.dds", "#servers/rendering/storage/ltc/ltc_lut2.dds"],
    Action(
        "$PYTHON_BIN servers/rendering/storage/make_ltc_lut.py --target $TARGET --source $SOURCES",
        "$GENCOMSTR",
    ),
)
