#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

import make_tony_mc_mapface_lut

env.add_source_files(env.servers_sources, "*.cpp")

env.CommandNoCache(
    "tony_mc_mapface_lut.gen.h",
    ["make_tony_mc_mapface_lut.py", "#thirdparty/tony-mc-mapface/tony_mc_mapface.dds"],
    env.Run(make_tony_mc_mapface_lut.run),
)
