#!/usr/bin/env python

Import("env")
Import("env_modules")

env_sqlite = env_modules.Clone()

if env["builtin_sqlite"]:
    env_sqlite.Prepend(CPPPATH=["#thirdparty_dir"])

    thirdparty_dir = "#thirdparty/sqlite/"
    thirdparty_sources = ["spmemvfs.c", "sqlite3.c"]
    thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]
    env_thirdparty = env_sqlite.Clone()
    env_thirdparty.disable_warnings()
    env_thirdparty.add_source_files(env.modules_sources, thirdparty_sources)

# Godot source files
env_sqlite.add_source_files(env.modules_sources, "*.cpp")
