#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_gltf = env_modules.Clone()

# Godot source files

env_gltf.add_source_files(env["MODULES_SOURCES"], "*.cpp")
if not env["disable_physics_3d"]:
    env_gltf.add_source_files(env["MODULES_SOURCES"], "physics/*.cpp")
