#!/usr/bin/env python
#
# Huge credit to https://github.com/goostengine/goost
# this script was made by them and only modified to my needs
#
import os
import sys
import pickle
import subprocess

from shutil import copytree, ignore_patterns

# godot v4.0.0-beta10
godot_ver = os.getenv("GODOT_VERSION", "4.1-stable")
godot_url = "https://github.com/godotengine/godot"
godot_dir = Dir("godot")

lua_dir = Dir("luaAPI")

# A method which allows us to run `git`, `scons`, and other commands.
def run(args, dir="."):
    if sys.platform.startswith("win32"):
        return subprocess.run(args, check=True, shell=True, cwd=dir).returncode
    else:
        return subprocess.run(args, check=True, cwd=dir).returncode

if not lua_dir.exists():
    print("Copying over source files.")
    copytree("../", lua_dir.abspath,
        ignore=ignore_patterns('.github*', 'scripts*', 'testing*'))

if not godot_dir.exists():
    # Checkout Godot repository directly under the current directory.
    print("Cloning godot.")
    run(["git", "clone", godot_url])
    run(["git", "checkout", godot_ver, "--quiet"], godot_dir.abspath)

# Setup base SCons arguments to the Godot build command.
args = ["scons"]
for arg in ARGLIST:
    if arg[0] == 'extra_suffix':
        os.environ["BUILD_NAME"] = arg[1]
    opt = "%s=%s" % (arg[0], arg[1])
    args.append(opt)

args.append("custom_modules=%s" % lua_dir.abspath)

# Avoid issues when building with different versions of Python.
SConsignFile(".sconsign{0}.dblite".format(pickle.HIGHEST_PROTOCOL))

# Enable cache if required, this is reused by Godot and CI.
scons_cache_path = os.environ.get("SCONS_CACHE")
if scons_cache_path != None:
    CacheDir(scons_cache_path)
    print("SCons cache enabled... (path: '" + scons_cache_path + "')")

# Some SCons-specific options may not trigger an actual build.
skip_build = False

# Pass commonly used SCons options to the Godot build.
scons_options = ["help", "clean"]
for opt in scons_options:
    if not GetOption(opt):
        continue
    skip_build |= opt in ["help", "clean"]
    args.append("--%s" % opt)

if GetOption("num_jobs") > 1:
    args.append("--jobs=%s" % GetOption("num_jobs"))

if not skip_build:
    print("Building Godot ...")

# Run SCons to build Godot, check the build configuration etc.

run(args, godot_dir.abspath)
