#!/usr/bin/env python

Import("env")
Import("env_modules")

env_game_help = env_modules.Clone()

# Module files
env_game_help.add_source_files(env.modules_sources, "*.cpp")
env_game_help.add_source_files(env.modules_sources, "Terrain3D/src/*.cpp")
env_game_help.add_source_files(env.modules_sources, "foliage_manager/*.cpp")
env_game_help.add_source_files(env.modules_sources, "game_gui/*.cpp")
env_game_help.add_source_files(env.modules_sources, "logic/*.cpp")
