#!/usr/bin/env python

Import("env")
Import("env_modules")

env_game_help = env_modules.Clone()

# Module files
env_game_help.add_source_files(env.modules_sources, "*.cpp")
env_game_help.add_source_files(env.modules_sources, "Terrain3D/src/*.cpp")
