#!/usr/bin/env python

Import("env")
Import("env_modules")

env_game_help = env_modules.Clone()
# Module files
env_game_help.add_source_files(env.modules_sources, "*.cpp")
env_game_help.add_source_files(env.modules_sources, "Terrain3D/src/*.cpp")
env_game_help.add_source_files(env.modules_sources, "foliage_manager/*.cpp")
env_game_help.add_source_files(env.modules_sources, "game_gui/*.cpp")
env_game_help.add_source_files(env.modules_sources, "logic/*.cpp")
env_game_help.add_source_files(env.modules_sources, "logic/animator/*.cpp")
env_game_help.add_source_files(env.modules_sources, "logic/character_ai/*.cpp")
env_game_help.add_source_files(env.modules_sources, "logic/character_shape/*.cpp")
env_game_help.add_source_files(env.modules_sources, "csv/*.cpp")
env_game_help.add_source_files(env.modules_sources, "unity/*.cpp")
env_game_help.add_source_files(env.modules_sources, "logic/navigation/*.cpp")
# mterrain
env_game_help.add_source_files(env.modules_sources, "MTerrain/gdextension/src/*.cpp")
env_game_help.add_source_files(env.modules_sources, "MTerrain/gdextension/src/height_brushes/*.cpp")
env_game_help.add_source_files(env.modules_sources, "MTerrain/gdextension/src/color_brushes/*.cpp")
env_game_help.add_source_files(env.modules_sources, "MTerrain/gdextension/src/grass/*.cpp")
env_game_help.add_source_files(env.modules_sources, "MTerrain/gdextension/src/navmesh/*.cpp")

env_game_help.add_source_files(env.modules_sources, "yaml/*.cpp")
env_game_help.add_source_files(env.modules_sources, "yaml/std/*.cpp")
env_game_help.add_source_files(env.modules_sources, "yaml/detail/*.cpp")


env_game_help.add_source_files(env.modules_sources, "yaml/c4/*.cpp")


if env.editor_build:
    env_game_help.add_source_files(env.modules_sources, "editor/*.cpp")
