/* THIS FILE IS GENERATED DO NOT EDIT */
#ifndef _EDITOR_AUTHORS_H
#define _EDITOR_AUTHORS_H
static const char *dev_names[] = {
	"Alexander Holland (AlexHolly)",
	"Alexey Velikiy (jonyrock)",
	"Andreas Haas (Hinsbart)",
	"Anton Yabchinskiy (a12n)",
	"Aren Villanueva (kurikaesu)",
	"Ariel Manzur (punto-)",
	"Bastiaan Olij (BastiaanOlij)",
	"Bojidar Marinov (bojidar-bg)",
	"Błażej Szczygieł (zaps166)",
	"Carl Olsson (not-surt)",
	"Dana Olson (adolson)",
	"Daniel J. Ramirez (djrm)",
	"Emmanuel Leblond (touilleMan)",
	"Fabio Alessandrelli (Faless)",
	"Ferenc Arn (tagcup)",
	"Franklin Sobrinho (TheHX)",
	"Geequlim",
	"Gen (dbsGen)",
	"George Marques (vnen)",
	"Guilherme Felipe (guilhermefelipecgs)",
	"Hein-Pieter van Braam (hpvb)",
	"Hubert Jarosz (Marqin)",
	"Ignacio Etcheverry (neikeq)",
	"J08nY",
	"Johan Manuel (29jm)",
	"Joshua Grams (JoshuaGrams)",
	"Juan Linietsky (reduz)",
	"Julian Murgia (StraToN)",
	"Kostadin Damyanov (Max-Might)",
	"L. Krause (eska014)",
	"Marc Gilleron (Zylann)",
	"Marcelo Fernandez (marcelofg55)",
	"Mariano Javier Suligoy (MarianoGnu)",
	"Mario Schlack (hurikhan)",
	"Masoud BH (masoudbh3)",
	"Nathan Warden (NathanWarden)",
	"Ovnuniarchos",
	"Patrick (firefly2442)",
	"Paul Batty (Paulb23)",
	"Pawel Kowal (pkowal1982)",
	"Pedro J. Estébanez (RandomShaper)",
	"Ralf Hölzemer (rollenrolm)",
	"Ramesh Ravone (RameshRavone)",
	"Ray Koopa (RayKoopa)",
	"Rémi Verschelde (akien-mga)",
	"SaracenOne",
	"Thomas Herzog (karroffel)",
	"V. Vamsi Krishna (vkbsb)",
	"Vinzenz Feenstra (vinzenz)",
	"Zher Huei Lee (leezh)",
	"ZuBsPaCe",
	"박한얼 (volzhs)",
	"est31",
	"marynate",
	"mrezai",
	"romulox-x",
	"sanikoyes",
	"yg2f (SuperUserNameMan)",
	0
};
#define AUTHORS_COUNT 58
#endif
