#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_interactive_music = env_modules.Clone()

# Godot's own source files
env_interactive_music.add_source_files(env.modules_sources, "*.cpp")
if env.editor_build:
    env_interactive_music.add_source_files(env.modules_sources, "editor/*.cpp")
