#!/usr/bin/env python

from typing import TYPE_CHECKING

from SCons.Script.SConscript import SConsEnvironment

if TYPE_CHECKING:
    env = SConsEnvironment()
    env_modules = SConsEnvironment()
    Import = SConsEnvironment.Import

Import("env")
Import("env_modules")

env_interactive_music = env_modules.Clone()

# Godot's own source files
env_interactive_music.add_source_files(env.modules_sources, "*.cpp")
if env.editor_build:
    env_interactive_music.add_source_files(env.modules_sources, "editor/*.cpp")
