#!/usr/bin/env python
from misc.utility.scons_hints import *

from glob import glob

import platform_builders

Import("env")

env["PLATFORM_SOURCES"] = []


# Generate export icons
for platform in env["PLATFORM_EXPORTERS"]:
    for path in glob(f"{platform}/export/*.svg"):
        env.CommandNoCache(path.replace(".svg", "_svg.gen.h"), path, env.Run(platform_builders.export_icon_builder))


# Register platform-exclusive APIs
register_platform_apis = env.CommandNoCache(
    "register_platform_apis.gen.cpp",
    env.Value(env["PLATFORM_APIS"]),
    env.Run(platform_builders.register_platform_apis_builder),
)
env.add_source_files(env["PLATFORM_SOURCES"], register_platform_apis)
for platform in env["PLATFORM_APIS"]:
    env.add_source_files(env["PLATFORM_SOURCES"], f"{platform}/api/*.cpp")

lib = env.add_library("platform", env["PLATFORM_SOURCES"])
env.Prepend(LIBS=[lib])
