#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

if "pipewire" in env and env["pipewire"]:
    if env["use_sowrap"]:
        env.Prepend(CPPPATH=["#thirdparty/linuxbsd_headers/pipewire"])
        env.add_source_files(env.drivers_sources, "pipewire-so_wrap.c")

env.add_source_files(env.drivers_sources, "*.cpp")
