#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env_object = env.Clone()

env_object.add_source_files(env.servers_sources, "physics_server_2d_extension.cpp")

if not env["disable_3d"]:
    env_object.add_source_files(env.servers_sources, "physics_server_3d_extension.cpp")
