#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env", "py_builder_env")

# Order matters here. Higher index controller database files write on top of lower index database files.
controller_databases = [
    "gamecontrollerdb.txt",
    "godotcontrollerdb.txt",
]

gensource = py_builder_env.Command(
    "default_controller_mappings.gen.cpp",
    controller_databases,
    Action(
        "$PYTHON_BIN core/input/input_builders.py --method make_default_controller_mappings --target $TARGET --source $SOURCES",
        "$GENCOMSTR",
    ),
)

env.add_source_files(env.core_sources, "*.cpp")
env.add_source_files(env.core_sources, gensource)
