#!/usr/bin/env python
from __future__ import annotations

from misc.utility.scons_hints import *

Import("env")

env.add_source_files(env.scene_sources, "*.cpp")

# Chain load SCsubs
SConscript("joints/SCsub")
