#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env_apple_embedded = env.Clone()

# Enable module support
# Need a functional export template here, so not using `try_use_cxx20_module`.
env_apple_embedded.Append(CCFLAGS=["-fmodules", "-fcxx-modules"])

# Use bundled Vulkan headers
vulkan_dir = "#thirdparty/vulkan"
env_apple_embedded.Prepend(CPPPATH=[vulkan_dir, vulkan_dir + "/include"])

# Driver source files
env_apple_embedded.add_source_files(env.drivers_sources, "*.mm")
