#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_zip = env_modules.Clone()

# Module files
env_zip.add_source_files(env["MODULES_SOURCES"], "*.cpp")

if env["tests"]:
    env_zip.add_source_files(env["MODULES_SOURCES"], "./tests/*.cpp")
