#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.add_source_files(env.servers_sources, "*.cpp")

env.add_subdirectory("dummy/SCsub")
env.add_subdirectory("renderer_rd/SCsub")
env.add_subdirectory("storage/SCsub")
