#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.add_source_files(env["SERVERS_SOURCES"], "*.cpp")

SConscript("dummy/SCsub")
SConscript("renderer_rd/SCsub")
SConscript("storage/SCsub")
