#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_gdscript_elf = env_modules.Clone()

# Add include paths
env_gdscript_elf.Prepend(CPPPATH=["#modules/gdscript_elf/src", "#thirdparty/elfio"])

# Source files - ELF64 generation using elfio
sources = [
    "register_types.cpp",
    "src/gdscript_elf64_writer.cpp",
    "src/gdscript_riscv_encoder.cpp",
    "src/gdscript_elf_fallback.cpp",
]

env_gdscript_elf.add_source_files(env.modules_sources, sources)
