// This file is generated. Do not edit!
// see https://github.com/hpvb/dynload-wrapper for details
// generated by /home/eirexe/repos/sdl_test/dynload-wrapper/generate-wrapper.py 0.5 on 2024-03-15 04:48:00
// flags: /home/eirexe/repos/sdl_test/dynload-wrapper/generate-wrapper.py --ignore-other --include ./thirdparty/sdl_headers/SDL.h --sys-include thirdparty/sdl_headers/SDL.h --include ./thirdparty/sdl_headers/SDL_main.h --sys-include thirdparty/sdl_headers/SDL_main.h --include ./thirdparty/sdl_headers/SDL_error.h --sys-include thirdparty/sdl_headers/SDL_error.h --include ./thirdparty/sdl_headers/SDL_hints.h --sys-include thirdparty/sdl_headers/SDL_hints.h --include ./thirdparty/sdl_headers/SDL_joystick.h --sys-include thirdparty/sdl_headers/SDL_joystick.h --include ./thirdparty/sdl_headers/SDL_events.h --sys-include thirdparty/sdl_headers/SDL_events.h --include ./thirdparty/sdl_headers/SDL_gamecontroller.h --sys-include thirdparty/sdl_headers/SDL_gamecontroller.h --include ./thirdparty/sdl_headers/SDL_rwops.h --sys-include thirdparty/sdl_headers/SDL_rwops.h --soname libSDL2-2.0.so --omit-prefix SDL_main --omit-prefix SDL_GameControllerGetSteamHandle --init-name SDL2 --output-header ./drivers/sdl/SDL2-so_wrap.h --output-implementation ./drivers/sdl/SDL2-so_wrap.c
//
#include <stdint.h>

#define SDL_SetMainReady SDL_SetMainReady_dylibloader_orig_SDL2
#define SDL_SetError SDL_SetError_dylibloader_orig_SDL2
#define SDL_GetError SDL_GetError_dylibloader_orig_SDL2
#define SDL_GetErrorMsg SDL_GetErrorMsg_dylibloader_orig_SDL2
#define SDL_ClearError SDL_ClearError_dylibloader_orig_SDL2
#define SDL_Error SDL_Error_dylibloader_orig_SDL2
#define SDL_RWFromFile SDL_RWFromFile_dylibloader_orig_SDL2
#define SDL_RWFromFP SDL_RWFromFP_dylibloader_orig_SDL2
#define SDL_RWFromMem SDL_RWFromMem_dylibloader_orig_SDL2
#define SDL_RWFromConstMem SDL_RWFromConstMem_dylibloader_orig_SDL2
#define SDL_AllocRW SDL_AllocRW_dylibloader_orig_SDL2
#define SDL_FreeRW SDL_FreeRW_dylibloader_orig_SDL2
#define SDL_RWsize SDL_RWsize_dylibloader_orig_SDL2
#define SDL_RWseek SDL_RWseek_dylibloader_orig_SDL2
#define SDL_RWtell SDL_RWtell_dylibloader_orig_SDL2
#define SDL_RWread SDL_RWread_dylibloader_orig_SDL2
#define SDL_RWwrite SDL_RWwrite_dylibloader_orig_SDL2
#define SDL_RWclose SDL_RWclose_dylibloader_orig_SDL2
#define SDL_LoadFile_RW SDL_LoadFile_RW_dylibloader_orig_SDL2
#define SDL_LoadFile SDL_LoadFile_dylibloader_orig_SDL2
#define SDL_ReadU8 SDL_ReadU8_dylibloader_orig_SDL2
#define SDL_ReadLE16 SDL_ReadLE16_dylibloader_orig_SDL2
#define SDL_ReadBE16 SDL_ReadBE16_dylibloader_orig_SDL2
#define SDL_ReadLE32 SDL_ReadLE32_dylibloader_orig_SDL2
#define SDL_ReadBE32 SDL_ReadBE32_dylibloader_orig_SDL2
#define SDL_ReadLE64 SDL_ReadLE64_dylibloader_orig_SDL2
#define SDL_ReadBE64 SDL_ReadBE64_dylibloader_orig_SDL2
#define SDL_WriteU8 SDL_WriteU8_dylibloader_orig_SDL2
#define SDL_WriteLE16 SDL_WriteLE16_dylibloader_orig_SDL2
#define SDL_WriteBE16 SDL_WriteBE16_dylibloader_orig_SDL2
#define SDL_WriteLE32 SDL_WriteLE32_dylibloader_orig_SDL2
#define SDL_WriteBE32 SDL_WriteBE32_dylibloader_orig_SDL2
#define SDL_WriteLE64 SDL_WriteLE64_dylibloader_orig_SDL2
#define SDL_WriteBE64 SDL_WriteBE64_dylibloader_orig_SDL2
#define SDL_LockJoysticks SDL_LockJoysticks_dylibloader_orig_SDL2
#define SDL_UnlockJoysticks SDL_UnlockJoysticks_dylibloader_orig_SDL2
#define SDL_NumJoysticks SDL_NumJoysticks_dylibloader_orig_SDL2
#define SDL_JoystickNameForIndex SDL_JoystickNameForIndex_dylibloader_orig_SDL2
#define SDL_JoystickPathForIndex SDL_JoystickPathForIndex_dylibloader_orig_SDL2
#define SDL_JoystickGetDevicePlayerIndex SDL_JoystickGetDevicePlayerIndex_dylibloader_orig_SDL2
#define SDL_JoystickGetDeviceGUID SDL_JoystickGetDeviceGUID_dylibloader_orig_SDL2
#define SDL_JoystickGetDeviceVendor SDL_JoystickGetDeviceVendor_dylibloader_orig_SDL2
#define SDL_JoystickGetDeviceProduct SDL_JoystickGetDeviceProduct_dylibloader_orig_SDL2
#define SDL_JoystickGetDeviceProductVersion SDL_JoystickGetDeviceProductVersion_dylibloader_orig_SDL2
#define SDL_JoystickGetDeviceType SDL_JoystickGetDeviceType_dylibloader_orig_SDL2
#define SDL_JoystickGetDeviceInstanceID SDL_JoystickGetDeviceInstanceID_dylibloader_orig_SDL2
#define SDL_JoystickOpen SDL_JoystickOpen_dylibloader_orig_SDL2
#define SDL_JoystickFromInstanceID SDL_JoystickFromInstanceID_dylibloader_orig_SDL2
#define SDL_JoystickFromPlayerIndex SDL_JoystickFromPlayerIndex_dylibloader_orig_SDL2
#define SDL_JoystickAttachVirtual SDL_JoystickAttachVirtual_dylibloader_orig_SDL2
#define SDL_JoystickAttachVirtualEx SDL_JoystickAttachVirtualEx_dylibloader_orig_SDL2
#define SDL_JoystickDetachVirtual SDL_JoystickDetachVirtual_dylibloader_orig_SDL2
#define SDL_JoystickIsVirtual SDL_JoystickIsVirtual_dylibloader_orig_SDL2
#define SDL_JoystickSetVirtualAxis SDL_JoystickSetVirtualAxis_dylibloader_orig_SDL2
#define SDL_JoystickSetVirtualButton SDL_JoystickSetVirtualButton_dylibloader_orig_SDL2
#define SDL_JoystickSetVirtualHat SDL_JoystickSetVirtualHat_dylibloader_orig_SDL2
#define SDL_JoystickName SDL_JoystickName_dylibloader_orig_SDL2
#define SDL_JoystickPath SDL_JoystickPath_dylibloader_orig_SDL2
#define SDL_JoystickGetPlayerIndex SDL_JoystickGetPlayerIndex_dylibloader_orig_SDL2
#define SDL_JoystickSetPlayerIndex SDL_JoystickSetPlayerIndex_dylibloader_orig_SDL2
#define SDL_JoystickGetGUID SDL_JoystickGetGUID_dylibloader_orig_SDL2
#define SDL_JoystickGetVendor SDL_JoystickGetVendor_dylibloader_orig_SDL2
#define SDL_JoystickGetProduct SDL_JoystickGetProduct_dylibloader_orig_SDL2
#define SDL_JoystickGetProductVersion SDL_JoystickGetProductVersion_dylibloader_orig_SDL2
#define SDL_JoystickGetFirmwareVersion SDL_JoystickGetFirmwareVersion_dylibloader_orig_SDL2
#define SDL_JoystickGetSerial SDL_JoystickGetSerial_dylibloader_orig_SDL2
#define SDL_JoystickGetType SDL_JoystickGetType_dylibloader_orig_SDL2
#define SDL_JoystickGetGUIDString SDL_JoystickGetGUIDString_dylibloader_orig_SDL2
#define SDL_JoystickGetGUIDFromString SDL_JoystickGetGUIDFromString_dylibloader_orig_SDL2
#define SDL_GetJoystickGUIDInfo SDL_GetJoystickGUIDInfo_dylibloader_orig_SDL2
#define SDL_JoystickGetAttached SDL_JoystickGetAttached_dylibloader_orig_SDL2
#define SDL_JoystickInstanceID SDL_JoystickInstanceID_dylibloader_orig_SDL2
#define SDL_JoystickNumAxes SDL_JoystickNumAxes_dylibloader_orig_SDL2
#define SDL_JoystickNumBalls SDL_JoystickNumBalls_dylibloader_orig_SDL2
#define SDL_JoystickNumHats SDL_JoystickNumHats_dylibloader_orig_SDL2
#define SDL_JoystickNumButtons SDL_JoystickNumButtons_dylibloader_orig_SDL2
#define SDL_JoystickUpdate SDL_JoystickUpdate_dylibloader_orig_SDL2
#define SDL_JoystickEventState SDL_JoystickEventState_dylibloader_orig_SDL2
#define SDL_JoystickGetAxis SDL_JoystickGetAxis_dylibloader_orig_SDL2
#define SDL_JoystickGetAxisInitialState SDL_JoystickGetAxisInitialState_dylibloader_orig_SDL2
#define SDL_JoystickGetHat SDL_JoystickGetHat_dylibloader_orig_SDL2
#define SDL_JoystickGetBall SDL_JoystickGetBall_dylibloader_orig_SDL2
#define SDL_JoystickGetButton SDL_JoystickGetButton_dylibloader_orig_SDL2
#define SDL_JoystickRumble SDL_JoystickRumble_dylibloader_orig_SDL2
#define SDL_JoystickRumbleTriggers SDL_JoystickRumbleTriggers_dylibloader_orig_SDL2
#define SDL_JoystickHasLED SDL_JoystickHasLED_dylibloader_orig_SDL2
#define SDL_JoystickHasRumble SDL_JoystickHasRumble_dylibloader_orig_SDL2
#define SDL_JoystickHasRumbleTriggers SDL_JoystickHasRumbleTriggers_dylibloader_orig_SDL2
#define SDL_JoystickSetLED SDL_JoystickSetLED_dylibloader_orig_SDL2
#define SDL_JoystickSendEffect SDL_JoystickSendEffect_dylibloader_orig_SDL2
#define SDL_JoystickClose SDL_JoystickClose_dylibloader_orig_SDL2
#define SDL_JoystickCurrentPowerLevel SDL_JoystickCurrentPowerLevel_dylibloader_orig_SDL2
#define SDL_GameControllerAddMappingsFromRW SDL_GameControllerAddMappingsFromRW_dylibloader_orig_SDL2
#define SDL_GameControllerAddMapping SDL_GameControllerAddMapping_dylibloader_orig_SDL2
#define SDL_GameControllerNumMappings SDL_GameControllerNumMappings_dylibloader_orig_SDL2
#define SDL_GameControllerMappingForIndex SDL_GameControllerMappingForIndex_dylibloader_orig_SDL2
#define SDL_GameControllerMappingForGUID SDL_GameControllerMappingForGUID_dylibloader_orig_SDL2
#define SDL_GameControllerMapping SDL_GameControllerMapping_dylibloader_orig_SDL2
#define SDL_IsGameController SDL_IsGameController_dylibloader_orig_SDL2
#define SDL_GameControllerNameForIndex SDL_GameControllerNameForIndex_dylibloader_orig_SDL2
#define SDL_GameControllerPathForIndex SDL_GameControllerPathForIndex_dylibloader_orig_SDL2
#define SDL_GameControllerTypeForIndex SDL_GameControllerTypeForIndex_dylibloader_orig_SDL2
#define SDL_GameControllerMappingForDeviceIndex SDL_GameControllerMappingForDeviceIndex_dylibloader_orig_SDL2
#define SDL_GameControllerOpen SDL_GameControllerOpen_dylibloader_orig_SDL2
#define SDL_GameControllerFromInstanceID SDL_GameControllerFromInstanceID_dylibloader_orig_SDL2
#define SDL_GameControllerFromPlayerIndex SDL_GameControllerFromPlayerIndex_dylibloader_orig_SDL2
#define SDL_GameControllerName SDL_GameControllerName_dylibloader_orig_SDL2
#define SDL_GameControllerPath SDL_GameControllerPath_dylibloader_orig_SDL2
#define SDL_GameControllerGetType SDL_GameControllerGetType_dylibloader_orig_SDL2
#define SDL_GameControllerGetPlayerIndex SDL_GameControllerGetPlayerIndex_dylibloader_orig_SDL2
#define SDL_GameControllerSetPlayerIndex SDL_GameControllerSetPlayerIndex_dylibloader_orig_SDL2
#define SDL_GameControllerGetVendor SDL_GameControllerGetVendor_dylibloader_orig_SDL2
#define SDL_GameControllerGetProduct SDL_GameControllerGetProduct_dylibloader_orig_SDL2
#define SDL_GameControllerGetProductVersion SDL_GameControllerGetProductVersion_dylibloader_orig_SDL2
#define SDL_GameControllerGetFirmwareVersion SDL_GameControllerGetFirmwareVersion_dylibloader_orig_SDL2
#define SDL_GameControllerGetSerial SDL_GameControllerGetSerial_dylibloader_orig_SDL2
#define SDL_GameControllerGetAttached SDL_GameControllerGetAttached_dylibloader_orig_SDL2
#define SDL_GameControllerGetJoystick SDL_GameControllerGetJoystick_dylibloader_orig_SDL2
#define SDL_GameControllerEventState SDL_GameControllerEventState_dylibloader_orig_SDL2
#define SDL_GameControllerUpdate SDL_GameControllerUpdate_dylibloader_orig_SDL2
#define SDL_GameControllerGetAxisFromString SDL_GameControllerGetAxisFromString_dylibloader_orig_SDL2
#define SDL_GameControllerGetStringForAxis SDL_GameControllerGetStringForAxis_dylibloader_orig_SDL2
#define SDL_GameControllerGetBindForAxis SDL_GameControllerGetBindForAxis_dylibloader_orig_SDL2
#define SDL_GameControllerHasAxis SDL_GameControllerHasAxis_dylibloader_orig_SDL2
#define SDL_GameControllerGetAxis SDL_GameControllerGetAxis_dylibloader_orig_SDL2
#define SDL_GameControllerGetButtonFromString SDL_GameControllerGetButtonFromString_dylibloader_orig_SDL2
#define SDL_GameControllerGetStringForButton SDL_GameControllerGetStringForButton_dylibloader_orig_SDL2
#define SDL_GameControllerGetBindForButton SDL_GameControllerGetBindForButton_dylibloader_orig_SDL2
#define SDL_GameControllerHasButton SDL_GameControllerHasButton_dylibloader_orig_SDL2
#define SDL_GameControllerGetButton SDL_GameControllerGetButton_dylibloader_orig_SDL2
#define SDL_GameControllerGetNumTouchpads SDL_GameControllerGetNumTouchpads_dylibloader_orig_SDL2
#define SDL_GameControllerGetNumTouchpadFingers SDL_GameControllerGetNumTouchpadFingers_dylibloader_orig_SDL2
#define SDL_GameControllerGetTouchpadFinger SDL_GameControllerGetTouchpadFinger_dylibloader_orig_SDL2
#define SDL_GameControllerHasSensor SDL_GameControllerHasSensor_dylibloader_orig_SDL2
#define SDL_GameControllerSetSensorEnabled SDL_GameControllerSetSensorEnabled_dylibloader_orig_SDL2
#define SDL_GameControllerIsSensorEnabled SDL_GameControllerIsSensorEnabled_dylibloader_orig_SDL2
#define SDL_GameControllerGetSensorDataRate SDL_GameControllerGetSensorDataRate_dylibloader_orig_SDL2
#define SDL_GameControllerGetSensorData SDL_GameControllerGetSensorData_dylibloader_orig_SDL2
#define SDL_GameControllerGetSensorDataWithTimestamp SDL_GameControllerGetSensorDataWithTimestamp_dylibloader_orig_SDL2
#define SDL_GameControllerRumble SDL_GameControllerRumble_dylibloader_orig_SDL2
#define SDL_GameControllerRumbleTriggers SDL_GameControllerRumbleTriggers_dylibloader_orig_SDL2
#define SDL_GameControllerHasLED SDL_GameControllerHasLED_dylibloader_orig_SDL2
#define SDL_GameControllerHasRumble SDL_GameControllerHasRumble_dylibloader_orig_SDL2
#define SDL_GameControllerHasRumbleTriggers SDL_GameControllerHasRumbleTriggers_dylibloader_orig_SDL2
#define SDL_GameControllerSetLED SDL_GameControllerSetLED_dylibloader_orig_SDL2
#define SDL_GameControllerSendEffect SDL_GameControllerSendEffect_dylibloader_orig_SDL2
#define SDL_GameControllerClose SDL_GameControllerClose_dylibloader_orig_SDL2
#define SDL_GameControllerGetAppleSFSymbolsNameForButton SDL_GameControllerGetAppleSFSymbolsNameForButton_dylibloader_orig_SDL2
#define SDL_GameControllerGetAppleSFSymbolsNameForAxis SDL_GameControllerGetAppleSFSymbolsNameForAxis_dylibloader_orig_SDL2
#define SDL_PumpEvents SDL_PumpEvents_dylibloader_orig_SDL2
#define SDL_PeepEvents SDL_PeepEvents_dylibloader_orig_SDL2
#define SDL_HasEvent SDL_HasEvent_dylibloader_orig_SDL2
#define SDL_HasEvents SDL_HasEvents_dylibloader_orig_SDL2
#define SDL_FlushEvent SDL_FlushEvent_dylibloader_orig_SDL2
#define SDL_FlushEvents SDL_FlushEvents_dylibloader_orig_SDL2
#define SDL_PollEvent SDL_PollEvent_dylibloader_orig_SDL2
#define SDL_WaitEvent SDL_WaitEvent_dylibloader_orig_SDL2
#define SDL_WaitEventTimeout SDL_WaitEventTimeout_dylibloader_orig_SDL2
#define SDL_PushEvent SDL_PushEvent_dylibloader_orig_SDL2
#define SDL_SetEventFilter SDL_SetEventFilter_dylibloader_orig_SDL2
#define SDL_GetEventFilter SDL_GetEventFilter_dylibloader_orig_SDL2
#define SDL_AddEventWatch SDL_AddEventWatch_dylibloader_orig_SDL2
#define SDL_DelEventWatch SDL_DelEventWatch_dylibloader_orig_SDL2
#define SDL_FilterEvents SDL_FilterEvents_dylibloader_orig_SDL2
#define SDL_EventState SDL_EventState_dylibloader_orig_SDL2
#define SDL_RegisterEvents SDL_RegisterEvents_dylibloader_orig_SDL2
#define SDL_SetHintWithPriority SDL_SetHintWithPriority_dylibloader_orig_SDL2
#define SDL_SetHint SDL_SetHint_dylibloader_orig_SDL2
#define SDL_ResetHint SDL_ResetHint_dylibloader_orig_SDL2
#define SDL_ResetHints SDL_ResetHints_dylibloader_orig_SDL2
#define SDL_GetHint SDL_GetHint_dylibloader_orig_SDL2
#define SDL_GetHintBoolean SDL_GetHintBoolean_dylibloader_orig_SDL2
#define SDL_AddHintCallback SDL_AddHintCallback_dylibloader_orig_SDL2
#define SDL_DelHintCallback SDL_DelHintCallback_dylibloader_orig_SDL2
#define SDL_ClearHints SDL_ClearHints_dylibloader_orig_SDL2
#define SDL_Init SDL_Init_dylibloader_orig_SDL2
#define SDL_InitSubSystem SDL_InitSubSystem_dylibloader_orig_SDL2
#define SDL_QuitSubSystem SDL_QuitSubSystem_dylibloader_orig_SDL2
#define SDL_WasInit SDL_WasInit_dylibloader_orig_SDL2
#define SDL_Quit SDL_Quit_dylibloader_orig_SDL2
#include "thirdparty/sdl_headers/SDL.h"
#include "thirdparty/sdl_headers/SDL_main.h"
#include "thirdparty/sdl_headers/SDL_error.h"
#include "thirdparty/sdl_headers/SDL_hints.h"
#include "thirdparty/sdl_headers/SDL_joystick.h"
#include "thirdparty/sdl_headers/SDL_events.h"
#include "thirdparty/sdl_headers/SDL_gamecontroller.h"
#include "thirdparty/sdl_headers/SDL_rwops.h"
#undef SDL_SetMainReady
#undef SDL_SetError
#undef SDL_GetError
#undef SDL_GetErrorMsg
#undef SDL_ClearError
#undef SDL_Error
#undef SDL_RWFromFile
#undef SDL_RWFromFP
#undef SDL_RWFromMem
#undef SDL_RWFromConstMem
#undef SDL_AllocRW
#undef SDL_FreeRW
#undef SDL_RWsize
#undef SDL_RWseek
#undef SDL_RWtell
#undef SDL_RWread
#undef SDL_RWwrite
#undef SDL_RWclose
#undef SDL_LoadFile_RW
#undef SDL_LoadFile
#undef SDL_ReadU8
#undef SDL_ReadLE16
#undef SDL_ReadBE16
#undef SDL_ReadLE32
#undef SDL_ReadBE32
#undef SDL_ReadLE64
#undef SDL_ReadBE64
#undef SDL_WriteU8
#undef SDL_WriteLE16
#undef SDL_WriteBE16
#undef SDL_WriteLE32
#undef SDL_WriteBE32
#undef SDL_WriteLE64
#undef SDL_WriteBE64
#undef SDL_LockJoysticks
#undef SDL_UnlockJoysticks
#undef SDL_NumJoysticks
#undef SDL_JoystickNameForIndex
#undef SDL_JoystickPathForIndex
#undef SDL_JoystickGetDevicePlayerIndex
#undef SDL_JoystickGetDeviceGUID
#undef SDL_JoystickGetDeviceVendor
#undef SDL_JoystickGetDeviceProduct
#undef SDL_JoystickGetDeviceProductVersion
#undef SDL_JoystickGetDeviceType
#undef SDL_JoystickGetDeviceInstanceID
#undef SDL_JoystickOpen
#undef SDL_JoystickFromInstanceID
#undef SDL_JoystickFromPlayerIndex
#undef SDL_JoystickAttachVirtual
#undef SDL_JoystickAttachVirtualEx
#undef SDL_JoystickDetachVirtual
#undef SDL_JoystickIsVirtual
#undef SDL_JoystickSetVirtualAxis
#undef SDL_JoystickSetVirtualButton
#undef SDL_JoystickSetVirtualHat
#undef SDL_JoystickName
#undef SDL_JoystickPath
#undef SDL_JoystickGetPlayerIndex
#undef SDL_JoystickSetPlayerIndex
#undef SDL_JoystickGetGUID
#undef SDL_JoystickGetVendor
#undef SDL_JoystickGetProduct
#undef SDL_JoystickGetProductVersion
#undef SDL_JoystickGetFirmwareVersion
#undef SDL_JoystickGetSerial
#undef SDL_JoystickGetType
#undef SDL_JoystickGetGUIDString
#undef SDL_JoystickGetGUIDFromString
#undef SDL_GetJoystickGUIDInfo
#undef SDL_JoystickGetAttached
#undef SDL_JoystickInstanceID
#undef SDL_JoystickNumAxes
#undef SDL_JoystickNumBalls
#undef SDL_JoystickNumHats
#undef SDL_JoystickNumButtons
#undef SDL_JoystickUpdate
#undef SDL_JoystickEventState
#undef SDL_JoystickGetAxis
#undef SDL_JoystickGetAxisInitialState
#undef SDL_JoystickGetHat
#undef SDL_JoystickGetBall
#undef SDL_JoystickGetButton
#undef SDL_JoystickRumble
#undef SDL_JoystickRumbleTriggers
#undef SDL_JoystickHasLED
#undef SDL_JoystickHasRumble
#undef SDL_JoystickHasRumbleTriggers
#undef SDL_JoystickSetLED
#undef SDL_JoystickSendEffect
#undef SDL_JoystickClose
#undef SDL_JoystickCurrentPowerLevel
#undef SDL_GameControllerAddMappingsFromRW
#undef SDL_GameControllerAddMapping
#undef SDL_GameControllerNumMappings
#undef SDL_GameControllerMappingForIndex
#undef SDL_GameControllerMappingForGUID
#undef SDL_GameControllerMapping
#undef SDL_IsGameController
#undef SDL_GameControllerNameForIndex
#undef SDL_GameControllerPathForIndex
#undef SDL_GameControllerTypeForIndex
#undef SDL_GameControllerMappingForDeviceIndex
#undef SDL_GameControllerOpen
#undef SDL_GameControllerFromInstanceID
#undef SDL_GameControllerFromPlayerIndex
#undef SDL_GameControllerName
#undef SDL_GameControllerPath
#undef SDL_GameControllerGetType
#undef SDL_GameControllerGetPlayerIndex
#undef SDL_GameControllerSetPlayerIndex
#undef SDL_GameControllerGetVendor
#undef SDL_GameControllerGetProduct
#undef SDL_GameControllerGetProductVersion
#undef SDL_GameControllerGetFirmwareVersion
#undef SDL_GameControllerGetSerial
#undef SDL_GameControllerGetAttached
#undef SDL_GameControllerGetJoystick
#undef SDL_GameControllerEventState
#undef SDL_GameControllerUpdate
#undef SDL_GameControllerGetAxisFromString
#undef SDL_GameControllerGetStringForAxis
#undef SDL_GameControllerGetBindForAxis
#undef SDL_GameControllerHasAxis
#undef SDL_GameControllerGetAxis
#undef SDL_GameControllerGetButtonFromString
#undef SDL_GameControllerGetStringForButton
#undef SDL_GameControllerGetBindForButton
#undef SDL_GameControllerHasButton
#undef SDL_GameControllerGetButton
#undef SDL_GameControllerGetNumTouchpads
#undef SDL_GameControllerGetNumTouchpadFingers
#undef SDL_GameControllerGetTouchpadFinger
#undef SDL_GameControllerHasSensor
#undef SDL_GameControllerSetSensorEnabled
#undef SDL_GameControllerIsSensorEnabled
#undef SDL_GameControllerGetSensorDataRate
#undef SDL_GameControllerGetSensorData
#undef SDL_GameControllerGetSensorDataWithTimestamp
#undef SDL_GameControllerRumble
#undef SDL_GameControllerRumbleTriggers
#undef SDL_GameControllerHasLED
#undef SDL_GameControllerHasRumble
#undef SDL_GameControllerHasRumbleTriggers
#undef SDL_GameControllerSetLED
#undef SDL_GameControllerSendEffect
#undef SDL_GameControllerClose
#undef SDL_GameControllerGetAppleSFSymbolsNameForButton
#undef SDL_GameControllerGetAppleSFSymbolsNameForAxis
#undef SDL_PumpEvents
#undef SDL_PeepEvents
#undef SDL_HasEvent
#undef SDL_HasEvents
#undef SDL_FlushEvent
#undef SDL_FlushEvents
#undef SDL_PollEvent
#undef SDL_WaitEvent
#undef SDL_WaitEventTimeout
#undef SDL_PushEvent
#undef SDL_SetEventFilter
#undef SDL_GetEventFilter
#undef SDL_AddEventWatch
#undef SDL_DelEventWatch
#undef SDL_FilterEvents
#undef SDL_EventState
#undef SDL_RegisterEvents
#undef SDL_SetHintWithPriority
#undef SDL_SetHint
#undef SDL_ResetHint
#undef SDL_ResetHints
#undef SDL_GetHint
#undef SDL_GetHintBoolean
#undef SDL_AddHintCallback
#undef SDL_DelHintCallback
#undef SDL_ClearHints
#undef SDL_Init
#undef SDL_InitSubSystem
#undef SDL_QuitSubSystem
#undef SDL_WasInit
#undef SDL_Quit
#include <dlfcn.h>
#include <stdio.h>
void (*SDL_SetMainReady_dylibloader_wrapper_SDL2)(void);
int (*SDL_SetError_dylibloader_wrapper_SDL2)(const char *, ...);
const char *(*SDL_GetError_dylibloader_wrapper_SDL2)(void);
char *(*SDL_GetErrorMsg_dylibloader_wrapper_SDL2)(char *, int);
void (*SDL_ClearError_dylibloader_wrapper_SDL2)(void);
int (*SDL_Error_dylibloader_wrapper_SDL2)(SDL_errorcode);
SDL_RWops *(*SDL_RWFromFile_dylibloader_wrapper_SDL2)(const char *, const char *);
SDL_RWops *(*SDL_RWFromFP_dylibloader_wrapper_SDL2)(void *, SDL_bool);
SDL_RWops *(*SDL_RWFromMem_dylibloader_wrapper_SDL2)(void *, int);
SDL_RWops *(*SDL_RWFromConstMem_dylibloader_wrapper_SDL2)(const void *, int);
SDL_RWops *(*SDL_AllocRW_dylibloader_wrapper_SDL2)(void);
void (*SDL_FreeRW_dylibloader_wrapper_SDL2)(SDL_RWops *);
Sint64 (*SDL_RWsize_dylibloader_wrapper_SDL2)(SDL_RWops *);
Sint64 (*SDL_RWseek_dylibloader_wrapper_SDL2)(SDL_RWops *, Sint64, int);
Sint64 (*SDL_RWtell_dylibloader_wrapper_SDL2)(SDL_RWops *);
size_t (*SDL_RWread_dylibloader_wrapper_SDL2)(SDL_RWops *, void *, size_t, size_t);
size_t (*SDL_RWwrite_dylibloader_wrapper_SDL2)(SDL_RWops *, const void *, size_t, size_t);
int (*SDL_RWclose_dylibloader_wrapper_SDL2)(SDL_RWops *);
void *(*SDL_LoadFile_RW_dylibloader_wrapper_SDL2)(SDL_RWops *, size_t *, int);
void *(*SDL_LoadFile_dylibloader_wrapper_SDL2)(const char *, size_t *);
Uint8 (*SDL_ReadU8_dylibloader_wrapper_SDL2)(SDL_RWops *);
Uint16 (*SDL_ReadLE16_dylibloader_wrapper_SDL2)(SDL_RWops *);
Uint16 (*SDL_ReadBE16_dylibloader_wrapper_SDL2)(SDL_RWops *);
Uint32 (*SDL_ReadLE32_dylibloader_wrapper_SDL2)(SDL_RWops *);
Uint32 (*SDL_ReadBE32_dylibloader_wrapper_SDL2)(SDL_RWops *);
Uint64 (*SDL_ReadLE64_dylibloader_wrapper_SDL2)(SDL_RWops *);
Uint64 (*SDL_ReadBE64_dylibloader_wrapper_SDL2)(SDL_RWops *);
size_t (*SDL_WriteU8_dylibloader_wrapper_SDL2)(SDL_RWops *, Uint8);
size_t (*SDL_WriteLE16_dylibloader_wrapper_SDL2)(SDL_RWops *, Uint16);
size_t (*SDL_WriteBE16_dylibloader_wrapper_SDL2)(SDL_RWops *, Uint16);
size_t (*SDL_WriteLE32_dylibloader_wrapper_SDL2)(SDL_RWops *, Uint32);
size_t (*SDL_WriteBE32_dylibloader_wrapper_SDL2)(SDL_RWops *, Uint32);
size_t (*SDL_WriteLE64_dylibloader_wrapper_SDL2)(SDL_RWops *, Uint64);
size_t (*SDL_WriteBE64_dylibloader_wrapper_SDL2)(SDL_RWops *, Uint64);
void (*SDL_LockJoysticks_dylibloader_wrapper_SDL2)(void);
void (*SDL_UnlockJoysticks_dylibloader_wrapper_SDL2)(void);
int (*SDL_NumJoysticks_dylibloader_wrapper_SDL2)(void);
const char *(*SDL_JoystickNameForIndex_dylibloader_wrapper_SDL2)(int);
const char *(*SDL_JoystickPathForIndex_dylibloader_wrapper_SDL2)(int);
int (*SDL_JoystickGetDevicePlayerIndex_dylibloader_wrapper_SDL2)(int);
SDL_JoystickGUID (*SDL_JoystickGetDeviceGUID_dylibloader_wrapper_SDL2)(int);
Uint16 (*SDL_JoystickGetDeviceVendor_dylibloader_wrapper_SDL2)(int);
Uint16 (*SDL_JoystickGetDeviceProduct_dylibloader_wrapper_SDL2)(int);
Uint16 (*SDL_JoystickGetDeviceProductVersion_dylibloader_wrapper_SDL2)(int);
SDL_JoystickType (*SDL_JoystickGetDeviceType_dylibloader_wrapper_SDL2)(int);
SDL_JoystickID (*SDL_JoystickGetDeviceInstanceID_dylibloader_wrapper_SDL2)(int);
SDL_Joystick *(*SDL_JoystickOpen_dylibloader_wrapper_SDL2)(int);
SDL_Joystick *(*SDL_JoystickFromInstanceID_dylibloader_wrapper_SDL2)(SDL_JoystickID);
SDL_Joystick *(*SDL_JoystickFromPlayerIndex_dylibloader_wrapper_SDL2)(int);
int (*SDL_JoystickAttachVirtual_dylibloader_wrapper_SDL2)(SDL_JoystickType, int, int, int);
int (*SDL_JoystickAttachVirtualEx_dylibloader_wrapper_SDL2)(const SDL_VirtualJoystickDesc *);
int (*SDL_JoystickDetachVirtual_dylibloader_wrapper_SDL2)(int);
SDL_bool (*SDL_JoystickIsVirtual_dylibloader_wrapper_SDL2)(int);
int (*SDL_JoystickSetVirtualAxis_dylibloader_wrapper_SDL2)(SDL_Joystick *, int, Sint16);
int (*SDL_JoystickSetVirtualButton_dylibloader_wrapper_SDL2)(SDL_Joystick *, int, Uint8);
int (*SDL_JoystickSetVirtualHat_dylibloader_wrapper_SDL2)(SDL_Joystick *, int, Uint8);
const char *(*SDL_JoystickName_dylibloader_wrapper_SDL2)(SDL_Joystick *);
const char *(*SDL_JoystickPath_dylibloader_wrapper_SDL2)(SDL_Joystick *);
int (*SDL_JoystickGetPlayerIndex_dylibloader_wrapper_SDL2)(SDL_Joystick *);
void (*SDL_JoystickSetPlayerIndex_dylibloader_wrapper_SDL2)(SDL_Joystick *, int);
SDL_JoystickGUID (*SDL_JoystickGetGUID_dylibloader_wrapper_SDL2)(SDL_Joystick *);
Uint16 (*SDL_JoystickGetVendor_dylibloader_wrapper_SDL2)(SDL_Joystick *);
Uint16 (*SDL_JoystickGetProduct_dylibloader_wrapper_SDL2)(SDL_Joystick *);
Uint16 (*SDL_JoystickGetProductVersion_dylibloader_wrapper_SDL2)(SDL_Joystick *);
Uint16 (*SDL_JoystickGetFirmwareVersion_dylibloader_wrapper_SDL2)(SDL_Joystick *);
const char *(*SDL_JoystickGetSerial_dylibloader_wrapper_SDL2)(SDL_Joystick *);
SDL_JoystickType (*SDL_JoystickGetType_dylibloader_wrapper_SDL2)(SDL_Joystick *);
void (*SDL_JoystickGetGUIDString_dylibloader_wrapper_SDL2)(SDL_JoystickGUID, char *, int);
SDL_JoystickGUID (*SDL_JoystickGetGUIDFromString_dylibloader_wrapper_SDL2)(const char *);
void (*SDL_GetJoystickGUIDInfo_dylibloader_wrapper_SDL2)(SDL_JoystickGUID, Uint16 *, Uint16 *, Uint16 *, Uint16 *);
SDL_bool (*SDL_JoystickGetAttached_dylibloader_wrapper_SDL2)(SDL_Joystick *);
SDL_JoystickID (*SDL_JoystickInstanceID_dylibloader_wrapper_SDL2)(SDL_Joystick *);
int (*SDL_JoystickNumAxes_dylibloader_wrapper_SDL2)(SDL_Joystick *);
int (*SDL_JoystickNumBalls_dylibloader_wrapper_SDL2)(SDL_Joystick *);
int (*SDL_JoystickNumHats_dylibloader_wrapper_SDL2)(SDL_Joystick *);
int (*SDL_JoystickNumButtons_dylibloader_wrapper_SDL2)(SDL_Joystick *);
void (*SDL_JoystickUpdate_dylibloader_wrapper_SDL2)(void);
int (*SDL_JoystickEventState_dylibloader_wrapper_SDL2)(int);
Sint16 (*SDL_JoystickGetAxis_dylibloader_wrapper_SDL2)(SDL_Joystick *, int);
SDL_bool (*SDL_JoystickGetAxisInitialState_dylibloader_wrapper_SDL2)(SDL_Joystick *, int, Sint16 *);
Uint8 (*SDL_JoystickGetHat_dylibloader_wrapper_SDL2)(SDL_Joystick *, int);
int (*SDL_JoystickGetBall_dylibloader_wrapper_SDL2)(SDL_Joystick *, int, int *, int *);
Uint8 (*SDL_JoystickGetButton_dylibloader_wrapper_SDL2)(SDL_Joystick *, int);
int (*SDL_JoystickRumble_dylibloader_wrapper_SDL2)(SDL_Joystick *, Uint16, Uint16, Uint32);
int (*SDL_JoystickRumbleTriggers_dylibloader_wrapper_SDL2)(SDL_Joystick *, Uint16, Uint16, Uint32);
SDL_bool (*SDL_JoystickHasLED_dylibloader_wrapper_SDL2)(SDL_Joystick *);
SDL_bool (*SDL_JoystickHasRumble_dylibloader_wrapper_SDL2)(SDL_Joystick *);
SDL_bool (*SDL_JoystickHasRumbleTriggers_dylibloader_wrapper_SDL2)(SDL_Joystick *);
int (*SDL_JoystickSetLED_dylibloader_wrapper_SDL2)(SDL_Joystick *, Uint8, Uint8, Uint8);
int (*SDL_JoystickSendEffect_dylibloader_wrapper_SDL2)(SDL_Joystick *, const void *, int);
void (*SDL_JoystickClose_dylibloader_wrapper_SDL2)(SDL_Joystick *);
SDL_JoystickPowerLevel (*SDL_JoystickCurrentPowerLevel_dylibloader_wrapper_SDL2)(SDL_Joystick *);
int (*SDL_GameControllerAddMappingsFromRW_dylibloader_wrapper_SDL2)(SDL_RWops *, int);
int (*SDL_GameControllerAddMapping_dylibloader_wrapper_SDL2)(const char *);
int (*SDL_GameControllerNumMappings_dylibloader_wrapper_SDL2)(void);
char *(*SDL_GameControllerMappingForIndex_dylibloader_wrapper_SDL2)(int);
char *(*SDL_GameControllerMappingForGUID_dylibloader_wrapper_SDL2)(SDL_JoystickGUID);
char *(*SDL_GameControllerMapping_dylibloader_wrapper_SDL2)(SDL_GameController *);
SDL_bool (*SDL_IsGameController_dylibloader_wrapper_SDL2)(int);
const char *(*SDL_GameControllerNameForIndex_dylibloader_wrapper_SDL2)(int);
const char *(*SDL_GameControllerPathForIndex_dylibloader_wrapper_SDL2)(int);
SDL_GameControllerType (*SDL_GameControllerTypeForIndex_dylibloader_wrapper_SDL2)(int);
char *(*SDL_GameControllerMappingForDeviceIndex_dylibloader_wrapper_SDL2)(int);
SDL_GameController *(*SDL_GameControllerOpen_dylibloader_wrapper_SDL2)(int);
SDL_GameController *(*SDL_GameControllerFromInstanceID_dylibloader_wrapper_SDL2)(SDL_JoystickID);
SDL_GameController *(*SDL_GameControllerFromPlayerIndex_dylibloader_wrapper_SDL2)(int);
const char *(*SDL_GameControllerName_dylibloader_wrapper_SDL2)(SDL_GameController *);
const char *(*SDL_GameControllerPath_dylibloader_wrapper_SDL2)(SDL_GameController *);
SDL_GameControllerType (*SDL_GameControllerGetType_dylibloader_wrapper_SDL2)(SDL_GameController *);
int (*SDL_GameControllerGetPlayerIndex_dylibloader_wrapper_SDL2)(SDL_GameController *);
void (*SDL_GameControllerSetPlayerIndex_dylibloader_wrapper_SDL2)(SDL_GameController *, int);
Uint16 (*SDL_GameControllerGetVendor_dylibloader_wrapper_SDL2)(SDL_GameController *);
Uint16 (*SDL_GameControllerGetProduct_dylibloader_wrapper_SDL2)(SDL_GameController *);
Uint16 (*SDL_GameControllerGetProductVersion_dylibloader_wrapper_SDL2)(SDL_GameController *);
Uint16 (*SDL_GameControllerGetFirmwareVersion_dylibloader_wrapper_SDL2)(SDL_GameController *);
const char *(*SDL_GameControllerGetSerial_dylibloader_wrapper_SDL2)(SDL_GameController *);
SDL_bool (*SDL_GameControllerGetAttached_dylibloader_wrapper_SDL2)(SDL_GameController *);
SDL_Joystick *(*SDL_GameControllerGetJoystick_dylibloader_wrapper_SDL2)(SDL_GameController *);
int (*SDL_GameControllerEventState_dylibloader_wrapper_SDL2)(int);
void (*SDL_GameControllerUpdate_dylibloader_wrapper_SDL2)(void);
SDL_GameControllerAxis (*SDL_GameControllerGetAxisFromString_dylibloader_wrapper_SDL2)(const char *);
const char *(*SDL_GameControllerGetStringForAxis_dylibloader_wrapper_SDL2)(SDL_GameControllerAxis);
SDL_GameControllerButtonBind (*SDL_GameControllerGetBindForAxis_dylibloader_wrapper_SDL2)(SDL_GameController *, SDL_GameControllerAxis);
SDL_bool (*SDL_GameControllerHasAxis_dylibloader_wrapper_SDL2)(SDL_GameController *, SDL_GameControllerAxis);
Sint16 (*SDL_GameControllerGetAxis_dylibloader_wrapper_SDL2)(SDL_GameController *, SDL_GameControllerAxis);
SDL_GameControllerButton (*SDL_GameControllerGetButtonFromString_dylibloader_wrapper_SDL2)(const char *);
const char *(*SDL_GameControllerGetStringForButton_dylibloader_wrapper_SDL2)(SDL_GameControllerButton);
SDL_GameControllerButtonBind (*SDL_GameControllerGetBindForButton_dylibloader_wrapper_SDL2)(SDL_GameController *, SDL_GameControllerButton);
SDL_bool (*SDL_GameControllerHasButton_dylibloader_wrapper_SDL2)(SDL_GameController *, SDL_GameControllerButton);
Uint8 (*SDL_GameControllerGetButton_dylibloader_wrapper_SDL2)(SDL_GameController *, SDL_GameControllerButton);
int (*SDL_GameControllerGetNumTouchpads_dylibloader_wrapper_SDL2)(SDL_GameController *);
int (*SDL_GameControllerGetNumTouchpadFingers_dylibloader_wrapper_SDL2)(SDL_GameController *, int);
int (*SDL_GameControllerGetTouchpadFinger_dylibloader_wrapper_SDL2)(SDL_GameController *, int, int, Uint8 *, float *, float *, float *);
SDL_bool (*SDL_GameControllerHasSensor_dylibloader_wrapper_SDL2)(SDL_GameController *, SDL_SensorType);
int (*SDL_GameControllerSetSensorEnabled_dylibloader_wrapper_SDL2)(SDL_GameController *, SDL_SensorType, SDL_bool);
SDL_bool (*SDL_GameControllerIsSensorEnabled_dylibloader_wrapper_SDL2)(SDL_GameController *, SDL_SensorType);
float (*SDL_GameControllerGetSensorDataRate_dylibloader_wrapper_SDL2)(SDL_GameController *, SDL_SensorType);
int (*SDL_GameControllerGetSensorData_dylibloader_wrapper_SDL2)(SDL_GameController *, SDL_SensorType, float *, int);
int (*SDL_GameControllerGetSensorDataWithTimestamp_dylibloader_wrapper_SDL2)(SDL_GameController *, SDL_SensorType, Uint64 *, float *, int);
int (*SDL_GameControllerRumble_dylibloader_wrapper_SDL2)(SDL_GameController *, Uint16, Uint16, Uint32);
int (*SDL_GameControllerRumbleTriggers_dylibloader_wrapper_SDL2)(SDL_GameController *, Uint16, Uint16, Uint32);
SDL_bool (*SDL_GameControllerHasLED_dylibloader_wrapper_SDL2)(SDL_GameController *);
SDL_bool (*SDL_GameControllerHasRumble_dylibloader_wrapper_SDL2)(SDL_GameController *);
SDL_bool (*SDL_GameControllerHasRumbleTriggers_dylibloader_wrapper_SDL2)(SDL_GameController *);
int (*SDL_GameControllerSetLED_dylibloader_wrapper_SDL2)(SDL_GameController *, Uint8, Uint8, Uint8);
int (*SDL_GameControllerSendEffect_dylibloader_wrapper_SDL2)(SDL_GameController *, const void *, int);
void (*SDL_GameControllerClose_dylibloader_wrapper_SDL2)(SDL_GameController *);
const char *(*SDL_GameControllerGetAppleSFSymbolsNameForButton_dylibloader_wrapper_SDL2)(SDL_GameController *, SDL_GameControllerButton);
const char *(*SDL_GameControllerGetAppleSFSymbolsNameForAxis_dylibloader_wrapper_SDL2)(SDL_GameController *, SDL_GameControllerAxis);
void (*SDL_PumpEvents_dylibloader_wrapper_SDL2)(void);
int (*SDL_PeepEvents_dylibloader_wrapper_SDL2)(SDL_Event *, int, SDL_eventaction, Uint32, Uint32);
SDL_bool (*SDL_HasEvent_dylibloader_wrapper_SDL2)(Uint32);
SDL_bool (*SDL_HasEvents_dylibloader_wrapper_SDL2)(Uint32, Uint32);
void (*SDL_FlushEvent_dylibloader_wrapper_SDL2)(Uint32);
void (*SDL_FlushEvents_dylibloader_wrapper_SDL2)(Uint32, Uint32);
int (*SDL_PollEvent_dylibloader_wrapper_SDL2)(SDL_Event *);
int (*SDL_WaitEvent_dylibloader_wrapper_SDL2)(SDL_Event *);
int (*SDL_WaitEventTimeout_dylibloader_wrapper_SDL2)(SDL_Event *, int);
int (*SDL_PushEvent_dylibloader_wrapper_SDL2)(SDL_Event *);
void (*SDL_SetEventFilter_dylibloader_wrapper_SDL2)(SDL_EventFilter, void *);
SDL_bool (*SDL_GetEventFilter_dylibloader_wrapper_SDL2)(SDL_EventFilter *, void **);
void (*SDL_AddEventWatch_dylibloader_wrapper_SDL2)(SDL_EventFilter, void *);
void (*SDL_DelEventWatch_dylibloader_wrapper_SDL2)(SDL_EventFilter, void *);
void (*SDL_FilterEvents_dylibloader_wrapper_SDL2)(SDL_EventFilter, void *);
Uint8 (*SDL_EventState_dylibloader_wrapper_SDL2)(Uint32, int);
Uint32 (*SDL_RegisterEvents_dylibloader_wrapper_SDL2)(int);
SDL_bool (*SDL_SetHintWithPriority_dylibloader_wrapper_SDL2)(const char *, const char *, SDL_HintPriority);
SDL_bool (*SDL_SetHint_dylibloader_wrapper_SDL2)(const char *, const char *);
SDL_bool (*SDL_ResetHint_dylibloader_wrapper_SDL2)(const char *);
void (*SDL_ResetHints_dylibloader_wrapper_SDL2)(void);
const char *(*SDL_GetHint_dylibloader_wrapper_SDL2)(const char *);
SDL_bool (*SDL_GetHintBoolean_dylibloader_wrapper_SDL2)(const char *, SDL_bool);
void (*SDL_AddHintCallback_dylibloader_wrapper_SDL2)(const char *, SDL_HintCallback, void *);
void (*SDL_DelHintCallback_dylibloader_wrapper_SDL2)(const char *, SDL_HintCallback, void *);
void (*SDL_ClearHints_dylibloader_wrapper_SDL2)(void);
int (*SDL_Init_dylibloader_wrapper_SDL2)(Uint32);
int (*SDL_InitSubSystem_dylibloader_wrapper_SDL2)(Uint32);
void (*SDL_QuitSubSystem_dylibloader_wrapper_SDL2)(Uint32);
Uint32 (*SDL_WasInit_dylibloader_wrapper_SDL2)(Uint32);
void (*SDL_Quit_dylibloader_wrapper_SDL2)(void);
int initialize_SDL2(int verbose) {
  void *handle;
  char *error;
  handle = dlopen("libSDL2-2.0.so.0", RTLD_LAZY);
  if (!handle) {
    if (verbose) {
      fprintf(stderr, "%s\n", dlerror());
    }
    return(1);
  }
  dlerror();
// SDL_SetMainReady
  *(void **) (&SDL_SetMainReady_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_SetMainReady");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_SetError
  *(void **) (&SDL_SetError_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_SetError");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GetError
  *(void **) (&SDL_GetError_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GetError");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GetErrorMsg
  *(void **) (&SDL_GetErrorMsg_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GetErrorMsg");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_ClearError
  *(void **) (&SDL_ClearError_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_ClearError");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_Error
  *(void **) (&SDL_Error_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_Error");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_RWFromFile
  *(void **) (&SDL_RWFromFile_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_RWFromFile");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_RWFromFP
  *(void **) (&SDL_RWFromFP_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_RWFromFP");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_RWFromMem
  *(void **) (&SDL_RWFromMem_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_RWFromMem");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_RWFromConstMem
  *(void **) (&SDL_RWFromConstMem_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_RWFromConstMem");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_AllocRW
  *(void **) (&SDL_AllocRW_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_AllocRW");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_FreeRW
  *(void **) (&SDL_FreeRW_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_FreeRW");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_RWsize
  *(void **) (&SDL_RWsize_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_RWsize");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_RWseek
  *(void **) (&SDL_RWseek_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_RWseek");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_RWtell
  *(void **) (&SDL_RWtell_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_RWtell");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_RWread
  *(void **) (&SDL_RWread_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_RWread");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_RWwrite
  *(void **) (&SDL_RWwrite_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_RWwrite");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_RWclose
  *(void **) (&SDL_RWclose_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_RWclose");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_LoadFile_RW
  *(void **) (&SDL_LoadFile_RW_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_LoadFile_RW");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_LoadFile
  *(void **) (&SDL_LoadFile_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_LoadFile");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_ReadU8
  *(void **) (&SDL_ReadU8_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_ReadU8");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_ReadLE16
  *(void **) (&SDL_ReadLE16_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_ReadLE16");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_ReadBE16
  *(void **) (&SDL_ReadBE16_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_ReadBE16");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_ReadLE32
  *(void **) (&SDL_ReadLE32_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_ReadLE32");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_ReadBE32
  *(void **) (&SDL_ReadBE32_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_ReadBE32");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_ReadLE64
  *(void **) (&SDL_ReadLE64_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_ReadLE64");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_ReadBE64
  *(void **) (&SDL_ReadBE64_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_ReadBE64");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_WriteU8
  *(void **) (&SDL_WriteU8_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_WriteU8");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_WriteLE16
  *(void **) (&SDL_WriteLE16_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_WriteLE16");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_WriteBE16
  *(void **) (&SDL_WriteBE16_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_WriteBE16");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_WriteLE32
  *(void **) (&SDL_WriteLE32_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_WriteLE32");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_WriteBE32
  *(void **) (&SDL_WriteBE32_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_WriteBE32");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_WriteLE64
  *(void **) (&SDL_WriteLE64_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_WriteLE64");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_WriteBE64
  *(void **) (&SDL_WriteBE64_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_WriteBE64");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_LockJoysticks
  *(void **) (&SDL_LockJoysticks_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_LockJoysticks");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_UnlockJoysticks
  *(void **) (&SDL_UnlockJoysticks_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_UnlockJoysticks");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_NumJoysticks
  *(void **) (&SDL_NumJoysticks_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_NumJoysticks");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickNameForIndex
  *(void **) (&SDL_JoystickNameForIndex_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickNameForIndex");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickPathForIndex
  *(void **) (&SDL_JoystickPathForIndex_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickPathForIndex");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickGetDevicePlayerIndex
  *(void **) (&SDL_JoystickGetDevicePlayerIndex_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickGetDevicePlayerIndex");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickGetDeviceGUID
  *(void **) (&SDL_JoystickGetDeviceGUID_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickGetDeviceGUID");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickGetDeviceVendor
  *(void **) (&SDL_JoystickGetDeviceVendor_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickGetDeviceVendor");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickGetDeviceProduct
  *(void **) (&SDL_JoystickGetDeviceProduct_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickGetDeviceProduct");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickGetDeviceProductVersion
  *(void **) (&SDL_JoystickGetDeviceProductVersion_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickGetDeviceProductVersion");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickGetDeviceType
  *(void **) (&SDL_JoystickGetDeviceType_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickGetDeviceType");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickGetDeviceInstanceID
  *(void **) (&SDL_JoystickGetDeviceInstanceID_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickGetDeviceInstanceID");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickOpen
  *(void **) (&SDL_JoystickOpen_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickOpen");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickFromInstanceID
  *(void **) (&SDL_JoystickFromInstanceID_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickFromInstanceID");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickFromPlayerIndex
  *(void **) (&SDL_JoystickFromPlayerIndex_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickFromPlayerIndex");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickAttachVirtual
  *(void **) (&SDL_JoystickAttachVirtual_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickAttachVirtual");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickAttachVirtualEx
  *(void **) (&SDL_JoystickAttachVirtualEx_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickAttachVirtualEx");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickDetachVirtual
  *(void **) (&SDL_JoystickDetachVirtual_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickDetachVirtual");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickIsVirtual
  *(void **) (&SDL_JoystickIsVirtual_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickIsVirtual");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickSetVirtualAxis
  *(void **) (&SDL_JoystickSetVirtualAxis_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickSetVirtualAxis");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickSetVirtualButton
  *(void **) (&SDL_JoystickSetVirtualButton_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickSetVirtualButton");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickSetVirtualHat
  *(void **) (&SDL_JoystickSetVirtualHat_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickSetVirtualHat");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickName
  *(void **) (&SDL_JoystickName_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickName");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickPath
  *(void **) (&SDL_JoystickPath_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickPath");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickGetPlayerIndex
  *(void **) (&SDL_JoystickGetPlayerIndex_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickGetPlayerIndex");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickSetPlayerIndex
  *(void **) (&SDL_JoystickSetPlayerIndex_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickSetPlayerIndex");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickGetGUID
  *(void **) (&SDL_JoystickGetGUID_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickGetGUID");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickGetVendor
  *(void **) (&SDL_JoystickGetVendor_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickGetVendor");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickGetProduct
  *(void **) (&SDL_JoystickGetProduct_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickGetProduct");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickGetProductVersion
  *(void **) (&SDL_JoystickGetProductVersion_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickGetProductVersion");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickGetFirmwareVersion
  *(void **) (&SDL_JoystickGetFirmwareVersion_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickGetFirmwareVersion");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickGetSerial
  *(void **) (&SDL_JoystickGetSerial_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickGetSerial");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickGetType
  *(void **) (&SDL_JoystickGetType_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickGetType");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickGetGUIDString
  *(void **) (&SDL_JoystickGetGUIDString_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickGetGUIDString");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickGetGUIDFromString
  *(void **) (&SDL_JoystickGetGUIDFromString_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickGetGUIDFromString");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GetJoystickGUIDInfo
  *(void **) (&SDL_GetJoystickGUIDInfo_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GetJoystickGUIDInfo");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickGetAttached
  *(void **) (&SDL_JoystickGetAttached_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickGetAttached");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickInstanceID
  *(void **) (&SDL_JoystickInstanceID_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickInstanceID");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickNumAxes
  *(void **) (&SDL_JoystickNumAxes_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickNumAxes");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickNumBalls
  *(void **) (&SDL_JoystickNumBalls_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickNumBalls");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickNumHats
  *(void **) (&SDL_JoystickNumHats_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickNumHats");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickNumButtons
  *(void **) (&SDL_JoystickNumButtons_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickNumButtons");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickUpdate
  *(void **) (&SDL_JoystickUpdate_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickUpdate");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickEventState
  *(void **) (&SDL_JoystickEventState_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickEventState");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickGetAxis
  *(void **) (&SDL_JoystickGetAxis_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickGetAxis");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickGetAxisInitialState
  *(void **) (&SDL_JoystickGetAxisInitialState_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickGetAxisInitialState");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickGetHat
  *(void **) (&SDL_JoystickGetHat_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickGetHat");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickGetBall
  *(void **) (&SDL_JoystickGetBall_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickGetBall");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickGetButton
  *(void **) (&SDL_JoystickGetButton_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickGetButton");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickRumble
  *(void **) (&SDL_JoystickRumble_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickRumble");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickRumbleTriggers
  *(void **) (&SDL_JoystickRumbleTriggers_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickRumbleTriggers");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickHasLED
  *(void **) (&SDL_JoystickHasLED_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickHasLED");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickHasRumble
  *(void **) (&SDL_JoystickHasRumble_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickHasRumble");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickHasRumbleTriggers
  *(void **) (&SDL_JoystickHasRumbleTriggers_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickHasRumbleTriggers");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickSetLED
  *(void **) (&SDL_JoystickSetLED_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickSetLED");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickSendEffect
  *(void **) (&SDL_JoystickSendEffect_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickSendEffect");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickClose
  *(void **) (&SDL_JoystickClose_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickClose");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_JoystickCurrentPowerLevel
  *(void **) (&SDL_JoystickCurrentPowerLevel_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_JoystickCurrentPowerLevel");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerAddMappingsFromRW
  *(void **) (&SDL_GameControllerAddMappingsFromRW_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerAddMappingsFromRW");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerAddMapping
  *(void **) (&SDL_GameControllerAddMapping_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerAddMapping");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerNumMappings
  *(void **) (&SDL_GameControllerNumMappings_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerNumMappings");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerMappingForIndex
  *(void **) (&SDL_GameControllerMappingForIndex_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerMappingForIndex");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerMappingForGUID
  *(void **) (&SDL_GameControllerMappingForGUID_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerMappingForGUID");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerMapping
  *(void **) (&SDL_GameControllerMapping_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerMapping");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_IsGameController
  *(void **) (&SDL_IsGameController_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_IsGameController");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerNameForIndex
  *(void **) (&SDL_GameControllerNameForIndex_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerNameForIndex");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerPathForIndex
  *(void **) (&SDL_GameControllerPathForIndex_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerPathForIndex");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerTypeForIndex
  *(void **) (&SDL_GameControllerTypeForIndex_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerTypeForIndex");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerMappingForDeviceIndex
  *(void **) (&SDL_GameControllerMappingForDeviceIndex_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerMappingForDeviceIndex");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerOpen
  *(void **) (&SDL_GameControllerOpen_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerOpen");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerFromInstanceID
  *(void **) (&SDL_GameControllerFromInstanceID_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerFromInstanceID");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerFromPlayerIndex
  *(void **) (&SDL_GameControllerFromPlayerIndex_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerFromPlayerIndex");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerName
  *(void **) (&SDL_GameControllerName_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerName");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerPath
  *(void **) (&SDL_GameControllerPath_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerPath");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerGetType
  *(void **) (&SDL_GameControllerGetType_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerGetType");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerGetPlayerIndex
  *(void **) (&SDL_GameControllerGetPlayerIndex_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerGetPlayerIndex");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerSetPlayerIndex
  *(void **) (&SDL_GameControllerSetPlayerIndex_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerSetPlayerIndex");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerGetVendor
  *(void **) (&SDL_GameControllerGetVendor_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerGetVendor");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerGetProduct
  *(void **) (&SDL_GameControllerGetProduct_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerGetProduct");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerGetProductVersion
  *(void **) (&SDL_GameControllerGetProductVersion_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerGetProductVersion");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerGetFirmwareVersion
  *(void **) (&SDL_GameControllerGetFirmwareVersion_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerGetFirmwareVersion");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerGetSerial
  *(void **) (&SDL_GameControllerGetSerial_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerGetSerial");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerGetAttached
  *(void **) (&SDL_GameControllerGetAttached_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerGetAttached");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerGetJoystick
  *(void **) (&SDL_GameControllerGetJoystick_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerGetJoystick");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerEventState
  *(void **) (&SDL_GameControllerEventState_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerEventState");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerUpdate
  *(void **) (&SDL_GameControllerUpdate_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerUpdate");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerGetAxisFromString
  *(void **) (&SDL_GameControllerGetAxisFromString_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerGetAxisFromString");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerGetStringForAxis
  *(void **) (&SDL_GameControllerGetStringForAxis_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerGetStringForAxis");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerGetBindForAxis
  *(void **) (&SDL_GameControllerGetBindForAxis_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerGetBindForAxis");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerHasAxis
  *(void **) (&SDL_GameControllerHasAxis_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerHasAxis");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerGetAxis
  *(void **) (&SDL_GameControllerGetAxis_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerGetAxis");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerGetButtonFromString
  *(void **) (&SDL_GameControllerGetButtonFromString_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerGetButtonFromString");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerGetStringForButton
  *(void **) (&SDL_GameControllerGetStringForButton_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerGetStringForButton");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerGetBindForButton
  *(void **) (&SDL_GameControllerGetBindForButton_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerGetBindForButton");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerHasButton
  *(void **) (&SDL_GameControllerHasButton_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerHasButton");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerGetButton
  *(void **) (&SDL_GameControllerGetButton_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerGetButton");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerGetNumTouchpads
  *(void **) (&SDL_GameControllerGetNumTouchpads_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerGetNumTouchpads");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerGetNumTouchpadFingers
  *(void **) (&SDL_GameControllerGetNumTouchpadFingers_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerGetNumTouchpadFingers");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerGetTouchpadFinger
  *(void **) (&SDL_GameControllerGetTouchpadFinger_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerGetTouchpadFinger");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerHasSensor
  *(void **) (&SDL_GameControllerHasSensor_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerHasSensor");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerSetSensorEnabled
  *(void **) (&SDL_GameControllerSetSensorEnabled_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerSetSensorEnabled");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerIsSensorEnabled
  *(void **) (&SDL_GameControllerIsSensorEnabled_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerIsSensorEnabled");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerGetSensorDataRate
  *(void **) (&SDL_GameControllerGetSensorDataRate_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerGetSensorDataRate");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerGetSensorData
  *(void **) (&SDL_GameControllerGetSensorData_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerGetSensorData");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerGetSensorDataWithTimestamp
  *(void **) (&SDL_GameControllerGetSensorDataWithTimestamp_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerGetSensorDataWithTimestamp");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerRumble
  *(void **) (&SDL_GameControllerRumble_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerRumble");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerRumbleTriggers
  *(void **) (&SDL_GameControllerRumbleTriggers_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerRumbleTriggers");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerHasLED
  *(void **) (&SDL_GameControllerHasLED_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerHasLED");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerHasRumble
  *(void **) (&SDL_GameControllerHasRumble_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerHasRumble");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerHasRumbleTriggers
  *(void **) (&SDL_GameControllerHasRumbleTriggers_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerHasRumbleTriggers");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerSetLED
  *(void **) (&SDL_GameControllerSetLED_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerSetLED");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerSendEffect
  *(void **) (&SDL_GameControllerSendEffect_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerSendEffect");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerClose
  *(void **) (&SDL_GameControllerClose_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerClose");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerGetAppleSFSymbolsNameForButton
  *(void **) (&SDL_GameControllerGetAppleSFSymbolsNameForButton_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerGetAppleSFSymbolsNameForButton");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GameControllerGetAppleSFSymbolsNameForAxis
  *(void **) (&SDL_GameControllerGetAppleSFSymbolsNameForAxis_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GameControllerGetAppleSFSymbolsNameForAxis");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_PumpEvents
  *(void **) (&SDL_PumpEvents_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_PumpEvents");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_PeepEvents
  *(void **) (&SDL_PeepEvents_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_PeepEvents");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_HasEvent
  *(void **) (&SDL_HasEvent_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_HasEvent");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_HasEvents
  *(void **) (&SDL_HasEvents_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_HasEvents");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_FlushEvent
  *(void **) (&SDL_FlushEvent_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_FlushEvent");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_FlushEvents
  *(void **) (&SDL_FlushEvents_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_FlushEvents");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_PollEvent
  *(void **) (&SDL_PollEvent_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_PollEvent");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_WaitEvent
  *(void **) (&SDL_WaitEvent_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_WaitEvent");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_WaitEventTimeout
  *(void **) (&SDL_WaitEventTimeout_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_WaitEventTimeout");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_PushEvent
  *(void **) (&SDL_PushEvent_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_PushEvent");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_SetEventFilter
  *(void **) (&SDL_SetEventFilter_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_SetEventFilter");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GetEventFilter
  *(void **) (&SDL_GetEventFilter_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GetEventFilter");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_AddEventWatch
  *(void **) (&SDL_AddEventWatch_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_AddEventWatch");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_DelEventWatch
  *(void **) (&SDL_DelEventWatch_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_DelEventWatch");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_FilterEvents
  *(void **) (&SDL_FilterEvents_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_FilterEvents");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_EventState
  *(void **) (&SDL_EventState_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_EventState");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_RegisterEvents
  *(void **) (&SDL_RegisterEvents_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_RegisterEvents");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_SetHintWithPriority
  *(void **) (&SDL_SetHintWithPriority_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_SetHintWithPriority");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_SetHint
  *(void **) (&SDL_SetHint_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_SetHint");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_ResetHint
  *(void **) (&SDL_ResetHint_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_ResetHint");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_ResetHints
  *(void **) (&SDL_ResetHints_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_ResetHints");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GetHint
  *(void **) (&SDL_GetHint_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GetHint");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_GetHintBoolean
  *(void **) (&SDL_GetHintBoolean_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_GetHintBoolean");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_AddHintCallback
  *(void **) (&SDL_AddHintCallback_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_AddHintCallback");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_DelHintCallback
  *(void **) (&SDL_DelHintCallback_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_DelHintCallback");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_ClearHints
  *(void **) (&SDL_ClearHints_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_ClearHints");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_Init
  *(void **) (&SDL_Init_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_Init");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_InitSubSystem
  *(void **) (&SDL_InitSubSystem_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_InitSubSystem");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_QuitSubSystem
  *(void **) (&SDL_QuitSubSystem_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_QuitSubSystem");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_WasInit
  *(void **) (&SDL_WasInit_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_WasInit");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// SDL_Quit
  *(void **) (&SDL_Quit_dylibloader_wrapper_SDL2) = dlsym(handle, "SDL_Quit");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
return 0;
}
