#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

import make_virtuals

env.CommandNoCache(["gdvirtual.gen.inc"], "make_virtuals.py", env.Run(make_virtuals.run))

env_object = env.Clone()

env_object.add_source_files(env.core_sources, "*.cpp")
