#!/usr/bin/env python

from typing import TYPE_CHECKING

import make_virtuals
from SCons.Script.SConscript import SConsEnvironment

if TYPE_CHECKING:
    env = SConsEnvironment()
    Import = SConsEnvironment.Import

Import("env")

env.CommandNoCache(["gdvirtual.gen.inc"], "make_virtuals.py", env.Run(make_virtuals.run))

env_object = env.Clone()

env_object.add_source_files(env.core_sources, "*.cpp")
