#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env", "py_builder_env")

py_builder_env.CommandNoCache(
    "gdvirtual.gen.h",
    "make_virtuals.py",
    Action(
        "$PYTHON_BIN core/object/make_virtuals.py --target $TARGET",
        "$GENCOMSTR",
    ),
)

env.add_source_files(env.core_sources, "*.cpp")
