#!/usr/bin/env python

Import("env")
Import("env_modules")

env_pvr = env_modules.Clone()

# Thirdparty source files
# Not unbundled so far since not widespread as shared library
thirdparty_dir = "#thirdparty/pvrtccompressor/"
thirdparty_sources = [
    "BitScale.cpp",
    "MortonTable.cpp",
    "PvrTcDecoder.cpp",
    "PvrTcEncoder.cpp",
    "PvrTcPacket.cpp",
]
thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

env_pvr.Prepend(CPPPATH=[thirdparty_dir])

env_thirdparty = env_pvr.Clone()
env_thirdparty.disable_warnings()
env_thirdparty.add_source_files(env.modules_sources, thirdparty_sources)

# Godot source files
env_pvr.add_source_files(env.modules_sources, "*.cpp")
