#!/usr/bin/env python

from scons_hints import *

Import("env")

env.add_source_files(env.servers_sources, "*.cpp")

SConscript("effects/SCsub")
SConscript("environment/SCsub")
SConscript("forward_clustered/SCsub")
SConscript("forward_mobile/SCsub")
SConscript("shaders/SCsub")
SConscript("spirv-reflect/SCsub")
SConscript("storage_rd/SCsub")
