#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.add_source_files(env.servers_sources, "*.cpp")

env.add_subdirectory("effects/SCsub")
env.add_subdirectory("environment/SCsub")
env.add_subdirectory("forward_clustered/SCsub")
env.add_subdirectory("forward_mobile/SCsub")
env.add_subdirectory("shaders/SCsub")
env.add_subdirectory("spirv-reflect/SCsub")
env.add_subdirectory("storage_rd/SCsub")
