#!/usr/bin/env python

Import("env")
Import("env_modules")

env_replication = env_modules.Clone()

env_replication.add_source_files(env.modules_sources, "editor/*.cpp")
env_replication.add_source_files(env.modules_sources, "*.cpp")
