#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_matroska = env_modules.Clone()

# Godot source files

module_obj = []

env_matroska.add_source_files(module_obj, "*.cpp")

env.modules_sources += module_obj
