#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.add_source_files(env["SCENE_SOURCES"], "fog_material.cpp")
env.add_source_files(env["SCENE_SOURCES"], "importer_mesh.cpp")
env.add_source_files(env["SCENE_SOURCES"], "joint_limitation_3d.cpp")
env.add_source_files(env["SCENE_SOURCES"], "joint_limitation_cone_3d.cpp")
env.add_source_files(env["SCENE_SOURCES"], "mesh_library.cpp")
env.add_source_files(env["SCENE_SOURCES"], "primitive_meshes.cpp")
env.add_source_files(env["SCENE_SOURCES"], "skin.cpp")
env.add_source_files(env["SCENE_SOURCES"], "sky_material.cpp")
env.add_source_files(env["SCENE_SOURCES"], "world_3d.cpp")
env.add_source_files(env["SCENE_SOURCES"], "skeleton/*.cpp")

if not env["disable_physics_3d"]:
    env.add_source_files(env["SCENE_SOURCES"], "box_shape_3d.cpp")
    env.add_source_files(env["SCENE_SOURCES"], "capsule_shape_3d.cpp")
    env.add_source_files(env["SCENE_SOURCES"], "circle_shape_3d.cpp")
    env.add_source_files(env["SCENE_SOURCES"], "concave_polygon_shape_3d.cpp")
    env.add_source_files(env["SCENE_SOURCES"], "convex_polygon_shape_3d.cpp")
    env.add_source_files(env["SCENE_SOURCES"], "cylinder_shape_3d.cpp")
    env.add_source_files(env["SCENE_SOURCES"], "height_map_shape_3d.cpp")
    env.add_source_files(env["SCENE_SOURCES"], "separation_ray_shape_3d.cpp")
    env.add_source_files(env["SCENE_SOURCES"], "shape_3d.cpp")
    env.add_source_files(env["SCENE_SOURCES"], "sphere_shape_3d.cpp")
    env.add_source_files(env["SCENE_SOURCES"], "world_boundary_shape_3d.cpp")
if not env["disable_navigation_3d"]:
    env.add_source_files(env["SCENE_SOURCES"], "navigation_mesh_source_geometry_data_3d.cpp")
