#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_gltf = env_modules.Clone()

# Godot source files

env_gltf.add_source_files(env["MODULES_SOURCES"], "*.cpp")
env_gltf.add_source_files(env["MODULES_SOURCES"], "structures/*.cpp")

SConscript("extensions/SCsub")

if env["EDITOR_BUILD"]:
    env_gltf.add_source_files(env["MODULES_SOURCES"], "editor/*.cpp")
