#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_lightmapper_rd = env_modules.Clone()

for file in Glob("*.glsl", exclude="*_inc.glsl"):
    env_lightmapper_rd.GLSL_HEADER(file)

# Godot source files
env_lightmapper_rd.add_source_files(env.modules_sources, "*.cpp")
