#!/usr/bin/env python
from __future__ import annotations

from misc.utility.scons_hints import *

Import("env")

env.add_source_files(env.editor_sources, "*.cpp")
env.add_source_files(env.editor_sources, "3d/*.cpp")
