#!/usr/bin/env python

import glob
from typing import TYPE_CHECKING

import editor_theme_builders
from SCons.Script.SConscript import SConsEnvironment

if TYPE_CHECKING:
    env = SConsEnvironment()
    Import = SConsEnvironment.Import

Import("env")

# Fonts
flist = glob.glob(env.Dir("#thirdparty").abspath + "/fonts/*.ttf")
flist.extend(glob.glob(env.Dir("#thirdparty").abspath + "/fonts/*.otf"))
flist.extend(glob.glob(env.Dir("#thirdparty").abspath + "/fonts/*.woff"))
flist.extend(glob.glob(env.Dir("#thirdparty").abspath + "/fonts/*.woff2"))
flist.sort()
env.Depends("#editor/themes/builtin_fonts.gen.h", flist)
env.CommandNoCache(
    "#editor/themes/builtin_fonts.gen.h",
    flist,
    env.Run(editor_theme_builders.make_fonts_header),
)

env.add_source_files(env.editor_sources, "*.cpp")
