#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env", "py_builder_env")

# Fonts
flist = Glob("#thirdparty/fonts/*.ttf")
flist.extend(Glob("#thirdparty/fonts/*.otf"))
flist.extend(Glob("#thirdparty/fonts/*.woff"))
flist.extend(Glob("#thirdparty/fonts/*.woff2"))
flist.sort()
py_builder_env.Command(
    "#editor/themes/builtin_fonts.gen.h",
    flist,
    Action(
        "$PYTHON_BIN editor/themes/editor_theme_builders.py --method make_fonts_header --target $TARGET --source $SOURCES",
        "$GENCOMSTR",
    ),
)

env.add_source_files(env.editor_sources, "*.cpp")
