#!/usr/bin/env python

Import('env')
Import('env_modules')

env_orca = env_modules.Clone()

# Thirdparty source files
if env['builtin_rvo2']:
    thirdparty_dir = "#thirdparty/rvo2"
    thirdparty_sources = [
                "/src/Agent.cpp",
                "/src/KdTree.cpp",
                "/src/Obstacle.cpp",
    ]
    thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

    env_orca.Prepend(CPPPATH=[thirdparty_dir + "/src"])

    env_thirdparty = env_orca.Clone()
    env_thirdparty.disable_warnings()
    env_thirdparty.add_source_files(env.modules_sources, thirdparty_sources)

# Godot source files
env_orca.add_source_files(env.modules_sources, "*.cpp")
