name: Build Android
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - {arch: arm64, precision: single}
          - {arch: arm64, precision: double}
          - {arch: arm32, precision: single}
          - {arch: arm32, precision: double}
          - {arch: x86_64, precision: single}
          - {arch: x86_64, precision: double}
          - {arch: x86_32, precision: single}
          - {arch: x86_32, precision: double}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1

      - name: Install newer Clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x ./llvm.sh
          sudo ./llvm.sh 17

      - name: 🔗 GDExtension Build
        uses: godotengine/godot-cpp-template/.github/actions/build@f9564a9c8115139b9624692d39e358291f6d76ce
        with:
          platform: android
          arch: ${{ matrix.arch }}
          build-target-type: template_release
          float-precision: ${{ matrix.precision }}
          godot-cpp-directory: thirdparty/godot-cpp

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot-sandbox-android-${{ matrix.arch }}-${{ matrix.precision }}
          path: |
            ${{ github.workspace }}/bin/**/*.so
          if-no-files-found: error
          retention-days: 10 # 90 days by default
