#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_claude_ai = env_modules.Clone()

# Godot source files
module_obj = []

env_claude_ai.add_source_files(module_obj, "*.cpp")
if env.editor_build:
    env_claude_ai.add_source_files(module_obj, "editor/*.cpp")

env.modules_sources += module_obj

