#!/usr/bin/env python

Import('env')
Import('env_modules')

env_tga = env_modules.Clone()

# Godot's own source files
env_tga.add_source_files(env.modules_sources, "*.cpp")
env_tga.add_header_files(env.modules_headers, "*.h")