#!/usr/bin/env python

Import("env")
Import("env_modules")

env_vsdecoder_gdnative = env_modules.Clone()

env_vsdecoder_gdnative.Prepend(CPPPATH=["#modules/gdnative/include/"])
env_vsdecoder_gdnative.add_source_files(env.modules_sources, "*.cpp")
