#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.scene_sources = []

# Godot source files
env.add_source_files(env.scene_sources, "*.cpp")

# Chain load SCsubs
env.add_subdirectory("main/SCsub")
env.add_subdirectory("gui/SCsub")
if not env["disable_3d"]:
    env.add_subdirectory("3d/SCsub")
env.add_subdirectory("2d/SCsub")
env.add_subdirectory("animation/SCsub")
env.add_subdirectory("audio/SCsub")
env.add_subdirectory("resources/SCsub")
env.add_subdirectory("debugger/SCsub")
env.add_subdirectory("theme/SCsub")

# Build it all as a library
lib = env.add_library("scene", env.scene_sources)
env.Prepend(LIBS=[lib])
