#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.add_source_files(env.drivers_sources, "*.cpp")

SConscript("shaders/SCsub")
SConscript("storage/SCsub")
SConscript("effects/SCsub")
SConscript("environment/SCsub")
