#!/usr/bin/env python

Import("env")
Import("env_modules")

env_stb_vorbis = env_modules.Clone()

# Thirdparty source files

thirdparty_obj = []

thirdparty_sources = ["#thirdparty/misc/stb_vorbis.c"]

env_thirdparty = env_stb_vorbis.Clone()
env_thirdparty.disable_warnings()
env_thirdparty.add_source_files(thirdparty_obj, thirdparty_sources)
env.modules_sources += thirdparty_obj

# Godot source files

module_obj = []

env_stb_vorbis.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj

# Needed to force rebuilding the module files when the thirdparty library is updated.
env.Depends(module_obj, thirdparty_obj)
