#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules py_builder_env")

env_betsy = py_builder_env.Clone()

# Betsy shaders, originally from https://github.com/darksylinc/betsy
env_betsy.GLSL_HEADER("bc6h.glsl")
env_betsy.GLSL_HEADER("bc1.glsl")
env_betsy.GLSL_HEADER("bc4.glsl")
env_betsy.GLSL_HEADER("alpha_stitch.glsl")
env_betsy.GLSL_HEADER("rgb_to_rgba.glsl")

# Godot source files
env_betsy.add_source_files(env.modules_sources, "*.cpp")
