var searchData=
[
  ['r',['R',['../classcom_1_1android_1_1vending_1_1expansion_1_1downloader_1_1_r.html',1,'com::android::vending::expansion::downloader']]],
  ['rand_5fmeth_5fst',['rand_meth_st',['../structrand__meth__st.html',1,'']]],
  ['range',['Range',['../class_range.html',1,'']]],
  ['rangefit',['RangeFit',['../classsquish_1_1_range_fit.html',1,'squish']]],
  ['rasterizer',['Rasterizer',['../class_rasterizer.html',1,'']]],
  ['rasterizerdummy',['RasterizerDummy',['../class_rasterizer_dummy.html',1,'']]],
  ['rasterizerflash',['RasterizerFlash',['../class_rasterizer_flash.html',1,'']]],
  ['rate',['rate',['../struct_speex_header.html#a6157e9a625429578f62accb14dd39d3b',1,'SpeexHeader']]],
  ['raycast',['RayCast',['../class_ray_cast.html',1,'']]],
  ['raycast2d',['RayCast2D',['../class_ray_cast2_d.html',1,'']]],
  ['raycastspatialgizmo',['RayCastSpatialGizmo',['../class_ray_cast_spatial_gizmo.html',1,'']]],
  ['rayresult',['RayResult',['../struct_physics_direct_space_state_1_1_ray_result.html',1,'PhysicsDirectSpaceState']]],
  ['rayresult',['RayResult',['../struct_physics2_d_direct_space_state_1_1_ray_result.html',1,'Physics2DDirectSpaceState']]],
  ['rayshape',['RayShape',['../class_ray_shape.html',1,'']]],
  ['rayshape2d',['RayShape2D',['../class_ray_shape2_d.html',1,'']]],
  ['rayshape2dsw',['RayShape2DSW',['../class_ray_shape2_d_s_w.html',1,'']]],
  ['rayshapesw',['RayShapeSW',['../class_ray_shape_s_w.html',1,'']]],
  ['rc2_5fkey_5fst',['rc2_key_st',['../structrc2__key__st.html',1,'']]],
  ['rc4_5fkey_5fst',['rc4_key_st',['../structrc4__key__st.html',1,'']]],
  ['rc5_5fkey_5fst',['rc5_key_st',['../structrc5__key__st.html',1,'']]],
  ['read',['Read',['../class_d_vector_1_1_read.html',1,'DVector']]],
  ['read',['read',['../structmpc__reader__t.html#aafc52aca4460e9168108a928bb6a773f',1,'mpc_reader_t::read()'],['../class_theora_data_source.html#a2c314eba2e5301b9a6d49e625498e5f7',1,'TheoraDataSource::read()'],['../class_theora_file_data_source.html#ad74b126de5960c3a10ddfb8621af90e1',1,'TheoraFileDataSource::read()'],['../class_theora_memory_file_data_source.html#afe4d052c61f7c8552af561c5a9305417',1,'TheoraMemoryFileDataSource::read()'],['../class_t_p_data_f_a.html#a28a764b12203550d58625fda5894a60a',1,'TPDataFA::read()']]],
  ['reader_2eh',['reader.h',['../reader_8h.html',1,'']]],
  ['realloc',['realloc',['../class_memory_pool_static.html#a33ec73cb115d12b1b7c12fa8440b730a',1,'MemoryPoolStatic::realloc()'],['../class_memory_pool_static_malloc.html#adeb69fa18cfc813c14590e900de47c8c',1,'MemoryPoolStaticMalloc::realloc()']]],
  ['realspeexstereostate',['RealSpeexStereoState',['../struct_real_speex_stereo_state.html',1,'']]],
  ['record_5fpqueue_5fst',['record_pqueue_st',['../structrecord__pqueue__st.html',1,'']]],
  ['rect2',['Rect2',['../struct_rect2.html',1,'']]],
  ['rect2i',['Rect2i',['../struct_rect2i.html',1,'']]],
  ['rectangleshape2d',['RectangleShape2D',['../class_rectangle_shape2_d.html',1,'']]],
  ['rectangleshape2dsw',['RectangleShape2DSW',['../class_rectangle_shape2_d_s_w.html',1,'']]],
  ['redraw',['redraw',['../class_slider_joint_spatial_gizmo.html#ac461f915f272fc0ddb43b513c445c652',1,'SliderJointSpatialGizmo::redraw()'],['../class_cone_twist_joint_spatial_gizmo.html#a76d383b90b4f9f504b10d4eab9fab027',1,'ConeTwistJointSpatialGizmo::redraw()'],['../class_generic6_d_o_f_joint_spatial_gizmo.html#a2ae3ce8d77b83c915f0cd9c5fe74da8b',1,'Generic6DOFJointSpatialGizmo::redraw()']]],
  ['ref',['Ref',['../class_ref.html',1,'']]],
  ['ref_3c_20animation_20_3e',['Ref&lt; Animation &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20audiostream_20_3e',['Ref&lt; AudioStream &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20audiostreaminput_20_3e',['Ref&lt; AudioStreamInput &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20bakedlight_20_3e',['Ref&lt; BakedLight &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20bitmap_20_3e',['Ref&lt; BitMap &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20canvasitemmaterial_20_3e',['Ref&lt; CanvasItemMaterial &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20colorramp_20_3e',['Ref&lt; ColorRamp &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20curve2d_20_3e',['Ref&lt; Curve2D &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20curve3d_20_3e',['Ref&lt; Curve3D &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20editorsettings_20_3e',['Ref&lt; EditorSettings &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20environment_20_3e',['Ref&lt; Environment &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20eventstream_20_3e',['Ref&lt; EventStream &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20eventstreamchibi_20_3e',['Ref&lt; EventStreamChibi &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20eventstreamplayback_20_3e',['Ref&lt; EventStreamPlayback &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20fixedmaterial_20_3e',['Ref&lt; FixedMaterial &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20font_20_3e',['Ref&lt; Font &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20gdnativeclass_20_3e',['Ref&lt; GDNativeClass &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20gdscript_20_3e',['Ref&lt; GDScript &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20imagetexture_20_3e',['Ref&lt; ImageTexture &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20javaclass_20_3e',['Ref&lt; JavaClass &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20material_20_3e',['Ref&lt; Material &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20mesh_20_3e',['Ref&lt; Mesh &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20meshlibrary_20_3e',['Ref&lt; MeshLibrary &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20multimesh_20_3e',['Ref&lt; MultiMesh &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20navigationmesh_20_3e',['Ref&lt; NavigationMesh &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20navigationpolygon_20_3e',['Ref&lt; NavigationPolygon &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20occluderpolygon2d_20_3e',['Ref&lt; OccluderPolygon2D &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20packeddatacontainer_20_3e',['Ref&lt; PackedDataContainer &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20packetpeerstream_20_3e',['Ref&lt; PacketPeerStream &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20rendertargettexture_20_3e',['Ref&lt; RenderTargetTexture &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20resource_20_3e',['Ref&lt; Resource &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20resourceimportmetadata_20_3e',['Ref&lt; ResourceImportMetadata &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20roombounds_20_3e',['Ref&lt; RoomBounds &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20sample_20_3e',['Ref&lt; Sample &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20samplelibrary_20_3e',['Ref&lt; SampleLibrary &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20script_20_3e',['Ref&lt; Script &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20shader_20_3e',['Ref&lt; Shader &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20shadergraph_20_3e',['Ref&lt; ShaderGraph &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20shape_20_3e',['Ref&lt; Shape &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20shape2d_20_3e',['Ref&lt; Shape2D &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20spatialeditorgizmo_20_3e',['Ref&lt; SpatialEditorGizmo &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20spriteframes_20_3e',['Ref&lt; SpriteFrames &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20streampeer_20_3e',['Ref&lt; StreamPeer &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20streampeertcp_20_3e',['Ref&lt; StreamPeerTCP &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20stylebox_20_3e',['Ref&lt; StyleBox &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20styleboxtexture_20_3e',['Ref&lt; StyleBoxTexture &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20tcp_5fserver_20_3e',['Ref&lt; TCP_Server &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20texture_20_3e',['Ref&lt; Texture &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20theme_20_3e',['Ref&lt; Theme &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20tileset_20_3e',['Ref&lt; TileSet &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20trianglemesh_20_3e',['Ref&lt; TriangleMesh &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20videostream_20_3e',['Ref&lt; VideoStream &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20world_20_3e',['Ref&lt; World &gt;',['../class_ref.html',1,'']]],
  ['ref_3c_20world2d_20_3e',['Ref&lt; World2D &gt;',['../class_ref.html',1,'']]],
  ['reference',['Reference',['../class_reference.html',1,'']]],
  ['referenceframe',['ReferenceFrame',['../class_reference_frame.html',1,'']]],
  ['refitem',['RefItem',['../struct___t_e_category_1_1_ref_item.html',1,'_TECategory']]],
  ['refptr',['RefPtr',['../class_ref_ptr.html',1,'']]],
  ['regex',['RegEx',['../class_reg_ex.html',1,'']]],
  ['register_5fcore_5ftypes',['register_core_types',['../class_core_string_names.html#aea82de8da050724530a70a57cc1bc54e',1,'CoreStringNames::register_core_types()'],['../class_string_name.html#aea82de8da050724530a70a57cc1bc54e',1,'StringName::register_core_types()']]],
  ['register_5fscene_5ftypes',['register_scene_types',['../class_scene_string_names.html#ae37abf354bfb16052fb2a81d4cc15686',1,'SceneStringNames']]],
  ['relative_5fquality',['relative_quality',['../struct_enc_state.html#a4211e850850702e37bebe9380d27c784',1,'EncState']]],
  ['releaseallconsumablestask',['ReleaseAllConsumablesTask',['../classcom_1_1android_1_1godot_1_1payments_1_1_release_all_consumables_task.html',1,'com::android::godot::payments']]],
  ['remotetransform2d',['RemoteTransform2D',['../class_remote_transform2_d.html',1,'']]],
  ['rendertargettexture',['RenderTargetTexture',['../class_render_target_texture.html',1,'']]],
  ['reopen',['reopen',['../class_file_access.html#af178c911a21acff6bfbe1aa23e8d4d51',1,'FileAccess']]],
  ['reparentdialog',['ReparentDialog',['../class_reparent_dialog.html',1,'']]],
  ['repr',['repr',['../class_theora_data_source.html#aad8c4534865a7759de651a14e4ab6829',1,'TheoraDataSource::repr()'],['../class_theora_file_data_source.html#a2ae7b0d9d2730ff5de9f281a593e24b4',1,'TheoraFileDataSource::repr()'],['../class_theora_memory_file_data_source.html#af379f0b167027562db28b0d0ebe40a9a',1,'TheoraMemoryFileDataSource::repr()'],['../class_t_p_data_f_a.html#a1ed9752ca0e55d02bd309d241322422e',1,'TPDataFA::repr()']]],
  ['requant_2ec',['requant.c',['../requant_8c.html',1,'']]],
  ['requant_2eh',['requant.h',['../requant_8h.html',1,'']]],
  ['requestabortdownload',['requestAbortDownload',['../interfacecom_1_1google_1_1android_1_1vending_1_1expansion_1_1downloader_1_1_i_downloader_service.html#a6820667ef5734399e3d4eda164f1013b',1,'com.google.android.vending.expansion.downloader.IDownloaderService.requestAbortDownload()'],['../classcom_1_1google_1_1android_1_1vending_1_1expansion_1_1downloader_1_1impl_1_1_downloader_service.html#a3ae3fa4046da6f822ccf5b48b3ddb4ff',1,'com.google.android.vending.expansion.downloader.impl.DownloaderService.requestAbortDownload()'],['../interfacecom_1_1google_1_1android_1_1vending_1_1expansion_1_1downloader_1_1_i_downloader_service.html#a6820667ef5734399e3d4eda164f1013b',1,'com.google.android.vending.expansion.downloader.IDownloaderService.requestAbortDownload()'],['../classcom_1_1google_1_1android_1_1vending_1_1expansion_1_1downloader_1_1impl_1_1_downloader_service.html#a3ae3fa4046da6f822ccf5b48b3ddb4ff',1,'com.google.android.vending.expansion.downloader.impl.DownloaderService.requestAbortDownload()']]],
  ['requestcontinuedownload',['requestContinueDownload',['../interfacecom_1_1google_1_1android_1_1vending_1_1expansion_1_1downloader_1_1_i_downloader_service.html#a71bafdd1e4ebaf94d00cccdef4022bbe',1,'com.google.android.vending.expansion.downloader.IDownloaderService.requestContinueDownload()'],['../classcom_1_1google_1_1android_1_1vending_1_1expansion_1_1downloader_1_1impl_1_1_downloader_service.html#ab52d01b0d620b0634ece380f8a39a1ef',1,'com.google.android.vending.expansion.downloader.impl.DownloaderService.requestContinueDownload()'],['../interfacecom_1_1google_1_1android_1_1vending_1_1expansion_1_1downloader_1_1_i_downloader_service.html#a71bafdd1e4ebaf94d00cccdef4022bbe',1,'com.google.android.vending.expansion.downloader.IDownloaderService.requestContinueDownload()'],['../classcom_1_1google_1_1android_1_1vending_1_1expansion_1_1downloader_1_1impl_1_1_downloader_service.html#ab52d01b0d620b0634ece380f8a39a1ef',1,'com.google.android.vending.expansion.downloader.impl.DownloaderService.requestContinueDownload()']]],
  ['requestdownloadstatus',['requestDownloadStatus',['../interfacecom_1_1google_1_1android_1_1vending_1_1expansion_1_1downloader_1_1_i_downloader_service.html#a1fb9dc23409be232db4242fe0e26d117',1,'com.google.android.vending.expansion.downloader.IDownloaderService.requestDownloadStatus()'],['../classcom_1_1google_1_1android_1_1vending_1_1expansion_1_1downloader_1_1impl_1_1_downloader_service.html#a1e0458df4af0cd4fc27f3457e522f2e8',1,'com.google.android.vending.expansion.downloader.impl.DownloaderService.requestDownloadStatus()'],['../interfacecom_1_1google_1_1android_1_1vending_1_1expansion_1_1downloader_1_1_i_downloader_service.html#a1fb9dc23409be232db4242fe0e26d117',1,'com.google.android.vending.expansion.downloader.IDownloaderService.requestDownloadStatus()'],['../classcom_1_1google_1_1android_1_1vending_1_1expansion_1_1downloader_1_1impl_1_1_downloader_service.html#a1e0458df4af0cd4fc27f3457e522f2e8',1,'com.google.android.vending.expansion.downloader.impl.DownloaderService.requestDownloadStatus()']]],
  ['requestemptyframe',['requestEmptyFrame',['../class_theora_frame_queue.html#a508170de2bca6be25f8ef6006f91ba02',1,'TheoraFrameQueue']]],
  ['requestparams',['RequestParams',['../classcom_1_1android_1_1godot_1_1utils_1_1_request_params.html',1,'com::android::godot::utils']]],
  ['requestpausedownload',['requestPauseDownload',['../interfacecom_1_1google_1_1android_1_1vending_1_1expansion_1_1downloader_1_1_i_downloader_service.html#ab2e290b9fa07a89181fc089c216bbc51',1,'com.google.android.vending.expansion.downloader.IDownloaderService.requestPauseDownload()'],['../classcom_1_1google_1_1android_1_1vending_1_1expansion_1_1downloader_1_1impl_1_1_downloader_service.html#abeec18b8eccb670e899e745ad71d8229',1,'com.google.android.vending.expansion.downloader.impl.DownloaderService.requestPauseDownload()'],['../interfacecom_1_1google_1_1android_1_1vending_1_1expansion_1_1downloader_1_1_i_downloader_service.html#ab2e290b9fa07a89181fc089c216bbc51',1,'com.google.android.vending.expansion.downloader.IDownloaderService.requestPauseDownload()'],['../classcom_1_1google_1_1android_1_1vending_1_1expansion_1_1downloader_1_1impl_1_1_downloader_service.html#abeec18b8eccb670e899e745ad71d8229',1,'com.google.android.vending.expansion.downloader.impl.DownloaderService.requestPauseDownload()']]],
  ['requestwork',['requestWork',['../class_theora_video_manager.html#a3dc6a4c2882810b920bc4cab2d762587',1,'TheoraVideoManager']]],
  ['resample_5fsse_2eh',['resample_sse.h',['../resample__sse_8h.html',1,'']]],
  ['reserved1',['reserved1',['../struct_speex_bits.html#a223a9cae3def71643024acef6a8fa545',1,'SpeexBits::reserved1()'],['../struct_speex_callback.html#a6981467e69c0245ac1b50a41f8987030',1,'SpeexCallback::reserved1()'],['../struct_speex_header.html#ae4ac8287a9ea7c4bb084b720e4e36228',1,'SpeexHeader::reserved1()'],['../struct_speex_stereo_state.html#a6528f2af66296d2990de5800be344e1f',1,'SpeexStereoState::reserved1()'],['../struct_real_speex_stereo_state.html#a651abaa205d0d9b275d20d0ec355a063',1,'RealSpeexStereoState::reserved1()']]],
  ['reserved2',['reserved2',['../struct_speex_bits.html#afb1c453029f208b9b714a4ea2b704e04',1,'SpeexBits::reserved2()'],['../struct_speex_callback.html#a5dcc7d93302d180ce0f0cf4aab0eeb49',1,'SpeexCallback::reserved2()'],['../struct_speex_header.html#aecf3ab6d15af2fb2d3cb9b14e8e0478e',1,'SpeexHeader::reserved2()'],['../struct_speex_stereo_state.html#af12f3e1c1208acf00a4f969cf71e7e9b',1,'SpeexStereoState::reserved2()'],['../struct_real_speex_stereo_state.html#aab07dc0fd9331e3a7d6ce1f3411772de',1,'RealSpeexStereoState::reserved2()']]],
  ['reset_5fstate',['reset_state',['../struct_jitter_buffer__.html#a889658c08bead5487e3c750fc6d15fba',1,'JitterBuffer_']]],
  ['resetpolicy',['resetPolicy',['../classcom_1_1google_1_1android_1_1vending_1_1licensing_1_1_a_p_k_expansion_policy.html#a545051a6ac8f6bd9842489714824fa2f',1,'com::google::android::vending::licensing::APKExpansionPolicy']]],
  ['resize',['resize',['../class_pool_allocator.html#a96f2a4fbf86e3db2c83e327b52c0a79d',1,'PoolAllocator']]],
  ['resize_5fto_5fpo2',['resize_to_po2',['../class_image.html#adf49a92a654c593686c4d352ae0f02bb',1,'Image']]],
  ['resource',['Resource',['../class_resource.html',1,'']]],
  ['resourcecache',['ResourceCache',['../class_resource_cache.html',1,'']]],
  ['resourceformatdds',['ResourceFormatDDS',['../class_resource_format_d_d_s.html',1,'']]],
  ['resourceformatloader',['ResourceFormatLoader',['../class_resource_format_loader.html',1,'']]],
  ['resourceformatloaderaudiostreammpc',['ResourceFormatLoaderAudioStreamMPC',['../class_resource_format_loader_audio_stream_m_p_c.html',1,'']]],
  ['resourceformatloaderaudiostreamoggvorbis',['ResourceFormatLoaderAudioStreamOGGVorbis',['../class_resource_format_loader_audio_stream_o_g_g_vorbis.html',1,'']]],
  ['resourceformatloaderaudiostreamspeex',['ResourceFormatLoaderAudioStreamSpeex',['../class_resource_format_loader_audio_stream_speex.html',1,'']]],
  ['resourceformatloaderbinary',['ResourceFormatLoaderBinary',['../class_resource_format_loader_binary.html',1,'']]],
  ['resourceformatloaderbitmap',['ResourceFormatLoaderBitMap',['../class_resource_format_loader_bit_map.html',1,'']]],
  ['resourceformatloaderchibi',['ResourceFormatLoaderChibi',['../class_resource_format_loader_chibi.html',1,'']]],
  ['resourceformatloadergdscript',['ResourceFormatLoaderGDScript',['../class_resource_format_loader_g_d_script.html',1,'']]],
  ['resourceformatloaderimage',['ResourceFormatLoaderImage',['../class_resource_format_loader_image.html',1,'']]],
  ['resourceformatloadershader',['ResourceFormatLoaderShader',['../class_resource_format_loader_shader.html',1,'']]],
  ['resourceformatloadertheme',['ResourceFormatLoaderTheme',['../class_resource_format_loader_theme.html',1,'']]],
  ['resourceformatloadervideostreamtheoraplayer',['ResourceFormatLoaderVideoStreamTheoraplayer',['../class_resource_format_loader_video_stream_theoraplayer.html',1,'']]],
  ['resourceformatloaderwav',['ResourceFormatLoaderWAV',['../class_resource_format_loader_w_a_v.html',1,'']]],
  ['resourceformatloaderxml',['ResourceFormatLoaderXML',['../class_resource_format_loader_x_m_l.html',1,'']]],
  ['resourceformatpvr',['ResourceFormatPVR',['../class_resource_format_p_v_r.html',1,'']]],
  ['resourceformatsaver',['ResourceFormatSaver',['../class_resource_format_saver.html',1,'']]],
  ['resourceformatsaverbinary',['ResourceFormatSaverBinary',['../class_resource_format_saver_binary.html',1,'']]],
  ['resourceformatsaverbinaryinstance',['ResourceFormatSaverBinaryInstance',['../class_resource_format_saver_binary_instance.html',1,'']]],
  ['resourceformatsavergdscript',['ResourceFormatSaverGDScript',['../class_resource_format_saver_g_d_script.html',1,'']]],
  ['resourceformatsaverxml',['ResourceFormatSaverXML',['../class_resource_format_saver_x_m_l.html',1,'']]],
  ['resourceformatsaverxmlinstance',['ResourceFormatSaverXMLInstance',['../class_resource_format_saver_x_m_l_instance.html',1,'']]],
  ['resourceimportmetadata',['ResourceImportMetadata',['../class_resource_import_metadata.html',1,'']]],
  ['resourceinteractiveloader',['ResourceInteractiveLoader',['../class_resource_interactive_loader.html',1,'']]],
  ['resourceinteractiveloaderbinary',['ResourceInteractiveLoaderBinary',['../class_resource_interactive_loader_binary.html',1,'']]],
  ['resourceinteractiveloaderdefault',['ResourceInteractiveLoaderDefault',['../class_resource_interactive_loader_default.html',1,'']]],
  ['resourceinteractiveloaderxml',['ResourceInteractiveLoaderXML',['../class_resource_interactive_loader_x_m_l.html',1,'']]],
  ['resourceloader',['ResourceLoader',['../class_resource_loader.html',1,'']]],
  ['resourcepreloader',['ResourcePreloader',['../class_resource_preloader.html',1,'']]],
  ['resourcepreloadereditor',['ResourcePreloaderEditor',['../class_resource_preloader_editor.html',1,'']]],
  ['resourcepreloadereditorplugin',['ResourcePreloaderEditorPlugin',['../class_resource_preloader_editor_plugin.html',1,'']]],
  ['resourcesaver',['ResourceSaver',['../class_resource_saver.html',1,'']]],
  ['resourcesaverpng',['ResourceSaverPNG',['../class_resource_saver_p_n_g.html',1,'']]],
  ['resourcesdock',['ResourcesDock',['../class_resources_dock.html',1,'']]],
  ['responsedata',['ResponseData',['../classcom_1_1google_1_1android_1_1vending_1_1licensing_1_1_response_data.html',1,'com::google::android::vending::licensing']]],
  ['restarttime',['restartTime',['../classcom_1_1google_1_1android_1_1vending_1_1expansion_1_1downloader_1_1impl_1_1_download_info.html#af54aefb6364ce546b96337c3782b5eb0',1,'com.google.android.vending.expansion.downloader.impl.DownloadInfo.restartTime(long now)'],['../classcom_1_1google_1_1android_1_1vending_1_1expansion_1_1downloader_1_1impl_1_1_download_info.html#af54aefb6364ce546b96337c3782b5eb0',1,'com.google.android.vending.expansion.downloader.impl.DownloadInfo.restartTime(long now)']]],
  ['resultcallback',['ResultCallback',['../interfacecom_1_1android_1_1godot_1_1_godot_1_1_result_callback.html',1,'com::android::godot::Godot']]],
  ['results',['results',['../structrg__etc1_1_1etc1__optimizer_1_1results.html',1,'rg_etc1::etc1_optimizer']]],
  ['retry',['RETRY',['../interfacecom_1_1google_1_1android_1_1vending_1_1licensing_1_1_policy.html#aa8c4f2b75570d969de11b071e00046c3',1,'com::google::android::vending::licensing::Policy']]],
  ['retry_5ffirst_5fdelay',['RETRY_FIRST_DELAY',['../classcom_1_1google_1_1android_1_1vending_1_1expansion_1_1downloader_1_1_constants.html#a93fe7736de8c6fc0d58ba119fae8ff10',1,'com::google::android::vending::expansion::downloader::Constants']]],
  ['reverb_5festimate',['reverb_estimate',['../struct_speex_preprocess_state__.html#a4db6450ac9e4cc7785ccaf37aa9cf62b',1,'SpeexPreprocessState_']]],
  ['reverbbufferssw',['ReverbBuffersSW',['../class_reverb_buffers_s_w.html',1,'']]],
  ['reverbparamssw',['ReverbParamsSW',['../struct_reverb_params_s_w.html',1,'']]],
  ['reverbsw',['ReverbSW',['../class_reverb_s_w.html',1,'']]],
  ['rfind',['rfind',['../class_string.html#a7629b08478db4ca0e88ec5d1de71d050',1,'String']]],
  ['rfindn',['rfindn',['../class_string.html#a4c22fd0429de3cded7cea121d4405ab2',1,'String']]],
  ['rgbabitmap',['RgbaBitmap',['../class_javelin_1_1_rgba_bitmap.html',1,'Javelin']]],
  ['rgbbitmap',['RgbBitmap',['../class_javelin_1_1_rgb_bitmap.html',1,'Javelin']]],
  ['richtext',['RichText',['../class_rich_text.html',1,'']]],
  ['richtexteditor',['RichTextEditor',['../class_rich_text_editor.html',1,'']]],
  ['richtexteditorplugin',['RichTextEditorPlugin',['../class_rich_text_editor_plugin.html',1,'']]],
  ['richtextlabel',['RichTextLabel',['../class_rich_text_label.html',1,'']]],
  ['rid',['RID',['../class_r_i_d.html',1,'']]],
  ['rid_5fowner',['RID_Owner',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20area2dsw_20_3e',['RID_Owner&lt; Area2DSW &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20areasw_20_3e',['RID_Owner&lt; AreaSW &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20bakedlight_20_3e',['RID_Owner&lt; BakedLight &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20bakedlightsampler_20_3e',['RID_Owner&lt; BakedLightSampler &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20body2dsw_20_3e',['RID_Owner&lt; Body2DSW &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20bodysw_20_3e',['RID_Owner&lt; BodySW &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20camera_20_3e',['RID_Owner&lt; Camera &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20canvas_20_3e',['RID_Owner&lt; Canvas &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20canvasitem_20_3e',['RID_Owner&lt; CanvasItem &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20canvaslightoccluderpolygon_20_3e',['RID_Owner&lt; CanvasLightOccluderPolygon &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20environment_20_3e',['RID_Owner&lt; Environment &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20fx_20_3e',['RID_Owner&lt; FX &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20immediate_20_3e',['RID_Owner&lt; Immediate &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20instance_20_3e',['RID_Owner&lt; Instance &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20joint2dsw_20_3e',['RID_Owner&lt; Joint2DSW &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20jointsw_20_3e',['RID_Owner&lt; JointSW &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20light_20_3e',['RID_Owner&lt; Light &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20lightinstance_20_3e',['RID_Owner&lt; LightInstance &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20listener_20_3e',['RID_Owner&lt; Listener &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20material_20_3e',['RID_Owner&lt; Material &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20mesh_20_3e',['RID_Owner&lt; Mesh &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20multimesh_20_3e',['RID_Owner&lt; MultiMesh &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20particles_20_3e',['RID_Owner&lt; Particles &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20particlesinstance_20_3e',['RID_Owner&lt; ParticlesInstance &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20portal_20_3e',['RID_Owner&lt; Portal &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20rasterizer_3a_3acanvasitemmaterial_20_3e',['RID_Owner&lt; Rasterizer::CanvasItemMaterial &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20rasterizer_3a_3acanvaslight_20_3e',['RID_Owner&lt; Rasterizer::CanvasLight &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20rasterizer_3a_3acanvaslightoccluderinstance_20_3e',['RID_Owner&lt; Rasterizer::CanvasLightOccluderInstance &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20room_20_3e',['RID_Owner&lt; Room &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20sample_20_3e',['RID_Owner&lt; Sample &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20sampledlight_20_3e',['RID_Owner&lt; SampledLight &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20scenario_20_3e',['RID_Owner&lt; Scenario &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20shader_20_3e',['RID_Owner&lt; Shader &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20shape2dsw_20_3e',['RID_Owner&lt; Shape2DSW &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20shapesw_20_3e',['RID_Owner&lt; ShapeSW &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20skeleton_20_3e',['RID_Owner&lt; Skeleton &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20source_20_3e',['RID_Owner&lt; Source &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20space_20_3e',['RID_Owner&lt; Space &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20space2dsw_20_3e',['RID_Owner&lt; Space2DSW &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20spacesw_20_3e',['RID_Owner&lt; SpaceSW &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20stream_20_3e',['RID_Owner&lt; Stream &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20texture_20_3e',['RID_Owner&lt; Texture &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20viewport_20_3e',['RID_Owner&lt; Viewport &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fowner_3c_20voice_20_3e',['RID_Owner&lt; Voice &gt;',['../class_r_i_d___owner.html',1,'']]],
  ['rid_5fownerbase',['RID_OwnerBase',['../class_r_i_d___owner_base.html',1,'']]],
  ['rigidbody',['RigidBody',['../class_rigid_body.html',1,'']]],
  ['rigidbody2d',['RigidBody2D',['../class_rigid_body2_d.html',1,'']]],
  ['ringbuffer',['RingBuffer',['../class_ring_buffer.html',1,'']]],
  ['ringbuffer_3c_20float_20_3e',['RingBuffer&lt; float &gt;',['../class_ring_buffer.html',1,'']]],
  ['ringbuffer_3c_20uint8_5ft_20_3e',['RingBuffer&lt; uint8_t &gt;',['../class_ring_buffer.html',1,'']]],
  ['ripemd160state_5fst',['RIPEMD160state_st',['../struct_r_i_p_e_m_d160state__st.html',1,'']]],
  ['room',['Room',['../class_room.html',1,'']]],
  ['roombounds',['RoomBounds',['../class_room_bounds.html',1,'']]],
  ['roominfo',['RoomInfo',['../struct_visual_server_raster_1_1_instance_1_1_room_info.html',1,'VisualServerRaster::Instance']]],
  ['roomspatialgizmo',['RoomSpatialGizmo',['../class_room_spatial_gizmo.html',1,'']]],
  ['rpc_5fctx',['rpc_ctx',['../structrpc__ctx.html',1,'']]],
  ['rpc_5fmsg',['rpc_msg',['../structrpc__msg.html',1,'']]],
  ['rsa_5fmeth_5fst',['rsa_meth_st',['../structrsa__meth__st.html',1,'']]],
  ['rsa_5fpkey_5fctx',['RSA_PKEY_CTX',['../struct_r_s_a___p_k_e_y___c_t_x.html',1,'']]],
  ['rsa_5fpss_5fparams_5fst',['rsa_pss_params_st',['../structrsa__pss__params__st.html',1,'']]],
  ['rsa_5fst',['rsa_st',['../structrsa__st.html',1,'']]],
  ['rterror',['RtError',['../class_rt_error.html',1,'RtError'],['../class_rt_error.html#aa479a305ccbe56be0fd9137b9b405a37',1,'RtError::RtError()']]],
  ['run',['run',['../classcom_1_1google_1_1android_1_1vending_1_1expansion_1_1downloader_1_1impl_1_1_download_thread.html#a5f752bbcd44263a8b54e3dab3148ca12',1,'com.google.android.vending.expansion.downloader.impl.DownloadThread.run()'],['../classcom_1_1google_1_1android_1_1vending_1_1expansion_1_1downloader_1_1impl_1_1_download_thread.html#a5f752bbcd44263a8b54e3dab3148ca12',1,'com.google.android.vending.expansion.downloader.impl.DownloadThread.run()']]],
  ['runsettingsdialog',['RunSettingsDialog',['../class_run_settings_dialog.html',1,'']]]
];
