var searchData=
[
  ['various_20definitions_20for_20speex_20callbacks_20supported_20by_20the_20decoder_2e',['Various definitions for Speex callbacks supported by the decoder.',['../group___speex_callbacks.html',1,'']]],
  ['v',['v',['../structyuv__buffer.html#aa429491dd112adb0254672c59ef55075',1,'yuv_buffer']]],
  ['v14customnotification',['V14CustomNotification',['../classcom_1_1google_1_1android_1_1vending_1_1expansion_1_1downloader_1_1impl_1_1_v14_custom_notification.html',1,'com::google::android::vending::expansion::downloader::impl']]],
  ['v3_5fext_5fctx',['v3_ext_ctx',['../structv3__ext__ctx.html',1,'']]],
  ['v3_5fext_5fmethod',['v3_ext_method',['../structv3__ext__method.html',1,'']]],
  ['v3customnotification',['V3CustomNotification',['../classcom_1_1google_1_1android_1_1vending_1_1expansion_1_1downloader_1_1impl_1_1_v3_custom_notification.html',1,'com::google::android::vending::expansion::downloader::impl']]],
  ['vad_5fenabled',['vad_enabled',['../struct_enc_state.html#a77c282926ea561ddcdb8d1ed81700ce9',1,'EncState::vad_enabled()'],['../struct_s_b_enc_state.html#a2c5721d38fb2588b6b4f8d6fd3d34552',1,'SBEncState::vad_enabled()']]],
  ['validatetask',['ValidateTask',['../classcom_1_1android_1_1godot_1_1payments_1_1_validate_task.html',1,'com::android::godot::payments']]],
  ['validationexception',['ValidationException',['../classcom_1_1google_1_1android_1_1vending_1_1licensing_1_1_validation_exception.html',1,'com::google::android::vending::licensing']]],
  ['vardecl',['VARDECL',['../stack__alloc_8h.html#a167f713ae96404a5d06af001669fbb4c',1,'stack_alloc.h']]],
  ['variablenode',['VariableNode',['../struct_shader_language_1_1_variable_node.html',1,'ShaderLanguage']]],
  ['variant',['Variant',['../class_variant.html',1,'']]],
  ['variantcaster',['VariantCaster',['../struct_variant_caster.html',1,'']]],
  ['variantcaster_3c_20const_20t_20_26_20_3e',['VariantCaster&lt; const T &amp; &gt;',['../struct_variant_caster_3_01const_01_t_01_6_01_4.html',1,'']]],
  ['variantcaster_3c_20t_20_26_20_3e',['VariantCaster&lt; T &amp; &gt;',['../struct_variant_caster_3_01_t_01_6_01_4.html',1,'']]],
  ['variantconstruct',['VariantConstruct',['../class_variant_construct.html',1,'']]],
  ['variantcontainer',['VariantContainer',['../struct_globals_1_1_variant_container.html',1,'Globals']]],
  ['varianthasher',['VariantHasher',['../struct_variant_hasher.html',1,'']]],
  ['varinfo',['VarInfo',['../struct_shader_language_1_1_var_info.html',1,'ShaderLanguage']]],
  ['varying',['Varying',['../structsh_1_1_varying.html',1,'sh']]],
  ['vboxcontainer',['VBoxContainer',['../class_v_box_container.html',1,'']]],
  ['vbr',['vbr',['../struct_enc_state.html#a55568eaff073d354e5921c1bed838b52',1,'EncState::vbr()'],['../struct_speex_header.html#a29870c83179a12f12c0408af4ad481c5',1,'SpeexHeader::vbr()']]],
  ['vbr_2eh',['vbr.h',['../vbr_8h.html',1,'']]],
  ['vbr_5fenabled',['vbr_enabled',['../struct_enc_state.html#a8616f8305f05306065c07ca3e5d9b3e4',1,'EncState::vbr_enabled()'],['../struct_s_b_enc_state.html#abc7a57e15c6ca4d7bdfaf73a0bff0da0',1,'SBEncState::vbr_enabled()']]],
  ['vbr_5fmax',['vbr_max',['../struct_enc_state.html#ab1fecf9be4da53f6b2d268376fad45ff',1,'EncState::vbr_max()'],['../struct_s_b_enc_state.html#a5552ccb7a7efc129caf7c37598b30133',1,'SBEncState::vbr_max()']]],
  ['vbr_5fmax_5fhigh',['vbr_max_high',['../struct_s_b_enc_state.html#adadf1597d9ae0166ba432e969682d45c',1,'SBEncState']]],
  ['vbr_5fquality',['vbr_quality',['../struct_enc_state.html#a83b8e2248e265b19a2d519438778a736',1,'EncState::vbr_quality()'],['../struct_s_b_enc_state.html#acc62bd3fa29c1c9afc2666b83325c4dd',1,'SBEncState::vbr_quality()']]],
  ['vbrstate',['VBRState',['../struct_v_b_r_state.html',1,'VBRState'],['../vbr_8h.html#a3102a36665160bea89582a317ee6c47c',1,'VBRState():&#160;vbr.h']]],
  ['vbuttonarray',['VButtonArray',['../class_v_button_array.html',1,'']]],
  ['ve_5fsetup_5fdata_5ftemplate',['ve_setup_data_template',['../structve__setup__data__template.html',1,'']]],
  ['vec3',['Vec3',['../classsquish_1_1_vec3.html',1,'squish']]],
  ['vec3f',['vec3F',['../structrg__etc1_1_1vec3_f.html',1,'rg_etc1']]],
  ['vec4',['Vec4',['../classsquish_1_1_vec4.html',1,'squish']]],
  ['vector',['Vector',['../class_vector.html',1,'']]],
  ['vector2',['Vector2',['../struct_vector2.html',1,'']]],
  ['vector3',['Vector3',['../struct_vector3.html',1,'']]],
  ['vector_3c_20_5fatlasworkrect_20_3e',['Vector&lt; _AtlasWorkRect &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20_5feditoratlasworkrect_20_3e',['Vector&lt; _EditorAtlasWorkRect &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20_5fpair_20_3e',['Vector&lt; _Pair &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20action_20_3e',['Vector&lt; Action &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20animationtreeplayer_3a_3atransitionnode_3a_3ainputdata_20_3e',['Vector&lt; AnimationTreePlayer::TransitionNode::InputData &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20areacmp_20_3e',['Vector&lt; AreaCMP &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20areadisplay_20_3e',['Vector&lt; AreaDisplay &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20areashapepair_20_3e',['Vector&lt; AreaShapePair &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20attractorcache_20_3e',['Vector&lt; AttractorCache &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20attribute_20_3e',['Vector&lt; Attribute &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20bakedlightbaker_3a_3abaketexture_20_3e',['Vector&lt; BakedLightBaker::BakeTexture &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20bakedlightbaker_3a_3alightdata_20_3e',['Vector&lt; BakedLightBaker::LightData &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20bakedlightbaker_3a_3aoctant_20_3e',['Vector&lt; BakedLightBaker::Octant &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20bakedlightbaker_3a_3atriangle_20_3e',['Vector&lt; BakedLightBaker::Triangle &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20bone_20_3e',['Vector&lt; Bone &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20bsp_5ftree_3a_3anode_20_3e',['Vector&lt; BSP_Tree::Node &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20button_20_3e',['Vector&lt; Button &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20bvh_20_3e',['Vector&lt; BVH &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20canvasitem_20_2a_20_3e',['Vector&lt; CanvasItem * &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20cell_20_3e',['Vector&lt; Cell &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20char_20_3e',['Vector&lt; char &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20chartype_20_3e',['Vector&lt; CharType &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20chessboard_3a_3aarea_3a_3aportal_20_3e',['Vector&lt; ChessBoard::Area::Portal &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20color_20_3e',['Vector&lt; Color &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20colorramp_3a_3apoint_20_3e',['Vector&lt; ColorRamp::Point &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20colorregion_20_3e',['Vector&lt; ColorRegion &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20columninfo_20_3e',['Vector&lt; ColumnInfo &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20conncache_20_3e',['Vector&lt; ConnCache &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20connection_20_3e',['Vector&lt; Connection &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20connectiondata_20_3e',['Vector&lt; ConnectionData &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20contact_20_3e',['Vector&lt; Contact &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20device_20_3e',['Vector&lt; Device &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20diritem_20_2a_20_3e',['Vector&lt; DirItem * &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20docdata_3a_3aargumentdoc_20_3e',['Vector&lt; DocData::ArgumentDoc &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20docdata_3a_3aconstantdoc_20_3e',['Vector&lt; DocData::ConstantDoc &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20docdata_3a_3amethoddoc_20_3e',['Vector&lt; DocData::MethodDoc &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20docdata_3a_3apropertydoc_20_3e',['Vector&lt; DocData::PropertyDoc &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20dvector_3c_20vector2_20_3e_20_3e',['Vector&lt; DVector&lt; Vector2 &gt; &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20edge_20_3e',['Vector&lt; Edge &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20editorexportplatform_3a_3atempdata_20_3e',['Vector&lt; EditorExportPlatform::TempData &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20editorfilesystemdirectory_20_2a_20_3e',['Vector&lt; EditorFileSystemDirectory * &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20editorfilesystemdirectory_3a_3aimportmeta_3a_3asource_20_3e',['Vector&lt; EditorFileSystemDirectory::ImportMeta::Source &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20editornodeinitcallback_20_3e',['Vector&lt; EditorNodeInitCallback &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20editorplugin_20_2a_20_3e',['Vector&lt; EditorPlugin * &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20extresoucre_20_3e',['Vector&lt; ExtResoucre &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20face_20_3e',['Vector&lt; Face &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20file_20_3e',['Vector&lt; File &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20fileinfo_20_3e',['Vector&lt; FileInfo &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20float_20_3e',['Vector&lt; float &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20gdparser_3a_3aclassnode_20_2a_20_3e',['Vector&lt; GDParser::ClassNode * &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20gdparser_3a_3aclassnode_3a_3aconstant_20_3e',['Vector&lt; GDParser::ClassNode::Constant &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20gdparser_3a_3aclassnode_3a_3amember_20_3e',['Vector&lt; GDParser::ClassNode::Member &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20gdparser_3a_3adictionarynode_3a_3apair_20_3e',['Vector&lt; GDParser::DictionaryNode::Pair &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20gdparser_3a_3afunctionnode_20_2a_20_3e',['Vector&lt; GDParser::FunctionNode * &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20gdparser_3a_3anode_20_2a_20_3e',['Vector&lt; GDParser::Node * &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20geometry_3a_3ameshdata_3a_3aedge_20_3e',['Vector&lt; Geometry::MeshData::Edge &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20geometry_3a_3ameshdata_3a_3aface_20_3e',['Vector&lt; Geometry::MeshData::Face &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20gridmap_3a_3aarea_3a_3aportal_20_3e',['Vector&lt; GridMap::Area::Portal &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20history_20_3e',['Vector&lt; History &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20input_20_3e',['Vector&lt; Input &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20instance_20_3e',['Vector&lt; Instance &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20int_20_3e',['Vector&lt; int &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20intresoucre_20_3e',['Vector&lt; IntResoucre &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20item_20_3e',['Vector&lt; Item &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20itemlistplugin_20_2a_20_3e',['Vector&lt; ItemListPlugin * &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20largetexture_3a_3apiece_20_3e',['Vector&lt; LargeTexture::Piece &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20lightmap_20_3e',['Vector&lt; LightMap &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20line_20_3e',['Vector&lt; Line &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20methodinfo_20_3e',['Vector&lt; MethodInfo &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20methodkey_20_3e',['Vector&lt; MethodKey &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20multimeshsurface_20_3e',['Vector&lt; MultiMeshSurface &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20navigation2d_3a_3apolygon_3a_3aedge_20_3e',['Vector&lt; Navigation2D::Polygon::Edge &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20navigation_3a_3apolygon_3a_3aedge_20_3e',['Vector&lt; Navigation::Polygon::Edge &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20node_20_2a_20_3e',['Vector&lt; Node * &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20nodedata_20_3e',['Vector&lt; NodeData &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20obj_20_3e',['Vector&lt; Obj &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20os_5fandroid_3a_3atouchpos_20_3e',['Vector&lt; OS_Android::TouchPos &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20os_5fjavascript_3a_3atouchpos_20_3e',['Vector&lt; OS_JavaScript::TouchPos &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20os_5fwindows_3a_3amonitorinfo_20_3e',['Vector&lt; OS_Windows::MonitorInfo &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20packedscene_3a_3anodedata_3a_3aproperty_20_3e',['Vector&lt; PackedScene::NodeData::Property &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20packsource_20_2a_20_3e',['Vector&lt; PackSource * &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20page_20_3e',['Vector&lt; Page &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20particle_20_3e',['Vector&lt; Particle &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20particlesystemprocesssw_3a_3aparticledata_20_3e',['Vector&lt; ParticleSystemProcessSW::ParticleData &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20path_20_3e',['Vector&lt; Path &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20physics2ddirectspacestate_3a_3ashaperesult_20_3e',['Vector&lt; Physics2DDirectSpaceState::ShapeResult &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20physicsdirectspacestate_3a_3ashaperesult_20_3e',['Vector&lt; PhysicsDirectSpaceState::ShapeResult &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20plane_20_3e',['Vector&lt; Plane &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20point_20_3e',['Vector&lt; Point &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20polygon_20_3e',['Vector&lt; Polygon &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20poskey_20_3e',['Vector&lt; PosKey &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20rasterizer_3a_3acanvasitem_3a_3acommand_20_2a_20_3e',['Vector&lt; Rasterizer::CanvasItem::Command * &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20rasterizerdummy_3a_3amultimesh_3a_3aelement_20_3e',['Vector&lt; RasterizerDummy::MultiMesh::Element &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20rasterizerflash_3a_3amultimesh_3a_3aelement_20_3e',['Vector&lt; RasterizerFlash::MultiMesh::Element &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20readblock_20_3e',['Vector&lt; ReadBlock &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20real_5ft_20_3e',['Vector&lt; real_t &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20rect2_20_3e',['Vector&lt; Rect2 &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20ref_3c_20animation_20_3e_20_3e',['Vector&lt; Ref&lt; Animation &gt; &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20ref_3c_20editorexportplugin_20_3e_20_3e',['Vector&lt; Ref&lt; EditorExportPlugin &gt; &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20ref_3c_20editorimportplugin_20_3e_20_3e',['Vector&lt; Ref&lt; EditorImportPlugin &gt; &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20ref_3c_20editorresourcepreviewgenerator_20_3e_20_3e',['Vector&lt; Ref&lt; EditorResourcePreviewGenerator &gt; &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20ref_3c_20editorsceneimporter_20_3e_20_3e',['Vector&lt; Ref&lt; EditorSceneImporter &gt; &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20ref_3c_20sample_20_3e_20_3e',['Vector&lt; Ref&lt; Sample &gt; &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20ref_3c_20shape2d_20_3e_20_3e',['Vector&lt; Ref&lt; Shape2D &gt; &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20ref_3c_20texture_20_3e_20_3e',['Vector&lt; Ref&lt; Texture &gt; &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20rid_20_3e',['Vector&lt; RID &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20sceneitem_20_2a_20_3e',['Vector&lt; SceneItem * &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20scenepreloader_3a_3anodedata_3a_3aproperty_20_3e',['Vector&lt; ScenePreloader::NodeData::Property &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20segment_20_3e',['Vector&lt; Segment &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20shaderlanguage_3a_3afunctionnode_3a_3aargument_20_3e',['Vector&lt; ShaderLanguage::FunctionNode::Argument &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20shaderlanguage_3a_3anode_20_2a_20_3e',['Vector&lt; ShaderLanguage::Node * &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20shaderlanguage_3a_3aprogramnode_3a_3afunction_20_3e',['Vector&lt; ShaderLanguage::ProgramNode::Function &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20shadowbuffer_20_2a_20_3e',['Vector&lt; ShadowBuffer * &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20shadowbuffer_20_3e',['Vector&lt; ShadowBuffer &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20shape_20_3e',['Vector&lt; Shape &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20shapedata_20_3e',['Vector&lt; ShapeData &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20shapepair_20_3e',['Vector&lt; ShapePair &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20source_20_3e',['Vector&lt; Source &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20spatialsound2dserversw_3a_3asource_3a_3avoice_20_3e',['Vector&lt; SpatialSound2DServerSW::Source::Voice &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20spatialsoundserversw_3a_3asource_3a_3avoice_20_3e',['Vector&lt; SpatialSoundServerSW::Source::Voice &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20string_20_3e',['Vector&lt; String &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20stringname_20_3e',['Vector&lt; StringName &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20surface_20_2a_20_3e',['Vector&lt; Surface * &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20surface_20_3e',['Vector&lt; Surface &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20tab_20_3e',['Vector&lt; Tab &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20textedit_3a_3atext_3a_3aline_20_3e',['Vector&lt; TextEdit::Text::Line &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20thread_20_2a_20_3e',['Vector&lt; Thread * &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20tkey_3c_20transformkey_20_3e_20_3e',['Vector&lt; TKey&lt; TransformKey &gt; &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20tkey_3c_20variant_20_3e_20_3e',['Vector&lt; TKey&lt; Variant &gt; &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20token_20_3e',['Vector&lt; Token &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20track_20_2a_20_3e',['Vector&lt; Track * &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20tracknodecache_20_2a_20_3e',['Vector&lt; TrackNodeCache * &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20transform_20_3e',['Vector&lt; Transform &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20treeitem_20_2a_20_3e',['Vector&lt; TreeItem * &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20treeitem_3a_3acell_3a_3abutton_20_3e',['Vector&lt; TreeItem::Cell::Button &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20uint32_5ft_20_3e',['Vector&lt; uint32_t &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20uint8_5ft_20_3e',['Vector&lt; uint8_t &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20variant_20_3e',['Vector&lt; Variant &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20variant_3a_3atype_20_3e',['Vector&lt; Variant::Type &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20vector2_20_3e',['Vector&lt; Vector2 &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20vector3_20_3e',['Vector&lt; Vector3 &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20vector_3c_20vector2_20_3e_20_3e',['Vector&lt; Vector&lt; Vector2 &gt; &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20vehiclewheel_20_2a_20_3e',['Vector&lt; VehicleWheel * &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20vertex_20_3e',['Vector&lt; Vertex &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20visibilitynotifier_20_2a_20_3e',['Vector&lt; VisibilityNotifier * &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20visualserverraster_3a_3acanvas_3a_3achilditem_20_3e',['Vector&lt; VisualServerRaster::Canvas::ChildItem &gt;',['../class_vector.html',1,'']]],
  ['vector_3c_20voice_20_3e',['Vector&lt; Voice &gt;',['../class_vector.html',1,'']]],
  ['vehiclebody',['VehicleBody',['../class_vehicle_body.html',1,'']]],
  ['vehiclewheel',['VehicleWheel',['../class_vehicle_wheel.html',1,'']]],
  ['vehiclewheelspatialgizmo',['VehicleWheelSpatialGizmo',['../class_vehicle_wheel_spatial_gizmo.html',1,'']]],
  ['vendor',['vendor',['../structth__comment.html#a93fbe894d23603f56843be15b0cbdba0',1,'th_comment::vendor()'],['../structtheora__comment.html#adb371baf8f0daed42af8b875cf8430ef',1,'theora_comment::vendor()']]],
  ['vertex',['Vertex',['../struct_surface_tool_1_1_vertex.html',1,'SurfaceTool']]],
  ['vertex',['Vertex',['../classio__scene__dae_1_1export__dae_1_1_dae_exporter_1_1_vertex.html',1,'io_scene_dae::export_dae::DaeExporter']]],
  ['vertexsorter',['VertexSorter',['../struct_triangulator_partition_1_1_vertex_sorter.html',1,'TriangulatorPartition']]],
  ['videomode',['VideoMode',['../struct_o_s_1_1_video_mode.html',1,'OS']]],
  ['videoplayer',['VideoPlayer',['../class_video_player.html',1,'']]],
  ['videostream',['VideoStream',['../class_video_stream.html',1,'']]],
  ['videostreamtheoraplayer',['VideoStreamTheoraplayer',['../class_video_stream_theoraplayer.html',1,'']]],
  ['viewcontroller',['ViewController',['../interface_view_controller.html',1,'']]],
  ['viewcontroller_28_29',['ViewController()',['../category_view_controller_07_08.html',1,'']]],
  ['viewport',['Viewport',['../class_viewport.html',1,'']]],
  ['viewportdata',['ViewportData',['../struct_spatial_indexer2_d_1_1_viewport_data.html',1,'SpatialIndexer2D']]],
  ['viewportrect',['ViewportRect',['../struct_visual_server_1_1_viewport_rect.html',1,'VisualServer']]],
  ['viewportrender',['ViewportRender',['../struct_rasterizer_1_1_canvas_item_1_1_viewport_render.html',1,'Rasterizer::CanvasItem']]],
  ['viewportsprite',['ViewportSprite',['../class_viewport_sprite.html',1,'']]],
  ['visibility_5fhidden',['VISIBILITY_HIDDEN',['../classcom_1_1google_1_1android_1_1vending_1_1expansion_1_1downloader_1_1impl_1_1_downloader_service.html#ae9b6087d88191bd37a2bc169083b39c0',1,'com::google::android::vending::expansion::downloader::impl::DownloaderService']]],
  ['visibility_5fvisible',['VISIBILITY_VISIBLE',['../classcom_1_1google_1_1android_1_1vending_1_1expansion_1_1downloader_1_1impl_1_1_downloader_service.html#a4f5a728ef01b37d66263e28cb4f1d4e1',1,'com::google::android::vending::expansion::downloader::impl::DownloaderService']]],
  ['visibility_5fvisible_5fnotify_5fcompleted',['VISIBILITY_VISIBLE_NOTIFY_COMPLETED',['../classcom_1_1google_1_1android_1_1vending_1_1expansion_1_1downloader_1_1impl_1_1_downloader_service.html#a2a0b637595c24ef0a87efae89ab784ca',1,'com::google::android::vending::expansion::downloader::impl::DownloaderService']]],
  ['visibilityenabler',['VisibilityEnabler',['../class_visibility_enabler.html',1,'']]],
  ['visibilityenabler2d',['VisibilityEnabler2D',['../class_visibility_enabler2_d.html',1,'']]],
  ['visibilitynotifier',['VisibilityNotifier',['../class_visibility_notifier.html',1,'']]],
  ['visibilitynotifier2d',['VisibilityNotifier2D',['../class_visibility_notifier2_d.html',1,'']]],
  ['visibilitynotifiergizmo',['VisibilityNotifierGizmo',['../class_visibility_notifier_gizmo.html',1,'']]],
  ['visualinstance',['VisualInstance',['../class_visual_instance.html',1,'']]],
  ['visualserver',['VisualServer',['../class_visual_server.html',1,'']]],
  ['visualserverraster',['VisualServerRaster',['../class_visual_server_raster.html',1,'']]],
  ['visualserverwrapmt',['VisualServerWrapMT',['../class_visual_server_wrap_m_t.html',1,'']]],
  ['vmap',['VMap',['../class_v_map.html',1,'']]],
  ['vmap_3c_20object_3a_3asignal_3a_3atarget_2c_20object_3a_3asignal_3a_3aslot_20_3e',['VMap&lt; Object::Signal::Target, Object::Signal::Slot &gt;',['../class_v_map.html',1,'']]],
  ['vmap_3c_20uint32_5ft_2c_20uint32_5ft_20_3e',['VMap&lt; uint32_t, uint32_t &gt;',['../class_v_map.html',1,'']]],
  ['voice',['Voice',['../struct_spatial_sound_server_s_w_1_1_source_1_1_voice.html',1,'SpatialSoundServerSW::Source']]],
  ['voice',['Voice',['../struct_spatial_sound2_d_server_s_w_1_1_source_1_1_voice.html',1,'SpatialSound2DServerSW::Source']]],
  ['voicerbsw',['VoiceRBSW',['../class_voice_r_b_s_w.html',1,'']]],
  ['volume',['Volume',['../struct_c_p_instrument_1_1_data_1_1_volume.html',1,'CPInstrument::Data']]],
  ['vorbis_5fblock',['vorbis_block',['../structvorbis__block.html',1,'']]],
  ['vorbis_5fblock_5finternal',['vorbis_block_internal',['../structvorbis__block__internal.html',1,'']]],
  ['vorbis_5fcomment',['vorbis_comment',['../structvorbis__comment.html',1,'']]],
  ['vorbis_5fdsp_5fstate',['vorbis_dsp_state',['../structvorbis__dsp__state.html',1,'']]],
  ['vorbis_5fencode_5fctl',['vorbis_encode_ctl',['../vorbisenc_8h.html#a5f398a378e20b8ce5e3341a582e773bd',1,'vorbisenc.c']]],
  ['vorbis_5fencode_5finit',['vorbis_encode_init',['../vorbisenc_8h.html#a6571d9c349c540491256f1083e1ede71',1,'vorbisenc.c']]],
  ['vorbis_5fencode_5finit_5fvbr',['vorbis_encode_init_vbr',['../vorbisenc_8h.html#ab4e3d96c3008a29c615271d1f551c2a0',1,'vorbisenc.c']]],
  ['vorbis_5fencode_5fsetup_5finit',['vorbis_encode_setup_init',['../vorbisenc_8h.html#ac3953ff69d05864e78d1858a544ed619',1,'vorbisenc.c']]],
  ['vorbis_5fencode_5fsetup_5fmanaged',['vorbis_encode_setup_managed',['../vorbisenc_8h.html#ac73714f24500e18024e83104e9e09485',1,'vorbisenc.c']]],
  ['vorbis_5fencode_5fsetup_5fvbr',['vorbis_encode_setup_vbr',['../vorbisenc_8h.html#a0f7677f216936a6cd7fa28ddbccada74',1,'vorbisenc.c']]],
  ['vorbis_5ffunc_5ffloor',['vorbis_func_floor',['../structvorbis__func__floor.html',1,'']]],
  ['vorbis_5ffunc_5fmapping',['vorbis_func_mapping',['../structvorbis__func__mapping.html',1,'']]],
  ['vorbis_5ffunc_5fresidue',['vorbis_func_residue',['../structvorbis__func__residue.html',1,'']]],
  ['vorbis_5finfo',['vorbis_info',['../structvorbis__info.html',1,'']]],
  ['vorbis_5finfo_5ffloor0',['vorbis_info_floor0',['../structvorbis__info__floor0.html',1,'']]],
  ['vorbis_5finfo_5ffloor1',['vorbis_info_floor1',['../structvorbis__info__floor1.html',1,'']]],
  ['vorbis_5finfo_5fmapping0',['vorbis_info_mapping0',['../structvorbis__info__mapping0.html',1,'']]],
  ['vorbis_5finfo_5fmode',['vorbis_info_mode',['../structvorbis__info__mode.html',1,'']]],
  ['vorbis_5finfo_5fpsy',['vorbis_info_psy',['../structvorbis__info__psy.html',1,'']]],
  ['vorbis_5finfo_5fpsy_5fglobal',['vorbis_info_psy_global',['../structvorbis__info__psy__global.html',1,'']]],
  ['vorbis_5finfo_5fresidue0',['vorbis_info_residue0',['../structvorbis__info__residue0.html',1,'']]],
  ['vorbis_5flook_5ffloor0',['vorbis_look_floor0',['../structvorbis__look__floor0.html',1,'']]],
  ['vorbis_5flook_5ffloor1',['vorbis_look_floor1',['../structvorbis__look__floor1.html',1,'']]],
  ['vorbis_5flook_5fpsy',['vorbis_look_psy',['../structvorbis__look__psy.html',1,'']]],
  ['vorbis_5flook_5fpsy_5fglobal',['vorbis_look_psy_global',['../structvorbis__look__psy__global.html',1,'']]],
  ['vorbis_5flook_5fresidue0',['vorbis_look_residue0',['../structvorbis__look__residue0.html',1,'']]],
  ['vorbis_5fmapping_5ftemplate',['vorbis_mapping_template',['../structvorbis__mapping__template.html',1,'']]],
  ['vorbis_5fresidue_5ftemplate',['vorbis_residue_template',['../structvorbis__residue__template.html',1,'']]],
  ['vorbisenc_2eh',['vorbisenc.h',['../vorbisenc_8h.html',1,'']]],
  ['vp8bitreader',['VP8BitReader',['../struct_v_p8_bit_reader.html',1,'']]],
  ['vp8bitwriter',['VP8BitWriter',['../struct_v_p8_bit_writer.html',1,'']]],
  ['vp8decoder',['VP8Decoder',['../struct_v_p8_decoder.html',1,'']]],
  ['vp8enciterator',['VP8EncIterator',['../struct_v_p8_enc_iterator.html',1,'']]],
  ['vp8encoder',['VP8Encoder',['../struct_v_p8_encoder.html',1,'']]],
  ['vp8filterheader',['VP8FilterHeader',['../struct_v_p8_filter_header.html',1,'']]],
  ['vp8finfo',['VP8FInfo',['../struct_v_p8_f_info.html',1,'']]],
  ['vp8frameheader',['VP8FrameHeader',['../struct_v_p8_frame_header.html',1,'']]],
  ['vp8io',['VP8Io',['../struct_v_p8_io.html',1,'']]],
  ['vp8lbackwardrefs',['VP8LBackwardRefs',['../struct_v_p8_l_backward_refs.html',1,'']]],
  ['vp8lbitreader',['VP8LBitReader',['../struct_v_p8_l_bit_reader.html',1,'']]],
  ['vp8lbitwriter',['VP8LBitWriter',['../struct_v_p8_l_bit_writer.html',1,'']]],
  ['vp8lcolorcache',['VP8LColorCache',['../struct_v_p8_l_color_cache.html',1,'']]],
  ['vp8ldecoder',['VP8LDecoder',['../struct_v_p8_l_decoder.html',1,'']]],
  ['vp8lencoder',['VP8LEncoder',['../struct_v_p8_l_encoder.html',1,'']]],
  ['vp8lhistogram',['VP8LHistogram',['../struct_v_p8_l_histogram.html',1,'']]],
  ['vp8lhistogramset',['VP8LHistogramSet',['../struct_v_p8_l_histogram_set.html',1,'']]],
  ['vp8lmetadata',['VP8LMetadata',['../struct_v_p8_l_metadata.html',1,'']]],
  ['vp8ltransform',['VP8LTransform',['../struct_v_p8_l_transform.html',1,'']]],
  ['vp8matrix',['VP8Matrix',['../struct_v_p8_matrix.html',1,'']]],
  ['vp8mb',['VP8MB',['../struct_v_p8_m_b.html',1,'']]],
  ['vp8mbinfo',['VP8MBInfo',['../struct_v_p8_m_b_info.html',1,'']]],
  ['vp8modescore',['VP8ModeScore',['../struct_v_p8_mode_score.html',1,'']]],
  ['vp8pictureheader',['VP8PictureHeader',['../struct_v_p8_picture_header.html',1,'']]],
  ['vp8proba',['VP8Proba',['../struct_v_p8_proba.html',1,'']]],
  ['vp8quantmatrix',['VP8QuantMatrix',['../struct_v_p8_quant_matrix.html',1,'']]],
  ['vp8residual',['VP8Residual',['../struct_v_p8_residual.html',1,'']]],
  ['vp8segmentheader',['VP8SegmentHeader',['../struct_v_p8_segment_header.html',1,'']]],
  ['vp8segmentinfo',['VP8SegmentInfo',['../struct_v_p8_segment_info.html',1,'']]],
  ['vp8threadcontext',['VP8ThreadContext',['../struct_v_p8_thread_context.html',1,'']]],
  ['vp_5fadjblock',['vp_adjblock',['../structvp__adjblock.html',1,'']]],
  ['vq_2eh',['vq.h',['../vq_8h.html',1,'']]],
  ['vq_5farm4_2eh',['vq_arm4.h',['../vq__arm4_8h.html',1,'']]],
  ['vq_5fbfin_2eh',['vq_bfin.h',['../vq__bfin_8h.html',1,'']]],
  ['vq_5fsse_2eh',['vq_sse.h',['../vq__sse_8h.html',1,'']]],
  ['vscrollbar',['VScrollBar',['../class_v_scroll_bar.html',1,'']]],
  ['vseparator',['VSeparator',['../class_v_separator.html',1,'']]],
  ['vset',['VSet',['../class_v_set.html',1,'']]],
  ['vset_3c_20areashapepair_20_3e',['VSet&lt; AreaShapePair &gt;',['../class_v_set.html',1,'']]],
  ['vset_3c_20poskey_20_3e',['VSet&lt; PosKey &gt;',['../class_v_set.html',1,'']]],
  ['vset_3c_20rid_20_3e',['VSet&lt; RID &gt;',['../class_v_set.html',1,'']]],
  ['vset_3c_20shapepair_20_3e',['VSet&lt; ShapePair &gt;',['../class_v_set.html',1,'']]],
  ['vslider',['VSlider',['../class_v_slider.html',1,'']]],
  ['vsplitcontainer',['VSplitContainer',['../class_v_split_container.html',1,'']]]
];
