#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_jsonrpc = env_modules.Clone()
env_jsonrpc.add_source_files(env["MODULES_SOURCES"], "*.cpp")

if env["tests"]:
    env_jsonrpc.add_source_files(env["MODULES_SOURCES"], "./tests/*.cpp")
