#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_vertex_optimizer = env_modules.Clone()
env_vertex_optimizer.add_source_files(env.modules_sources, "*.cpp")
