#!/usr/bin/env python

Import('env')

files = [
    'os_osx.mm',
    'godot_main_osx.mm',
    'audio_driver_osx.cpp',
    'sem_osx.cpp',
    #	'context_gl_osx.cpp',
    'dir_access_osx.mm',
    'joypad_osx.cpp',
    'power_osx.cpp',
]

env.Program('#bin/godot', files)
