#!/usr/bin/env python

Import('env')

files = [
    'crash_handler_osx.mm',
    'os_osx.mm',
    'godot_main_osx.mm',
    'audio_driver_osx.cpp',
    'sem_osx.cpp',
    #	'context_gl_osx.cpp',
    'dir_access_osx.mm',
    'joystick_osx.cpp',
]

prog = env.add_program('#bin/godot', files)

if (env['target'] == "debug" or env['target'] == "release_debug"):
    # Build the .dSYM file for atos
    action = "dsymutil " + File(prog)[0].path + " -o " + File(prog)[0].path + ".dSYM"
    env.AddPostAction(prog, action)
