#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_noise = env_modules.Clone()

thirdparty_dir = "#thirdparty/noise/"
env_noise.Prepend(CPPPATH=[thirdparty_dir])

# Godot source files

module_obj = []

env_noise.add_source_files(module_obj, "*.cpp")
env_noise.add_source_files(module_obj, "editor/*.cpp")
env.modules_sources += module_obj
