#!/usr/bin/env python

Import("env")

if env["platform"] == "linuxbsd":
    # Thirdparty source files
    thirdparty_dir = "#thirdparty/glad/"
    thirdparty_sources = [
        "egl.c",
    ]
    thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

    env.Prepend(CPPPATH=[thirdparty_dir])

    env.Append(CPPDEFINES=["EGL_ENABLED"])

    env_thirdparty = env.Clone()
    env_thirdparty.disable_warnings()
    env_thirdparty.add_source_files(env.drivers_sources, thirdparty_sources)

# Godot source files
env.add_source_files(env.drivers_sources, "*.cpp")
