name: 🤖 Build (Android)

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - '**.md'
      - '**.txt'
      - '!**/CMakeLists.txt'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - '**.md'
      - '**.txt'
      - '!**/CMakeLists.txt'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    name: "\
      ${{ matrix.platform }}-\
      ${{ matrix.arch }}-\
      ${{ matrix.double == true && 'double-' || '' }}\
      ${{ matrix.editor == true && 'editor-' || '' }}\
      ${{ matrix.config }}"

    strategy:
      fail-fast: false
      matrix:
        platform: [linux-android]
        arch: [arm64, arm32, x64, x86]
        double: [false, true]
        editor: [false, true]
        config: [debug, development, distribution]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure
        uses: ./.github/actions/cmake-configure
        with:
          platform: ${{ matrix.platform }}
          arch: ${{ matrix.arch }}
          double: ${{ matrix.double }}
        env:
          CXXFLAGS: -Werror

      - name: Build
        uses: ./.github/actions/cmake-build
        with:
          platform: ${{ matrix.platform }}
          arch: ${{ matrix.arch }}
          editor: ${{ matrix.editor }}
          config: ${{ matrix.config }}
