#!/usr/bin/env python

from typing import TYPE_CHECKING

from SCons.Script.SConscript import SConsEnvironment

if TYPE_CHECKING:
    env = SConsEnvironment()
    env_modules = SConsEnvironment()
    Import = SConsEnvironment.Import

Import("env")
Import("env_modules")

env_dds = env_modules.Clone()

env_dds.add_source_files(env.modules_sources, "*.cpp")
