#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_dds = env_modules.Clone()

module_obj = []

env_dds.add_source_files(module_obj, "*.cpp")

if env.editor_build:
    env_dds.add_source_files(module_obj, "editor/*.cpp")

env.modules_sources += module_obj
