#!/usr/bin/env python
from __future__ import annotations

from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_dds = env_modules.Clone()

env_dds.add_source_files(env.modules_sources, "*.cpp")
