#!/usr/bin/env python

Import("env")
Import("env_modules")

env_opensimplex = env_modules.Clone()

# Thirdparty source files
thirdparty_dir = "#thirdparty/misc/"
thirdparty_sources = [
    "open-simplex-noise.c",
]
thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

env_opensimplex.Prepend(CPPPATH=[thirdparty_dir])

env_thirdparty = env_opensimplex.Clone()
env_thirdparty.disable_warnings()
env_thirdparty.add_source_files(env.modules_sources, thirdparty_sources)

# Godot's own source files
env_opensimplex.add_source_files(env.modules_sources, "*.cpp")
