#!/usr/bin/env python3
"""Extract documentation from GDScript sources into Markdown."""
from __future__ import annotations

from pathlib import Path
from datetime import date
import re

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "api" / "gdscript_reference.md"
SOURCE_ROOTS = (
    ROOT / "modules" / "gaussian_splatting",
    ROOT / "scripts",
    ROOT / "tests" / "runtime",
    ROOT / "tests" / "examples" / "godot" / "test_project",
)

FUNC_PATTERN = re.compile(r"^\s*func\s+(?P<name>[^(]+)\((?P<params>[^)]*)\)")
CLASS_PATTERN = re.compile(r"^\s*class_name\s+(?P<name>[A-Za-z0-9_]+)")


def extract_docs(path: Path) -> dict[str, dict[str, str]]:
    docs: dict[str, dict[str, str]] = {}
    current_class = path.stem
    lines = path.read_text(encoding="utf-8").splitlines()
    for idx, line in enumerate(lines):
        class_match = CLASS_PATTERN.match(line)
        if class_match:
            current_class = class_match.group("name")
            docs.setdefault(current_class, {})
            continue

        func_match = FUNC_PATTERN.match(line)
        if func_match:
            func_name = func_match.group("name").strip()
            params = func_match.group("params").strip()
            signature = f"{func_name}({params})" if params else f"{func_name}()"
            doc_lines = []
            lookback = idx - 1
            while lookback >= 0 and lines[lookback].strip().startswith("##"):
                doc_lines.append(lines[lookback].strip().lstrip("# "))
                lookback -= 1
            doc_lines.reverse()
            docs.setdefault(current_class, {})[signature] = " ".join(doc_lines) if doc_lines else "(undocumented)"
    return docs


def collect_sources() -> list[Path]:
    sources: list[Path] = []
    for root in SOURCE_ROOTS:
        if not root.exists():
            continue
        for path in root.rglob("*.gd"):
            if "addons" in path.parts:
                continue
            sources.append(path)
    return sorted(set(sources))


def _render_member_table(members: dict[str, str]) -> list[str]:
    rows = [
        "<table>",
        "  <thead>",
        "    <tr>",
        "      <th>Member</th>",
        "      <th>Description</th>",
        "    </tr>",
        "  </thead>",
        "  <tbody>",
    ]
    for signature, description in sorted(members.items()):
        desc = description if description and description != "(undocumented)" else "Undocumented."
        rows.extend(
            [
                "    <tr>",
                f"      <td><pre><code>{signature}</code></pre></td>",
                f"      <td>{desc}</td>",
                "    </tr>",
            ]
        )
    rows.extend(["  </tbody>", "</table>"])
    return rows


def build_reference() -> str:
    sections = [
        "# GDScript API Reference",
        "",
        f"Last generated: {date.today().isoformat()}",
        "",
    ]
    for script in sorted(collect_sources()):
        docs = extract_docs(script)
        if not docs:
            continue
        sections.append("## Script")
        sections.append("")
        sections.append("```")
        sections.append(str(script.relative_to(ROOT)))
        sections.append("```")
        sections.append("")
        for class_name, members in docs.items():
            sections.append("### Class")
            sections.append("")
            sections.append("```")
            sections.append(class_name)
            sections.append("```")
            sections.append("")
            if not members:
                sections.append("No documented functions.")
                sections.append("")
                continue
            sections.extend(_render_member_table(members))
            sections.append("")
    sections.extend(
        [
            "Generated by:",
            "",
            "```",
            "scripts/extract_gdscript_docs.py",
            "```",
        ]
    )
    return "\n".join(sections).strip() + "\n"


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(build_reference(), encoding="utf-8")
    print(f"[docs] Wrote GDScript reference to {OUTPUT}")


if __name__ == "__main__":
    main()
