#!/usr/bin/python3

import argparse
import os


def __make_platform_logo(input: str, output: str, platform: str):
    filedata: str = ''
    filename, _ = os.path.splitext(os.path.basename(input))
    with open(input, 'rb') as pngf:
        filedata = " /* AUTOGENERATED FILE, DO NOT EDIT */ \n"
        filedata += " static const unsigned char _" + \
            platform + "_" + filename + "[]={"

        png_binary = pngf.read(1)
        while len(png_binary) == 1:
            filedata += hex(ord(png_binary))
            png_binary = pngf.read(1)
            if len(png_binary) == 1:
                filedata += ","

        filedata += "};\n"

    with open(output, 'w') as pngw:
        pngw.write(filedata)


if __name__ == "__main__":
    parser = argparse.ArgumentParser("Generator for platform logos.")

    parser.add_argument('input', type=str, help='The input image binary file.')
    parser.add_argument('output', type=str,
                        help='The output generated header file.')
    parser.add_argument('platform', type=str,
                        help='The platform this logo is for.')

    args = parser.parse_args()

    __make_platform_logo(args.input, args.output, args.platform)
