#!/usr/bin/env python

Import("env")
Import("env_modules")

freetype_enabled = env.module_check_dependencies("text_server_fb", ["freetype"], True)
msdngen_enabled = env.module_check_dependencies("text_server_fb", ["msdfgen"], True)

env_text_server_fb = env_modules.Clone()

if msdngen_enabled:
    env_text_server_fb.Append(
        CPPPATH=[
            "#thirdparty/msdfgen",
        ]
    )

if freetype_enabled:
    env_text_server_fb.Append(
        CPPPATH=[
            "#thirdparty/freetype/include",
        ]
    )

env_text_server_fb.add_source_files(env.modules_sources, "*.cpp")
