#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

import default_theme_icons_builders

env.CommandNoCache(
    "#scene/theme/default_theme_icons.gen.h",
    Glob("*.svg"),
    env.Run(default_theme_icons_builders.make_default_theme_icons_action),
)
