#!/usr/bin/env python

Import('env')


if env['disable_3d']:

    env.scene_sources.append("3d/spatial.cpp")
    env.scene_sources.append("3d/skeleton.cpp")
else:
    env.add_source_files(env.scene_sources, "*.cpp")

Export('env')
