#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

# As we have a few, not yet, converted files we name the ones we want to include:
env.GLES3_GLSL("canvas.glsl")
env.GLES3_GLSL("feed.glsl")
env.GLES3_GLSL("scene.glsl")
env.GLES3_GLSL("sky.glsl")
env.GLES3_GLSL("canvas_occlusion.glsl")
env.GLES3_GLSL("canvas_sdf.glsl")
env.GLES3_GLSL("particles.glsl")
env.GLES3_GLSL("particles_copy.glsl")
env.GLES3_GLSL("skeleton.glsl")
env.GLES3_GLSL("tex_blit.glsl")

# Once we finish conversion we can introduce this to cover all files:
# for file in Glob("*.glsl", exclude="*_inc.glsl"):
#     env.GLES3_GLSL(file)

SConscript("effects/SCsub")
