#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_dr_wav = env_modules.Clone()

# Godot source files
env_dr_wav.add_source_files(env.modules_sources, "*.cpp")
