#!/usr/bin/env python
from __future__ import annotations

from misc.utility.scons_hints import *

Import("env")

env.add_source_files(env.drivers_sources, "*.cpp")

env["check_c_headers"] = {"mntent.h": "HAVE_MNTENT"}
