#!/usr/bin/env python
from misc.utility.scons_hints import *

import swizzling_builders

Import("env")

env_variant = env.Clone()

swizzling_setget = env.CommandNoCache(
    "swizzling_setget.gen.h", "swizzling_builders.py", env.Run(swizzling_builders.swizzling_setget_builder)
)

env_variant.add_source_files(env.core_sources, "*.cpp")
env_variant.Depends("variant_setget.cpp", swizzling_setget)
