#!/usr/bin/env python
from misc.utility.scons_hints import *

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from godot_typing import GodotSConsEnvironment

    env: "GodotSConsEnvironment"
Import("env")

env_variant = env.Clone()

env_variant.add_source_files(env.core_sources, "*.cpp")
