#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_etcpak = env_modules.Clone()

# Thirdparty source files

thirdparty_obj = []

thirdparty_dir = "#thirdparty/etcpak/"
thirdparty_sources = [
    "DecodeRGB.cpp",
    "Dither.cpp",
    "ProcessDxtc.cpp",
    "ProcessRGB.cpp",
    "Tables.cpp",
]
thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

env_etcpak.Prepend(CPPPATH=[thirdparty_dir])

env_thirdparty = env_etcpak.Clone()
env_thirdparty.disable_warnings()

if env["arch"] == "x86_64" and env["extension"] == "sse42" and env.msvc:
    env_thirdparty.Append(CPPDEFINES=["__SSE3__", "__SSSE3__", "__SSE4_1__", "__SSE4_2__"])

if env["arch"] == "x86_64" and env["extension"] == "avx" and env.msvc:
    env_thirdparty.Append(CPPDEFINES=["__SSE3__", "__SSSE3__", "__SSE4_1__", "__SSE4_2__", "__AVX__"])

if env["arch"] == "x86_64" and env["extension"] == "avx2" and env.msvc:
    env_thirdparty.Append(
        CPPDEFINES=[
            "__SSE3__",
            "__SSSE3__",
            "__SSE4_1__",
            "__SSE4_2__",
            "__AVX__",
            "__AVX2__",
            "__F16C__",
            "__FMA__",
            "__BMI2__",
        ]
    )

if env["arch"] == "x86_64" and env["extension"] == "avx512" and env.msvc:
    env_thirdparty.Append(
        CPPDEFINES=[
            "__SSE3__",
            "__SSSE3__",
            "__SSE4_1__",
            "__SSE4_2__",
            "__AVX__",
            "__AVX2__",
            "__F16C__",
            "__FMA__",
            "__BMI2__",
            "__AVX512F__",
            "__AVX512DQ__",
            "__AVX512VL__",
        ]
    )

env_thirdparty.add_source_files(thirdparty_obj, thirdparty_sources)
env.modules_sources += thirdparty_obj

# Godot source files

module_obj = []

env_etcpak.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj

# Needed to force rebuilding the module files when the thirdparty library is updated.
env.Depends(module_obj, thirdparty_obj)
