#!/usr/bin/env python
from __future__ import annotations

from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_bcdec = env_modules.Clone()

# Godot source files
env_bcdec.add_source_files(env.modules_sources, "*.cpp")
