#!/usr/bin/env python

Import('env')
Import('env_modules')

env_pluginscript = env_modules.Clone()

env_pluginscript.Append(CPPPATH=['#modules/gdnative/include/'])
env_pluginscript.add_source_files(env.modules_sources, '*.cpp')
