#!/usr/bin/env python

Import("env")
Import("env_modules")

env_realtime_retarget = env_modules.Clone()
env_realtime_retarget.add_source_files(env.modules_sources, "src/*.cpp")
env_realtime_retarget.add_source_files(env.modules_sources, "*.cpp")

if env.editor_build:
    env_realtime_retarget.add_source_files(env.modules_sources, "editor/*.cpp")
    SConscript("editor/SCsub")
