name: Configure with CMake

inputs:
  platform:
    required: true
  arch:
    default: null
  double:
    default: false
  strict:
    default: true
  args:
    default: ''

runs:
  using: composite
  steps:
    - shell: pwsh
      run: cmake --version

    - shell: pwsh
      run: |
        $Platform = "${{ inputs.platform }}"
        $Arch = "${{ inputs.arch != null && format('-{0}', inputs.arch) || '' }}"
        $ConfigurePreset = "$Platform$Arch"

        cmake `
          --log-level=VERBOSE `
          ${{ inputs.strict == 'true' && '--warn-uninitialized' || '' }} `
          ${{ inputs.strict == 'true' && '-Werror=dev' || '' }} `
          --preset $ConfigurePreset `
          ${{ inputs.double == 'true' && '-DGDJ_DOUBLE_PRECISION=TRUE' || '' }} `
          ${{ inputs.args }}
