#!/usr/bin/env python

import os
Import('env')

def make_debug(target, source, env):
    os.system('objcopy --only-keep-debug %s %s.debug' % (target[0], target[0]))
    os.system('strip --strip-debug --strip-unneeded %s' % (target[0]))
    os.system('objcopy --add-gnu-debuglink=%s.debug %s' % (target[0], target[0]))

common_x11 = [
    "context_gl_x11.cpp",
    "crash_handler_x11.cpp",
    "os_x11.cpp",
    "key_mapping_x11.cpp",
    "joypad_linux.cpp",
    "power_x11.cpp",
]

binary = env.Program('#bin/godot', ['godot_x11.cpp'] + common_x11)
if env["debug_symbols"] == "full" or env["debug_symbols"] == "yes":
    env.AddPostAction(binary, make_debug)
