#!/usr/bin/env python

Import('env')


common_x11 = [
    "context_gl_x11.cpp",
    "crash_handler_x11.cpp",
    "os_x11.cpp",
    "key_mapping_x11.cpp",
    "joypad_linux.cpp",
    "power_x11.cpp",
]

env.Program('#bin/godot', ['godot_x11.cpp'] + common_x11)
