#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env_error = env.Clone()

if env["tests"]:
    env_error.Append(CPPDEFINES=["TESTS_ENABLED"])

env_error.add_source_files(env.core_sources, "*.cpp")
