#!/usr/bin/env python

Import("env")

env.add_source_files(env.servers_sources, "*.cpp")
env.add_source_files(env.servers_sources, "geometry_parser_2d/*.cpp")
env.add_source_files(env.servers_sources, "geometry_parser_3d/*.cpp")
