#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

if not env["disable_navigation_2d"]:
    env.add_source_files(env.servers_sources, "navigation_path_query_parameters_2d.cpp")
    env.add_source_files(env.servers_sources, "navigation_path_query_result_2d.cpp")

if not env["disable_navigation_3d"]:
    env.add_source_files(env.servers_sources, "navigation_path_query_parameters_3d.cpp")
    env.add_source_files(env.servers_sources, "navigation_path_query_result_3d.cpp")
