#!/usr/bin/env python

Import("env")
Import("env_modules")

env_qoi = env_modules.Clone()

# Godot source files

module_obj = []

env_qoi.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj
