#!/usr/bin/env python

Import('env')
Import('env_modules')

# Thirdparty source files

env_webrtc = env_modules.Clone()
use_gdnative = env_webrtc["module_gdnative_enabled"]

if use_gdnative: # GDNative is retained in Javascript for export compatibility
    env_webrtc.Append(CPPDEFINES=['WEBRTC_GDNATIVE_ENABLED'])
    env_webrtc.Prepend(CPPPATH=["#modules/gdnative/include/"])

env_webrtc.add_source_files(env.modules_sources, "*.cpp")
