#!/usr/bin/env python

from typing import TYPE_CHECKING

from SCons.Script.SConscript import SConsEnvironment

if TYPE_CHECKING:
    env = SConsEnvironment()
    env_modules = SConsEnvironment()
    Import = SConsEnvironment.Import

Import("env")
Import("env_modules")

if env["platform"] == "web":
    env.AddJSLibraries(["native/library_godot_webxr.js"])
    env.AddJSExterns(["native/webxr.externs.js"])

env_webxr = env_modules.Clone()
env_webxr.add_source_files(env.modules_sources, "*.cpp")
