#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

if env["platform"] == "web":
    env.AddJSLibraries(["native/library_godot_webxr.js"])
    env.AddJSExterns(["native/webxr.externs.js"])

env_webxr = env_modules.Clone()
env_webxr.add_source_files(env.modules_sources, "*.cpp")
