#!/usr/bin/env python

Import("env")

from platform_methods import run_in_subprocess
import platform_macos_builders

files = [
    "os_macos.mm",
    "godot_application.mm",
    "godot_application_delegate.mm",
    "crash_handler_macos.mm",
    "macos_terminal_logger.mm",
    "display_server_macos.mm",
    "godot_button_view.mm",
    "godot_content_view.mm",
    "godot_window_delegate.mm",
    "godot_window.mm",
    "key_mapping_macos.mm",
    "godot_main_macos.mm",
    "godot_menu_delegate.mm",
    "godot_menu_item.mm",
    "dir_access_macos.mm",
    "tts_macos.mm",
    "joypad_macos.cpp",
    "vulkan_context_macos.mm",
    "gl_manager_macos_angle.mm",
    "gl_manager_macos_legacy.mm",
]

prog = env.add_program("#bin/godot", files)

if env["debug_symbols"] and env["separate_debug_symbols"]:
    env.AddPostAction(prog, run_in_subprocess(platform_macos_builders.make_debug_macos))
