#!/usr/bin/env python

Import('env')

env_spirv_reflect = env.Clone()

thirdparty_dir = "#thirdparty/spirv-reflect/"
thirdparty_sources = [
    "spirv_reflect.c"
]
    
thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

env_spirv_reflect.add_source_files(env.drivers_sources, thirdparty_sources)

Export('env')
