#!/usr/bin/env python

from typing import TYPE_CHECKING

from SCons.Script.SConscript import SConsEnvironment

if TYPE_CHECKING:
    env = SConsEnvironment()
    Import = SConsEnvironment.Import

Import("env")

# Thirdparty source files

thirdparty_dir = "#thirdparty/spirv-reflect/"
thirdparty_sources = [
    "spirv_reflect.c",
]

thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

env_thirdparty = env.Clone()
env_thirdparty.disable_warnings()

env_thirdparty.add_source_files(env.servers_sources, thirdparty_sources)
