#!/usr/bin/env python

Import("env")
Import("env_modules")

app_protocol = env_modules.Clone()

# Godot's own source files
app_protocol.add_source_files(env.modules_sources, "*.cpp")
app_protocol.add_source_files(env.modules_sources, "#thirdparty/ipc/ipc.cpp")
app_protocol.add_source_files(env.modules_sources, "#thirdparty/ipc/socket_posix.cpp")
app_protocol.add_source_files(env.modules_sources, "#thirdparty/ipc/socket_windows.cpp")
