name: Export Godot project
description: Export a test Godot project.

inputs:
  bin:
    description: The path to the Godot executable
    required: true

runs:
  using: composite
  steps:
    - name: Build test GDExtension
      shell: sh
      run: |
        cd misc/test_project/addons/test_extension/
        git clone --depth=1 https://github.com/godotengine/godot-cpp.git src/godot-cpp/
        scons target=template_debug
        scons target=template_release
        cd ../../../../

    - name: Import resources and export project
      shell: sh
      run: |
        echo "Exporting project for Linux (PCK)"
        xvfb-run ${{ inputs.bin }} --headless --path misc/test_project/ --export-pack "Linux" /tmp/test_project.pck 2>&1 | tee log.txt || true
        misc/scripts/check_ci_log.py log.txt

        echo "Exporting project for Linux (ZIP)"
        xvfb-run ${{ inputs.bin }} --headless --path misc/test_project/ --export-pack "Linux" /tmp/test_project.zip 2>&1 | tee log.txt || true
        misc/scripts/check_ci_log.py log.txt

        echo "Exporting project for Linux as dedicated server (PCK)"
        xvfb-run ${{ inputs.bin }} --headless --path misc/test_project/ --export-pack "Linux Server" /tmp/test_project_server.pck 2>&1 | tee log.txt || true
        misc/scripts/check_ci_log.py log.txt

    - name: Run project files from folder
      shell: sh
      run: |
        xvfb-run ${{ inputs.bin }} --path misc/test_project/ --audio-driver Dummy --resolution 64x64 --write-movie /tmp/test_project_folder.png --quit
        # FIXME: Not checked currently, as leaked resources on exit cause CI failures.
        # misc/scripts/check_ci_log.py log.txt

        xvfb-run ${{ inputs.bin }} --path misc/test_project/ --headless --quit

    - name: Run exported project PCK/ZIP
      shell: sh
      run: |
        xvfb-run ${{ inputs.bin }} --main-pack /tmp/test_project.pck --audio-driver Dummy --resolution 64x64 --write-movie /tmp/test_project_pck.png --quit
        # FIXME: Not checked currently, as leaked resources on exit cause CI failures.
        # misc/scripts/check_ci_log.py log.txt

        xvfb-run ${{ inputs.bin }} --main-pack /tmp/test_project.zip --audio-driver Dummy --resolution 64x64 --write-movie /tmp/test_project_zip.png --quit

        # Headless mode is implied for dedicated server PCKs.
        xvfb-run ${{ inputs.bin }} --main-pack /tmp/test_project_server.pck --quit

        echo "Checking whether video output from project folder and exported project match..."
        md5sum /tmp/test_project*.png | md5sum --check

        echo "Checking whether audio output from project folder and exported project match..."
        md5sum /tmp/test_project*.wav | md5sum --check
