name: 🍏 iOS Builds
on:
  workflow_call:

# Global Settings
env:
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: "4.0"
  SCONSFLAGS: verbose=yes warnings=extra werror=yes debug_symbols=no module_text_server_fb_enabled=yes

jobs:
  ios-template:
    # From https://docs.github.com/en/actions/how-tos/write-workflows/choose-where-workflows-run/choose-the-runner-for-a-job#choosing-github-hosted-runners
    runs-on: macos-latest
    name: Template (target=template_release)
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      # From https://github.com/actions/runner-images/blob/main/images/macos
      - name: Select Xcode 26
        run: sudo xcode-select -s /Applications/Xcode_26.0.1.app

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        continue-on-error: true

      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      - name: Compilation (arm64)
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }}
          platform: ios
          target: template_release
          tests: false

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        continue-on-error: true

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
