name: 🔗 GHA
on: [push, pull_request, merge_group]

concurrency:
  group: ci-${{ github.actor }}-${{ github.head_ref || github.run_number }}-${{ github.ref }}-runner
  cancel-in-progress: true

jobs:
#  linux-build:
#    name: 🐧 Linux
#    uses: ./.github/workflows/linux_builds.yml

  macos-build:
    name: 🍎 macOS
    uses: ./.github/workflows/macos_builds.yml
