name: 🔗 GHA

on: [pull_request, merge_group, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}|${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  static-checks:
    if: ${{ !vars.DISABLE_GODOT_CI || github.run_attempt > 1 || github.event_name == 'workflow_dispatch' }}
    name: 📊 Static checks
    uses: ./.github/workflows/static_checks.yml

  android-build:
    name: 🤖 Android
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/android_builds.yml
    secrets:
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}

  ios-build:
    name: 🍏 iOS
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/ios_builds.yml

  linux-build:
    name: 🐧 Linux
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/linux_builds.yml

  macos-build:
    name: 🍎 macOS
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/macos_builds.yml

  windows-build:
    name: 🏁 Windows
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/windows_builds.yml

  web-build:
    name: 🌐 Web
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/web_builds.yml
