#!/usr/bin/env python

Import('env')

import os
from platform_methods import run_in_subprocess
import platform_x11_builders

common_linux = [
    "x11/context_gl_x11.cpp",
    "x11/os_x11.cpp",
    "crash_handler_x11.cpp",
    "os_linux.cpp",
    "key_mapping_x11.cpp",
    "joypad_linux.cpp",
    "power_x11.cpp",
]

prog = env.add_program('#bin/godot', ['godot_linux.cpp'] + common_linux)

if (env["debug_symbols"] == "full" or env["debug_symbols"] == "yes") and env["separate_debug_symbols"]:
    env.AddPostAction(prog, run_in_subprocess(
        platform_x11_builders.make_debug_x11))
