#!/usr/bin/env python
from __future__ import annotations

from misc.utility.scons_hints import *

Import("env")

if "alsa" in env and env["alsa"]:
    if env["use_sowrap"]:
        env.add_source_files(env.drivers_sources, "asound-so_wrap.c")

env.add_source_files(env.drivers_sources, "*.cpp")
